### ISSUE TITLE
"Phone" should be lowercase

### ISSUE THREAD

**Issue by andrewgoz** [espruino/BangleApps#1014]
https://github.com/espruino/BangleApps/blob/ab7889d42897f11d7447850772c27f60c31624e1/apps/messages/app.js#L72

**Comment by gfwilliams** [comment]
What Platform are you on? because I seem to recall it's like that because on iOS it's reported as uppercase?

**Comment by gfwilliams** [comment]
Thanks :) I'll get a fix in now
