### ISSUE TITLE
[Bangle.JS 2] [Feature request] Add a setting to remove clocks from the app menu?

### ISSUE THREAD

**Issue by Aracnoss** [espruino/BangleApps#1015]
Since you can't actually (or at least, I've not been able to) properly set the clock from the clocks in the app menu. I end up just using the app manager to drop them to the bottom of the app menu, it'd be nice if there was an option to just hide clocks entirely.

I suggest an option since some people / devs, might want to temporarily view their clocks without setting it.

More of a QoL feature, but if possible it'd certainly be nice.

**Comment by zloid** [comment]
By the way, this functionality is available in the Desktop Launcher app.

**Comment by alessandrococco** [comment]
@Aracnoss Done ;-)
