### ISSUE TITLE
[Bangle.JS 2] [Feature request] Have app manager remember/set positions of app that update?

### ISSUE THREAD

**Issue by Aracnoss** [espruino/BangleApps#1016]
Since the update process is an uninstall/reinstall process, the app manager forgets the placement of any updated apps.

It'd be nice if the manager kept track of installed apps [with changed sort values from default], and would (either flagged by update or time based) monitor then reassign/remove where necessary?

**Comment by gfwilliams** [comment]
The app manager could easily store app locations in its own JSON but unless you wanted a performance hit each reboot it'd have to restore it only when you loaded the app - or I guess the App Loader could remember the sortorder in any installed apps when it reinstalls

**Comment by zloid** [comment]
Good suggestion!

I would also like to be able to install applications at the end of the list, and not at the beginning. Now this is solved only by setting negative ordinal numbers, which is not very convenient.

**Comment by thyttan** [comment]
Candidate for being closed - leave a comment if you object!

Rationale:
I'm unsure but I think this refers to launchers on the bangle itself? Both 'Launcher' and 'Desktop Launcher' seem to sort by initial letters if no other order has been manually specified in metadata.json files. So there should not be an issue with apps changing position in the launcher.

**Comment by sersorrel** [comment]
this would be nice for things like widget ordering, I think (though I don't remember how that actually works currently, only that my widgets are now in a different order after updating a bunch of apps)

**Comment by gfwilliams** [comment]
Thanks, I think this is fine to close too.

> this would be nice for things like widget ordering

Adding to app manager wouldn't really solve this I think, but if you want to change/force widget locations you can always use this app:  https://banglejs.com/apps/?id=wid_edit
