### ISSUE TITLE
gpsrec strange menu colors when entering veiw track menu

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1024]
Record 1 track
Go into GPSrec
View Tracks
View Track 0 say
The resulting menu looks odd as if its go extra highlighted menu lines ?
Screenshot attached.
![download (1)](https://user-images.githubusercontent.com/3630481/145121222-190724a9-2cb2-4ee3-a2fa-94ceb7f85152.png)

**Comment by hughbarney** [comment]
![Uploading download (2).png…]()

**Comment by gfwilliams** [comment]
Thanks -  I *thought* I had fixed this but obviously not - reproducible with:

```
g.setBgColor("#f00");
E.showMenu({
  "" : { "title" : "-- Main Menu --" },
  "One" : function() {  },
  "Two" : function() {  }
});
```

**Comment by gfwilliams** [comment]
Fixed now - this was a bug in showMenu
