### ISSUE TITLE
[Messages - Feature Request] - make the 3 buttons at the bottom of the view message larger

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1032]
When viewing a message there are 3 buttons at the bottom of the screen.  These are a little small and a bit hard to accurately tap.  They could do with being 1/3 larger in widdth and height.

**Comment by gfwilliams** [comment]
Yes - I think this could be handled just by changing the Layout library actually. I guess buttons that are supposed to be pressed should have a minimum size

**Comment by nebbishhacker** [comment]
Does `fillx` work on buttons? It would be nice to have them evenly subdivide the available space.

**Comment by gfwilliams** [comment]
It should do, yes... I guess in some cases it might be nice not to do that but I think it could just be added for the messages app at minimum.

**Comment by gfwilliams** [comment]
I think icons are actually bigger now? Could you confirm? 
![image](https://user-images.githubusercontent.com/754445/152321052-5f552dd2-de2f-4d84-9a16-8113a3ed1cda.png)

**Comment by hughbarney** [comment]
Apologies - I tend to use my googlemail account for github notifications and only read it every now and again.
Will give this a test soon.

**Comment by hughbarney** [comment]
Have finally tested.  Yes these are better.

However I personally dont see much being added by these button at all and would rather have the additional display space on the screen.

<- goes back.   I'm perfectly happy with clicking the back button, which seems intuitive to me.
Tick - haven't a clue what this actually does.
X - haven't a clue what this does or why it is needed.

The act of displaying a message on the screen is all that is needed to send any acknowledgement back to gadget bridge.  Nothing else is needed in my opinion and the Messages app would be simpler / more intuitive without these buttons.

But the original bug can be closed.

**Comment by nebbishhacker** [comment]
> Tick - haven't a clue what this actually does.
> X - haven't a clue what this does or why it is needed.

"✓" is equivalent to tapping on the notification on the phone, so e.g. if the notification is a text it'll open the messaging app on your phone.
"X" dismisses the notification on your phone.

I personally use the "X" and "<" buttons regularly, depending on whether I want to dismiss a notification completely or deal with it later.

**Comment by gfwilliams** [comment]
Link to the forum post you started too: http://forum.espruino.com/conversations/373174/#comment16408087

What the buttons do is in the README for the messages app
