### ISSUE TITLE
[Messages - Feature Request] - change the widget bar to an icon rather than flashing 'MESSAGES'

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1033]
Love the new Messages app.  But think it would be more elegant if the notification on the widget bar was a simple envelope icon, rather than a flashing 'MESSAGES' bit of text.  It does not need to flash or be so large.   The user will easily spot the appearance of an envelope ICON in the widget area.

**Comment by gfwilliams** [comment]
I bet someone will complain it's not obvious enough if we change it, but I appreciate it doesn't look that great.

Maybe it should be a setting

**Comment by jeroenpeters1986** [comment]
I was also thinking this, that it could be a setting. I was thinking of a bell tingling left and right. But I'm not even sure if I can manage that. 

Also, I have my watch/LCD to only react to the button or touch, but it seems that when I have messages it's lighting up more (but the message has already disappeared). Anyway, mightb be unrelated. I'll try to figure out the pattern. 

I will create some new icons and app-detections, I will also try to work on this

**Comment by hasmar04** [comment]
This change to an icon would also mean that the alert widget doesn't interfere with the watchface theming. 
For example, the colouring and flashing affects the appearance of the cliock face, which I'm assuming is unintended.

**Comment by jeroenpeters1986** [comment]
I worked on this and I have a test available, but it broken on some other codepart I think.

@gfwilliams when working with icons you pointed me to "use the Image Converter with crop + inverted + transparency". I got some new icons from icon8, but wanted to know if you have the icon-size in pixels you were using, and also, do you need to enable the compression at this point in the image convertor. I am not sure.

**Comment by gfwilliams** [comment]
> the colouring and flashing affects the appearance of the cliock face, which I'm assuming is unintended.

Thanks - that'd be worth filing a bug for cliock on. `cliock`'s probably not setting up the colours properly each time it renders.

@jeroenpeters1986  I just used the '30px' versions - there are certain types of B&W icons8 icons that come in that size, and that seemed fine. I don't use compression on them as they're so small it's not really worth it :)

**Comment by jeroenpeters1986** [comment]
Thanks @gfwilliams, I downloaded them as 24 and that works too now but that was just my guess. I will update them to 30px. 
Because I'm adding new icons it might be worth compressing, but I don't know if the decompression time is worth it. Do you have any insights on that?

**Comment by gfwilliams** [comment]
>  I don't know if the decompression time is worth it. Do you have any insights on that?

I'd say don't bother - if you look at the total number of characters you're putting in, you're saving maybe only 10%. The way it's done all the images are stored in flash anyway, so it's not like it will be using up RAM

**Comment by jeroenpeters1986** [comment]
Right :-) Then I hope I can make a new PR today. Just one other question: is "Messages" only for the integration with phones? If so i would like to change the icon more time to https://img.icons8.com/dusk/452/push-notifications.png and the small (default) icon to https://img.icons8.com/ios-filled/452/push-notifications.png

**Comment by jeroenpeters1986** [comment]
![ezgif-1-fbfbdcc3a6dd](https://user-images.githubusercontent.com/6328938/145826807-38e8ec54-390c-474b-8fdd-495af8c63f05.gif)
It would come down to this

**Comment by gfwilliams** [comment]
For the icon, you could use it with other devices but I think mainly it is for phones. However I think on the Bangle don't people expect the messages app to have an icon like it is at the moment? 

For the bell - that may be the same icon alarms use when set though? I guess they could be changed...

Just in future - if you type `g.dump()` in the web IDE it'll give you a nice '.png' screenshot that you can save/copy/paste - way easier than having to take photos ;)

**Comment by jeroenpeters1986** [comment]
Thanks @gfwilliams that would help for the screenshots! I dont know how to use this on the WebIDE though. 

I have checked, the bell for alarms is indeed a solid black icon, but it doesn't move. It is not that different from alarms, that is right. I didn't find a better one at the moment, but I could use one that has only outlines, or maybe even a yellow one (not sure if that would be easily seen when the LCD is off).

The new icon I was thinking about makes it look like a phone pushes it message to the watch I think, but the current one is OK too. The only thing I had 'against' it was the red dot, that might seem to indicate there was a notification already. 

I appreciate the time you take to provide me with feedback, thanks!

**Comment by gfwilliams** [comment]
Fixed with 1084
