### ISSUE TITLE
[Android Integration] Find phone not working

### ISSUE THREAD

**Issue by Saduff** [espruino/BangleApps#1038]
As mentioned in the title, the "find phone" function in the Android app on the Bangle 2 is not working, the phone does not do anything. The phone is a Xiaomi Mi 11 on MIUI 12.5 (Android 11).

I found [this](https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Find-phone) Gadgetbridge page where they say:

> In order for the Find phone feature to work correctly on Android 10 and up, Android requires that the pairing between the mobile device (phone) and the smart bracelet/watch is done via Companion Device Management, read about it here for more details.

I followed the steps there, enabled "CompanionDevice Pairing" in Gadgetbridge settings and paired the watch. However, on [this](https://www.espruino.com/Gadgetbridge) page, it's not recommended to pair. Anyway, find phone still didn't work after that.

As a side note, the other way around (to find the watch) works.

---

Update: I found that it works only when Gadgetbridge is in the foreground on the phone. The screen can be off and locked, but Gadgetbridge must be in the foreground. This must be a Gadgetbridge/MIUI issue and has nothing to do with the Bangle app. I'll close this issue soon and will post any updates here if I find how to make it work with Gadgetbridge in the background.

---

So I unpaired the watch from Bluetooth settings, disabled "CompanionDevice Pairing", reconnected from Gadgetbridge and selected "don't pair" and "find phone" still works the same way as described above, so it seems the "CompanionDevice Pairing" is not actually required.

Also, while Gadgetbridge is in the background, I do get a "Find my phone" notification, but the phone does not ring.

**Comment by gfwilliams** [comment]
Thanks for the update!

> Update: I found that it works only when Gadgetbridge is in the foreground on the phone. 

Could this be related to battery saving optimisations? I know Gadgetbridge does say you need to disable battery optimisation or the phone will try and shut it down to save power

**Comment by elrod16** [comment]
Being that it does do the notification acknowledging the "find my phone" request but stays silent, could it be a "Do Not Disturb" setting issue or the notification is set low priority? I know Google has been rolling out "Adaptive Notifications" on newer Android builds. It adjusts the priority without user input, possibly downgrading Gadget bridge.

**Comment by Saduff** [comment]
Thanks for the suggestions. I did enable Autostart and disabled battery optimizations for Gadgetbridge. It seems the issue is not that it gets killed in the background since the notification does appear. I don't see any notification priority options in MIUI. I have my phone on silent all the time, but not "Do Not Disturb" mode. If I turn silent off, the notification makes a bubble sound like all other notifications, but Gadgetbridge still doesn't ring.

Anyway, I'll close this issue soon since this is a Gadgetbridge/MIUI issue and maybe open an issue with Gadgetbridge.
