### ISSUE TITLE
"Try in emulator" throws

### ISSUE THREAD

**Issue by 23RoMax** [espruino/BangleApps#107]
Hi together,

I've pre-ordered a few days ago and wanted to tinker around in the webIDE.
However, apparently `var file = app.storage.find(f=>f.name[0]=='-');` returns nothing,
thus applications can not get loaded into the webIDE any longer and `index.js:307 No entrypoint found for mclock`is logged out.

<img width="408" alt="Screenshot 2020-02-29 at 14 06 24" src="https://user-images.githubusercontent.com/11503063/75608169-7a1a6f80-5afd-11ea-952b-999597f07207.png">

Cheers,

23Ro

**Comment by gfwilliams** [comment]
Thank you! Just fixed this. I made some quite large changes to the Espruino codebase on friday where I gave all the apps more sensible filenames (with extensions like `.js`) - the code at fault was looking for the old style names, not the new :)
