### ISSUE TITLE
Desktop Launcher - now shows itself in the launcher window ?

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1096]
screenshot attached
![download](https://user-images.githubusercontent.com/3630481/146256179-579d399f-cf7f-4ab3-a6a2-7ffe6283eb3b.png)

**Comment by elrod16** [comment]
In the app settings there is an option now to filter out launchers and clocks.

**Comment by hughbarney** [comment]
Got it.  Didn't realise.  Not a bug.  Will close this.

**Comment by hughbarney** [comment]
not a bug, there is a setting to hide them now.

**Comment by elrod16** [comment]
> Got it. Didn't realise. Not a bug. Will close this.

Yeah I think the reasoning is so that it will show up as launchable in other launchers, allowing toy to test drive it before making it your default. I personally like being able to test out watch faces and launchers without having to set than in case something REALLY doesn't work as intended.
