### ISSUE TITLE
showimg: icon is blank in the launcher, 

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1099]
Showimg: The icon comes up blank in the launcher.  Looks like there is something wrong with the icon format.

It is not clear what this app does.  When you run it you get a blank screen.
There is mention of showimg.user.img but there is no interface to upload a file - is the intention that a user uploads an image through the IDE ?  Would be good if a screenshot could be added to explain how its meant to work.
![download (1)](https://user-images.githubusercontent.com/3630481/146268094-8ce4b118-9881-4b54-8ace-baf7f736a7d9.png)

**Comment by elrod16** [comment]
Yeah the js to version evaluated in the icon isn't right. It doesn't call "heatshrink". As far as the other stuff, you're right about the IDE being the only option. Currently there doesn't seem to be any App Loader interface.

**Comment by xxDUxx** [comment]
I just fixed the launcher image, something went wrong on the first version. The app is very simple, no App Loader interface (yet). I will look into it though...

**Comment by gfwilliams** [comment]
Icon fixed now
