### ISSUE TITLE
Both GPSTIme and GPSInfo broken after watch restart until time is set from App Loader

### ISSUE THREAD

**Issue by conoro** [espruino/BangleApps#110]
GPSTime shows only the satellite animation after watch restart. 

GPSInfo only shows part of the screen from the Welcome App after watch restart. 

Both work ok if I set the time from the App Loader first.

![2020-03-04 14 01 14](https://user-images.githubusercontent.com/586566/75888947-0b525480-5e24-11ea-85df-905ae3fa2e59.jpg)
![2020-03-04 14 01 52](https://user-images.githubusercontent.com/586566/75888949-0d1c1800-5e24-11ea-9508-cf49f6548652.jpg)
![2020-03-04 14 12 52](https://user-images.githubusercontent.com/586566/75888951-0d1c1800-5e24-11ea-9b01-5c559fcb1ab5.jpg)
![2020-03-04 14 13 11](https://user-images.githubusercontent.com/586566/75888956-0db4ae80-5e24-11ea-997c-d10cb5c5f7b1.jpg)

**Comment by gfwilliams** [comment]
Thanks for this - just figured out what happened. I had this on Monday and figured it was an issue with uploading corrupt firmware (now fixed)

It's the code that attempts to update the time from GPS - it was starting at the same time as the GPS app, then shutting down the GPS. Only happens at first boot now so it should be sorted.

**Comment by conoro** [comment]
Thanks Gordon that sorted it out. One thing I've just noticed, not sure if it's new or I missed it before, but it now displays "Searching for GPS Time " on the screen any time I switch between apps (i.e. long-press BTN3). Is it actually searching and, if so, is there any battery implication for this if it's indoors and never gets the time?

**Comment by gfwilliams** [comment]
Yeah - before it was doing it, but it never told you.

There would be a (small) battery effect (40mA for 1 second). However the second you set the time correctly *or* left the GPS running enough to get a lock, you wouldn't see it at all.

**Comment by conoro** [comment]
Ah that's perfect. It's time for me to flash a bunch of older watches with the latest!

**Comment by gfwilliams** [comment]
We're just in the process of adding translation, so in a few days you might get that built in as well if you want to wait.
