### ISSUE TITLE
Unlocking app on a "Twist". Bangle.js 2

### ISSUE THREAD

**Issue by RomanistHere** [espruino/BangleApps#1107]
I don't know whether it's an intended behavior, but when I twist (after lock), screen becomes unlocked, but not highlighted. So I can scroll and tap, but it's gray as far as I don't click the button.

It kinda makes sense, but looks as a bug at the same time, because there is no setting to change it, so I decided to report it, just in case.

Can record a video if needed.

**Comment by gfwilliams** [comment]
Thanks - however you just need to update your Bangle's firmware: https://www.espruino.com/Bangle.js2#firmware-updates

This was fixed a few weeks back but the fix couldn't be done in JS - it had to be in the watch firmware itself.
