### ISSUE TITLE
Messages app: Dithered background makes text hard to read

### ISSUE THREAD

**Issue by mabuchner** [espruino/BangleApps#1109]
The dithered background in the messages app (with dark theme) sometimes makes it difficult to read the text

![IMG_9481](https://user-images.githubusercontent.com/6006874/146385764-b93a869e-9508-403d-a0e2-b592d524b5bd.jpg)

Maybe a solid background colour or at least a solid background behind the text would help.

**Comment by gfwilliams** [comment]
Ouch - thanks! I wasn't aware that happened. On light themes the main text's background is plain (like the widget bar) and I'd expected the same here.

**Comment by mabuchner** [comment]
I've just opened the same message manually and now the text background uses the same background as the title bar. The message text is then readable, but I'm not sure, if this is the intended behaviour.

**Comment by gfwilliams** [comment]
Ok - so how did you open the message first time when you got this to happen?

**Comment by mabuchner** [comment]
If I click the bird button and then go back, then the message background is black.

**Comment by mabuchner** [comment]
Feels to me like a call to `g.setBgColor` is missing.

**Comment by gfwilliams** [comment]
Closing as this has been tweaked now and I feel like it's much improved:

![image](https://user-images.githubusercontent.com/754445/152320038-462c0343-91cd-4806-8e8c-a2c25500b5a7.png)

![image](https://user-images.githubusercontent.com/754445/152320083-5f05d213-49be-41a4-b340-26a555ea7b58.png)
