### ISSUE TITLE
Firmware Updates via Web IDE fails

### ISSUE THREAD

**Issue by RomanistHere** [espruino/BangleApps#1110]
I managed to update it via nRF toolbox, however still want to report the issue with web IDE. During ~15-20 tries I got the same two errors:

![image](https://user-images.githubusercontent.com/49812531/146399879-41ff82ad-160e-48bb-ae77-d815f1e00823.png)
![image](https://user-images.githubusercontent.com/49812531/146399886-511ce976-eaee-4f71-b109-884f8d6a83bf.png)

"Updating" popup didn't go after errors happened and if console wasn't opened, there'd no chances to understand whether something is going on or not. 

Watch showed either "connect, start, error" or "connect, error". Reset to default and factory reset didn't help.

**Comment by gfwilliams** [comment]
Thanks - sorry for the delay following this up. Just tried here and it's fine on Linux. I got an error once on Android but then it worked fine - i'll have to see if it's reproducable on Windows.

Did you get the problem every time, or did it work sometimes?

**Comment by RomanistHere** [comment]
every time

**Comment by gfwilliams** [comment]
Web IDE flasher has now been improved for 6+ months. No reports anywhere of issues now so I think we're good now
