### ISSUE TITLE
[BangleJS 2] [Feature request] Commandline-Clock JS2 Enhanced - Add option to change date locale to Month/Day/Year

### ISSUE THREAD

**Issue by Izaic** [espruino/BangleApps#1116]
For American losers out there, this would be a neat option, though far from necessary.

**Comment by gfwilliams** [comment]
If this used the `locale` library it should change automatically when the `Languages` app is installed

**Comment by gfwilliams** [comment]
... and its does! Just install the Languages app set to US and it'll work
