### ISSUE TITLE
BangleApps/apps/health/ wrong month

### ISSUE THREAD

**Issue by markcra** [espruino/BangleApps#1119]
On my newly received Bangle.js 2 I have gathered a little health data using the Health Tracking app. I just exported it in csv format and it has stored the data with the wrong month, showing as November instead of December. Watch apps know that it is currently December so I don't believe the time/date is set wrongly (it was automatically set when I connected to the App Loader I believe).

[Bangle.js Health 2021-11.csv](https://github.com/espruino/BangleApps/files/7730739/Bangle.js.Health.2021-11.csv)

**Comment by gfwilliams** [comment]
ok, thanks! Yes, looks like we store the data in a file that's named `health-year-month`, but month was 0-based.

I've just fixed the file naming, but it'll mess up existing health recordings (leaving everything before classed as 'november').

Still, everyone has max 1 month of data and it'll take 5 minutes to copy and paste the rows of CSV file
