### ISSUE TITLE
Circleclock icon is 178x178 and takes up whole screen in dtlauncher

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1121]
Tried to contact the developer through github but can't figure out how to PM on github.
![download (2)](https://user-images.githubusercontent.com/3630481/146467848-487293d0-b798-4c71-9b09-e9b01d4914c8.png)

**Comment by nebbishhacker** [comment]
I've noticed a couple other incorrectly sized icons (albeit not that dramatic). I wonder if it'd be worth adding an icon size check to sanitycheck.js.

**Comment by myxor** [comment]
Circles clock icon is fixed via https://github.com/espruino/BangleApps/pull/1113

**Comment by gfwilliams** [comment]
Thanks! I've been been through using @nebbishhacker's sanitytest additions and have fixed all the massively big or broken icons.

I haven't fixed all the ones that are too big though - I notice you've got a few too @hughbarney!

> Warning: JS icon pebble.img should be 48x48px but is instead 64x64px
> Warning: JS icon rebble.img should be 48x48px but is instead 64x64px

**Comment by hughbarney** [comment]
@gfwilliams - oops, its a size setting thats difficult to remember.  It the size you choose works, then you don't question if you got the size right or not.   Maybe a tickbox on the imageInverter that said - [x] this is (48x48) an icon for a Bangle App.
