### ISSUE TITLE
thermometer 0.05  (bangle1) issue displaying

### ISSUE THREAD

**Issue by dapgo** [espruino/BangleApps#1125]
After opening the app i can see 

-  temperature  overlapping top widget area
- sometimes temperature goes to fg and widgets disappear
- othertime widgets are displayed over temperature
- part of the digits of temperature out of  top of the display
- "eading temperature.." string always and placed in the middle of the screen

**Comment by gfwilliams** [comment]
Eep. ok - is bootloader up to date on your Bangle 1? I imagine the issue would be if appRect isn't set, but that should be polyfilled by the bootloader

**Comment by gfwilliams** [comment]
Ahh - thanks! So I guess the issue is the bootloader file doesn't update when the firmware updates. I'll file a new issue for that.

**Comment by gfwilliams** [comment]
This is fixed now - it checks the git commit and reloads if it changed
