### ISSUE TITLE
Pebbled: - might be a good idea to set battery level warning from a seting as 15% might be too low.

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1129]
Hi there @RomanistHere.  I see my Pebble watch has been Pebbled :)
Just a note about setting the battery warning to 15%.  

The battery charge tends to fall off a cliff after about 30%.  In the space of 1 hour you can be in 30% the next minute your watch has shutdown as your are out of charge.  I'm wondering if the warning level % should be set from a settings menu ?

**Comment by RomanistHere** [comment]
Hi :) 

I haven't experienced it yet. If that's the case I'd suggest another way to inform the user about, like making some parts of screen or elements change colors.

For example, boot and calendar icons become yellow at 30%, and red at 15%.

Or we could move kilometers to the left corner and add battery widget at right one.

**Comment by hughbarney** [comment]
dont think this is ever going to get done.  Closing.
