### ISSUE TITLE
Looks like widgets  position is fare to left., cant see them

### ISSUE THREAD

**Issue by MaBecker** [espruino/BangleApps#114]
Running on   VERSION: "2v04.379"

Bluetooth Widget (v0.02)

![far_too_left](https://user-images.githubusercontent.com/15932646/75997519-bd128380-5eff-11ea-9a95-a482747188bd.jpg)

**Comment by MaBecker** [comment]
Just updated to latest version.

Work as expected.

**Comment by gfwilliams** [comment]
Yeah, while I have the big note up there saying to update, I thought I'd make some breaking changes :)
