### ISSUE TITLE
Messages:   chopping off text while justifying, not using full screen space, FIX

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1147]
Got sent a 6 digit pass code from Amazon.  Only the last 3 digits could be read.

Would take a screenshot but as soon as disconnect gadgetbrudge the bangle says no more messages.
I will try a photo next time.

**Comment by hughbarney** [comment]
OK this is a bit more complicated.  There is a general issue with justifying the text into lines.  Here are a couple of examples. Apologies about the poor quality of the photo's.  1) In the first example the bulk of the text is split onto the first line but then the start and end of the first line are clipped off the end.    This example was created using the Android GadgetBridge debug facility to send a message.  2) in the second example I got an email pop up.  The text is rendered only using the inner half of the screen across 4 lines.
![IMG_20211220_211151](https://user-images.githubusercontent.com/3630481/146836469-1e05c3c8-706e-4a3e-89cf-9ba670dccd18.jpg)
![IMG_20211220_212109](https://user-images.githubusercontent.com/3630481/146836484-b1d25ff6-ce78-426c-9ad7-599d51600ad4.jpg)

**Comment by hughbarney** [comment]
![IMG_20211220_212109](https://user-images.githubusercontent.com/3630481/146836931-24f599bc-ed2d-4ac9-b4b0-93fc43c6389a.jpg)
![IMG_20211220_211151](https://user-images.githubusercontent.com/3630481/146836947-82034b67-044c-4422-a075-09872fbce4a2.jpg)

**Comment by hughbarney** [comment]
In the 2nd screenshow above the text is:

"Testing and the beanstalk the same time and hear the tragic news"
     What is seen is:
"ting and the beanstalk the same t
    and hear the tragic news"

**Comment by hughbarney** [comment]
ok - worked out a fix.  We need to set the font to the font that will be used to display the body of the text before calling g.wrapString();

g.setFont(fontMedium);
lines = g.wrapString(msg.body, g.getWidth()-10);

![IMG_20211220_222049](https://user-images.githubusercontent.com/3630481/146841012-e84c3568-bbfe-4f88-b9ca-157321d887dd.jpg)

**Comment by gfwilliams** [comment]
Great - thanks for sorting this! I must not have seen it because I only tested when the title was long so the title font was small
