### ISSUE TITLE
Dev Stopwatch app does not work

### ISSUE THREAD

**Issue by zloid** [espruino/BangleApps#1157]
@Ronin0000 Hey! Thanks for the Dev Stopwatch app! App really handy and helpful. But at the moment it doesn't work on Bangle.js v1 :(

And how about time counting down endlessly in minutes? For example, with a limit of 24 hours?

**Comment by Ronin0000** [comment]
Hi @zloid I am not the creator of the app so I can not help you. You might of got confused that I was the creator because I added a screenshot at was the most recent commit.
![image](https://user-images.githubusercontent.com/89286474/147428496-f71883db-4d92-4f65-ae65-45f5fbad26f1.png)

**Comment by zloid** [comment]
@Ronin0000 haha :) That's right, sorry :)

**Comment by zloid** [comment]
@ukaoskid @fergalwalsh Hi! Maybe you can help with this problem?

**Comment by ukaoskid** [comment]
Hey guys, I am gonna take a look to this

**Comment by DDDanny** [comment]
_Root Cause_ ...with the bangle2 adoption `setUI` instead of `on watch` the app button handler was brocken.
@ukaoskid seems you are busy and I asked a lot of questions, so I decided to try to close an issue.
And it helps me to get more and more fluent with VS Code and git
