### ISSUE TITLE
Request: Make font converter slider go up to 120

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1168]
When looking to convert a large font you often want to set the slider at 90.
The generated font size will say 61 or some other number.
In order to get a font at actual size 90 the slider would need to be set much higher - say at 120.
Obviously this is not an exact science and depends a lot on the font being loaded.
But going higher would allow more fonts with 2 digits that will fill the width or height of the screen.
Whilst it is possible to scale the fonts - they often come out better if they are done at the size you want rather than scale up later.

**Comment by gfwilliams** [comment]
Thanks - just done. Will push live soon
