### ISSUE TITLE
nbr.toString(36) related issues in App Loader and Web IDE

### ISSUE THREAD

**Issue by sebi5361** [espruino/BangleApps#117]
I have noticed some issues manipulating storage files with numbers higher than 9.
E.g., track number 10 storage file `.gpsrca` cannot be:
- downloaded properly nor erased by the App Loader GPS Recorder `interface.html` panel,
- deleted by the Web IDE device storage panel.

However it can be deleted properly by using the watch GPS Recorder app interface.

**Comment by gfwilliams** [comment]
Interesting - thanks! Just fixed both issues.

Seems I fell into another slightly dodgy bit of JS :)
