### ISSUE TITLE
widpedom:   fix for big text size on start up, when lock widget kicks in

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1170]
I have noticed an issue with widpedom when it starts up the size is not setting correctly, when the lock widget kicks in you get whats in the screenshot below.

I have experimented with various fixes but the only thing thta worked reliably was to put
  }
  WIDGETS["wpedom"].reload();
})()

at the bottom of the code.  This seems to work. Have been running with this for 5 days and not see an issues.
But I am not sure if that would an acceptable soultion.
![pedom_error](https://user-images.githubusercontent.com/3630481/147351129-58a9d5f1-b6fc-4b3c-9dee-4c30b717d260.png)

![pedom_error](https://user-images.githubusercontent.com/3630481/147351162-4f62f6eb-3233-46a2-9cfe-0bc6eb62879a.png)

**Comment by gfwilliams** [comment]
Thanks - that's interesting. I'd need to look but I guess it just needs to set the width up correctly right at the start
