### ISSUE TITLE
Calendar app: numbers are barely readable

### ISSUE THREAD

**Issue by pasniak** [espruino/BangleApps#1191]
https://github.com/espruino/BangleApps/tree/master/apps/calendar

I would suggest black background instead light blue and increase font by ~30%

![IMG_20211230_132004033](https://user-images.githubusercontent.com/19778666/147778323-46b552ec-31ce-461e-bb21-e211ad21c259.jpg)

**Comment by pasniak** [comment]
Quickly improved version:

[code (8).js.txt](https://github.com/espruino/BangleApps/files/7794442/code.8.js.txt)

![IMG_20211230_144440822](https://user-images.githubusercontent.com/19778666/147783492-a82135ed-ecb5-4077-8369-9736791e047a.jpg)

**Comment by Athemis** [comment]
That has already been addressed in #1126. However, this version is currently only available from the development version of the app loader (https://espruino.github.io/BangleApps/) and not the stable one (https://banglejs.com/apps).
