### ISSUE TITLE
Invalid gpx file format generated by recorder app.

### ISSUE THREAD

**Issue by pzo** [espruino/BangleApps#1197]
The gpx file generated by the interface for the recorder app is invalid XML.
Check Apps/recorder/interface.html    the "gpx creator" node is opened twice 
`
function saveGPX(track, title) {                                                                                                                                                                                   
  var gpx =  '<?xml version="1.0" encoding="UTF-8"?>                                                                                                                                                                
<gpx creator="Bangle.js" version="1.1" ...
<gpx creator="Bangle.js" version="1.1">     
`

Also the xsi:schemaLocation part contains duplicate entries, this part is repeated four times : 
`
http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd 
`
this is sufficient : 
`
xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www.garmin.com/xmlschemas/GpxExtensionsv3.xsd http://www.garmin.com/xmlschemas/TrackPointExtension/v1 http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd"                    
`

Also the same schema is repeated in apps/banglerun/interface.html  / saveGPX function.

**Comment by gfwilliams** [comment]
Thanks! Should be fixed now I hope.

Not sure how that got so garbled - my guess is the original GPX in BangleRun was copied from somewhere online, and I just copied that for recorder and forgot to remove the 'simple' `<gpx`.
