### ISSUE TITLE
thermometer and accuracy (bangle1) 

### ISSUE THREAD

**Issue by dapgo** [espruino/BangleApps#1212]
I see that thermometer in my bangle.js1 is not showing accurate temperatures, I assume that the problem is not in this app but in the sensor or fw. 
Anyway as changes of temperatures seems coherent so maybe it can be calibrated from this app.
Also the app should detect when you have it on your wrist or not because there is a logical alteration cause by human temperature. 

![thermo_standlone-lr](https://user-images.githubusercontent.com/4981669/148185523-4f0f3e43-4758-4096-8e88-2c2650abb8bd.jpg)
![thermo_wrist-lr](https://user-images.githubusercontent.com/4981669/148185529-34a49daf-ca10-4373-9a59-ccd5a031c904.jpg)

**Comment by gfwilliams** [comment]
Yes, the app uses the CPU's internal thermometer, which needs calibration. Realistically I guess some option for calibration would need to be built into the app.

**Comment by gfwilliams** [comment]
Closing - this is for Bangle.js 1 which we stopped selling years ago, and B.js 2 has a better temp sensor inside the pressure sensor
