### ISSUE TITLE
Bangle.getHealthStatus("day").steps  - not resetting at midnight

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1216]
Bangle.getHealthStatus("day").steps is meant to provide the total steps for the current day.

However it just appears to accumulate.

11PM 4/1/22
Widpedom 3721  - Bangle.getHealthStatus("day").steps  = 6553

Next Morning 9am
Widpedom 715  - Bangle.getHealthStatus("day").steps  = 7327  (diff 6607)

12:49
Widpedom 782  - Bangle.getHealthStatus("day").steps  = 7389  (diff 6607)

We can see that Bangle.getHealthStatus("day").steps is incrementing correctly with Bangle.on('step'...)
BUT the value did not reset to 0 over midnight.

It would be great to get this fixed as it would support a whole class of simple pendoeter widgets that could have custom fonts and settings etc.

**Comment by gfwilliams** [comment]
Ok - should be fixed in the latest firmware build now I hope!
