### ISSUE TITLE
widpedom: v21 - widpedom.wid.js ReferenceError: ReferenceError: "stps" is not defined

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1233]
Started seeing this on the IDE consoe after reboot after upgrading to widpedom 0.21
Reverted to 0.20 and it went away, installed 0.21 and it came back.
Very strangs, I looked at the change and could not see an obvious reason for it.

**Comment by gfwilliams** [comment]
Thanks - just found the issue and will get a fix in now. It's odd - I'd tested this before commit and didn't see any issue but I don't see how now!
