### ISSUE TITLE
Anton clock seems to have dow string hardcoded.

### ISSUE THREAD

**Issue by pzo** [espruino/BangleApps#1259]
cfr app.js  / function draw()  :
...
    var dowwumStr = require("locale").dow(date);
      dowwumStr = "thursday";
...

**Comment by gfwilliams** [comment]
@DDDanny any idea what's going on here? This is obviously not ideal for the default clock...

**Comment by DDDanny** [comment]
Yeah, really sorry - isn't it thursday oO
I discovered and fixed this morning via Pull Request #1262
and missed to check for issues...

**Comment by gfwilliams** [comment]
Thanks! Sorry, missed your PR when I was responding here :)
