### ISSUE TITLE
Feature request: Add link to repo in the overview

### ISSUE THREAD

**Issue by msdeibel** [espruino/BangleApps#127]
It is already great that users are able to try an app from the overview in the emulator.

For devs it would be nice if the app info also contained a link to the repo where the source is located.

It would improve the ability to build on another one's code and especially for beginners provide a quicker access to code that might help them get started.

**Comment by gfwilliams** [comment]
Thanks - good idea! A little GitHub icon would be nice and wouldn't get in the way too much
