### ISSUE TITLE
OpenStreetMap: tiles without hillshade?

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#1276]
Currently we use opentopomap tiles for Openstreetmap:

https://opentopomap.org/#map=17/53.06828/-4.07828

For comparison, Snowdon again but with Openstreetmap: https://www.openstreetmap.org/node/8755297244#map=18/53.06841/-4.07670

It's neat because the colours render better in 3 bit and it also has contours which is good for walking

BUT when you have a decent size hill the hillshade darkens the map such that when converted to 3 bit you just get a big black area.

* Ideally we'd just render in the browser using colors we defined that look good on Bangle.js but that doesn't really seem possible at the moment.
* Maybe somehow we can get tiles without hillshade but with contours, but this seems tricky too.
* Or maybe we can do some filtering on the image to remove the hillshade (after all it is just grey)

**Comment by gfwilliams** [comment]
Example:

![image](https://user-images.githubusercontent.com/754445/149157106-ade1c357-4609-487f-a882-7bf1148c1c78.png)

**Comment by myxor** [comment]
A good page to try out map styles available for leaflet is this one: https://leaflet-extras.github.io/leaflet-providers/preview/

But please note that a lot of these styles require a registration and API Key and some of them have an usage policy which we have to obey.

Just wanted to leave this here so it can help us discussing this.

**Comment by gfwilliams** [comment]
Thanks - this is very handy! Makes me think there should maybe be some map style options too...

It seems very hard to find contours without hillshade, so some kind of preprocessing filter might still make sense I guess.

**Comment by myxor** [comment]
I played around with the different styles on the preview page and found these three promising:

I made screenshots and converted them using TheGIMP to 8 colors (3-bit):


# Esri WorldTopoMap
![Esri WorldTopoMap](https://user-images.githubusercontent.com/1397377/150135161-b1b6695b-5ba3-4e13-b28a-2f66ab24d0bc.png)

Pricing: free
Info about it: https://www.arcgis.com/home/item.html?id=7dc6cea0b1764a1f9af2e679f642f0f5

# CyclOSM
![CyclOSM](https://user-images.githubusercontent.com/1397377/150135166-33013559-c1df-4b1a-9410-657051c6c9ae.png)

Pricing: free
Info about it: https://www.cyclosm.org

# Thunderforest OpenCycleMam
![Thunderforest OpenCycleMap](https://user-images.githubusercontent.com/1397377/150136654-b45c5067-73de-4780-865a-45eee941b117.png)


Pricing: free until 150k tiles / month
Info about it: https://www.thunderforest.com/pricing/

**Comment by gfwilliams** [comment]
> I made screenshots and converted them using TheGIMP to 8 colors (3-bit):

Did you do this with a custom palette? Because Bangle.js 2 can only output red/green/blue on/off you really need to threshold each channel, not just choose the 8 most-used colours...

**Comment by myxor** [comment]
You are right.
I am no expert in this but i gave it another try with a custom palette of 8 colors (red, green, blue, magenta, cyan, yellow, white and black).
The palette looks like this in css:

```
/* Generated with GIMP Palette Export */
 { color: rgb(255, 0, 0) }
 { color: rgb(0, 255, 0) }
 { color: rgb(0, 0, 255) }
 { color: rgb(0, 255, 255) }
 { color: rgb(255, 0, 255) }
 { color: rgb(255, 255, 0) }
 { color: rgb(255, 255, 255) }
 { color: rgb(0, 0, 0) }
```

I hope this is correct.

The maps now looks like these:

# Esri WorldTopoMap
![Esri WorldTopoMap](https://user-images.githubusercontent.com/1397377/150152190-1ab17ff1-0a05-49ab-9195-e56753658254.png)

# CyclOSM
![CyclOSM](https://user-images.githubusercontent.com/1397377/150152197-0c8d73e8-7f35-417b-8069-9880f421bab0.png)

# Thunderforest OpenCycleMap
![Thunderforest OpenCycleMap](https://user-images.githubusercontent.com/1397377/150152201-b6b16976-b905-4cb0-b388-6c4f7716235e.png)

**Comment by gfwilliams** [comment]
Ahh - yes, that's what I'd expect. So what I do with the other tileset is I darken it slightly first.

But that brings back the main issue that the hillshade (when everything is darkened then the hillshade ends up black). But that has just made me think:

Maybe we could convert the RGB to HSB, then increase the saturation to 100%. We basically only care about the color, not the brghtness - so that could do it for us

**Comment by gfwilliams** [comment]
If you try now hopefully you will see a definite improvement. Small text is still not great - hard to know how to fix that to be honest - but most stuff works a lot better now

**Comment by myxor** [comment]
It looks like this now:

![grafik](https://user-images.githubusercontent.com/1397377/150168691-9e2832dd-0d53-4175-8472-85693db98f83.png)

Definitively a lot better as we don't have complete black areas anymore!

**Comment by gfwilliams** [comment]
Hmm, still not great. I'd added the ability to completely pull out the dark greys but then I found that the text wasn't displaying properly so I had to move the threshold back to ~50%

I think to get it better we might have to look at the surrounding area to choose where we put that threshold value. The actual text seems to be surrounded by a light halo which should help with that

**Comment by gfwilliams** [comment]
Fixed now - sadly opentopomap wasn't working for us (often tiles never loaded) so we had to move back to standard openstmap without contours.

A lot of work has gone into filtering though and it's miles better now
