### ISSUE TITLE
Weather v0.15 in app image not loading

### ISSUE THREAD

**Issue by elrod16** [espruino/BangleApps#1277]
The widget works correctly and all weather data displays except the image of the current conditions. It stays as a cloud with a question mark at all times.

**Comment by myxor** [comment]
Are you using GadgetBridge version >= 0.64.0?

It is working quiet fine on my side.

**Comment by elrod16** [comment]
Ah, I'm still on 0.63.1. I'll close this after I update if all goes well.

**Comment by myxor** [comment]
Indeed strange. And it should work for older GadgetBridge versions as well. I will have a look at the code in the next days.
