### ISSUE TITLE
Swiper Clock Launch "return" functional again

### ISSUE THREAD

**Issue by elrod16** [espruino/BangleApps#1289]
After installing firmware 2v11.23, Swiper Clock Launch's swipe to return to clock started working again. However, it does not have a blacklist or control over which swipe handlers you want active, while the new Swipe to Clock app implements this functionality better.

Also, I only have anecdotal evidence, but the return swipe handler becoming active again seemed to cause significant lag

**Comment by thyttan** [comment]
Candidate for being closed - leave a comment if you object!

Rationale:
This seems to report an absence of an issue, which shouldn't be an issue :P

There are some feature requests here, but those should probably be in a separate issue instead.

**Comment by gfwilliams** [comment]
Thanks - yes, I think this can be closed.

`swiperclocklaunch` appears to have been updated recently and so I assume isn't completely broken now.  `swp2clk` has a blacklist in it and maybe could be better, but I guess we have both and people can choose
