### ISSUE TITLE
[Messages - Feature Request] Make message timeout also apply to menu

### ISSUE THREAD

**Issue by hasmar04** [espruino/BangleApps#1313]
Currently, if a notification is deleted from the phone but there are still others remaining, the list of notifications stays open indefinitely, requiring the back button to be pressed to show the watchface again.

**Comment by Zennate** [comment]
+1 This can also become a very unfortunate combination with Spotify, which creates a music player notification that can't be closed manually, and won't be closed by the Spotify app.

**Comment by hasmar04** [comment]
Looks like this was fixed in the latest update, so going to close this issue.
