### ISSUE TITLE
configurable_clock has no JSON in apps.json 

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#1319]
@rozek  I've just merged the PR from http://forum.espruino.com/conversations/372018

And I noticed that configurable_clock never made it into apps.json. Was that the intention?

For now I'm moving it to testing so it doesn't break things, but if it wasn't then please could you put a `metadata.json` file in the app's folder and rename it back?

**Comment by gfwilliams** [comment]
Actually it's possible this is due to a merge error... Hang on - i'll check

**Comment by rozek** [comment]
Perhaps, it has been deleted by accident.

I'll try to provide the metadata a.s.a.p.

**Comment by gfwilliams** [comment]
Thanks! Just checked and I can't see it in the apps.json before the big merge, so if you were able to grab it that'd be great

**Comment by rozek** [comment]
Well, I just added the metadata.json (and removed a wrong .md file)

But what I do not understand is: "could you put a metadata.json file in the app's folder and rename it back?" What will I have to rename back?

**Comment by gfwilliams** [comment]
Thanks!

I'd moved `apps/configurable_clock` to `testing/configurable_clock` but may not have managed to push it straight away. Anyway, all moved back and fixed now
