### ISSUE TITLE
Pending Updates are not sorted to the top of the App List

### ISSUE THREAD

**Issue by andiohn** [espruino/BangleApps#1352]
It would be helpful to find out which apps are needing update before pressing "update all".
Apps that are ahead because I loaded a dev version, I don't update them, so I have to look down the list for the update icon. It would be nice to not do this.

**Comment by gfwilliams** [comment]
That sounds like a good idea to me...

**Comment by myxor** [comment]
Other idea (not exclusive to the above idea) is to have a filter alá "show only apps with updates" on the "my apps" page.

**Comment by andiohn** [comment]
Ya, that'd work too!

**Comment by hughbarney** [comment]
This would be very helpful. Was going to ask for this at some point as well.
