### ISSUE TITLE
health tracking app: graphic glitch in the widgets bar

### ISSUE THREAD

**Issue by alessandrococco** [espruino/BangleApps#1366]
I just started the HRM (3 min) and the app shows a loooong bar nevertheless there's no data yet.

![image](https://user-images.githubusercontent.com/2331798/151560350-ef4096eb-4ef1-4643-957d-fef5850579f0.png)

After returning to the menu the top of the bar remains in the widgets bar:

![image](https://user-images.githubusercontent.com/2331798/151560778-8cbf5296-d1e4-4f97-8eb5-99f8062c5e05.png)

Android 11, latest stable firmware, all apps are up to date.

**Comment by alessandrococco** [comment]
I took a look at the code - Would it make sense to remove the `drawWidgets` before drawing the bar chart?

https://github.com/espruino/BangleApps/blob/2c9e164a060d92fc751c551922bf34b01f1a5b4d/apps/health/app.js#L104 

I'd like to try to make the change:
- remove the drawWidgets() calls
- update the code to go fullscreen (steps charts also)

What do you think @gfwilliams? :-)

**Comment by gfwilliams** [comment]
It's a bit harder than just removing the drawWidgets call I'm afraid since even if you clear the screen any event that'd cause a widget to redraw (eg battery going down slightly) would put it back on the screen.

Looks like the graph drawing just needs fixing to not draw past the top of the screen - Maybe it should use Bangle.appRect to get the area it can draw in

**Comment by Ronin0000** [comment]
Do you just want the bar not to be drawn at all because there is no data or do you want it to draw a long bar in the middle, but not drawing into the widget area?

**Comment by Ronin0000** [comment]
I have made a pull request for this.

**Comment by alessandrococco** [comment]
> Do you just want the bar not to be drawn at all because there is no data or do you want it to draw a long bar in the middle, but not drawing into the widget area?

Two things:

1. If there is no data for a day/hour then the app should draw nothing for that day/hour
1. The app should not draw into the widget area

Thank you :)
