### ISSUE TITLE
App Loader "Update App Button" does not work on customizable apps.

### ISSUE THREAD

**Issue by Ronin0000** [espruino/BangleApps#1383]
When I try to use the Update Apps Button on languages, which is a customizable app than needs to be updated, it says this error:
![image](https://user-images.githubusercontent.com/89286474/152257160-41debfcd-bbae-4995-8de7-79e556f9fcb6.png)
When I press the update button on the languages app it works fine and opens the customization window.
![Screenshot 2022-02-02 154624](https://user-images.githubusercontent.com/89286474/152257106-6fd84ffe-596d-46bc-a318-8fba9617eefa.png)

**Comment by gfwilliams** [comment]
That's odd - I though we'd fixed that so the 'Update app' button didn't include customizable apps.

But the idea is that the 'Update app' button does not update custom apps. It used to AFAIK and someone filed an issue saying not to - it's not great user experience having a bunch of custom app windows popping up if you click 'Update'.

**Comment by bernhardreiter** [comment]
I am seeing the same issue, with the language app installed and customized for German.

Suggestion: If it cannot be fixed directly, the message could be changed to say something like `Updated failed, no apps can be updated automatically.  (Some apps require a manual update with configuration.)`
