### ISSUE TITLE
[Recorder v0.09] App/Settings / Recorder just hangs, no errors on IDE console.

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1401]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

In Recorder v0.09.  Go to Settings / Apps / Recorder.
The settings hang showing 'loading'.
Has been seen my 2 users.
![download (4)](https://user-images.githubusercontent.com/3630481/152696830-277749aa-49ae-480a-95e5-aeb32f383ffa.png)

**Comment by gfwilliams** [comment]
Fixed now, with 

https://github.com/espruino/BangleApps/commit/624f91d8ef3fc84a16e0ac4ad0c8499261bc1fe3
https://github.com/espruino/BangleApps/commit/fa244185ac25e357aecd2fda437c409d4b4e5663
