### ISSUE TITLE
latest upgrade mclock not visible

### ISSUE THREAD

**Issue by giacomo** [espruino/BangleApps#141]
Version 0.03

**Comment by gfwilliams** [comment]
Can you provide more info on how you got the problem? Did you try installing again?

I just did 'Install default apps' here to install everything and mclock 0.03 works great.

**Comment by giacomo** [comment]
installed reinstalled tried everything.
now I've installed again and the screen remains black only the widget starts. today received and updated all installed apps. 

and version 0.02 has run out of the box but todays update didn't work.

installed locale de
update morphing clock to 0.03

**Comment by gfwilliams** [comment]
Ok, thanks - the `de` locale was the trick.

Please can you try re-installing the `de` language now? That should have fixed it.

**Comment by giacomo** [comment]
@gfwilliams good work! awesome, thanks :rocket:
