### ISSUE TITLE
[Q alarm] Not saving configured day of week

### ISSUE THREAD

**Issue by Aracnoss** [espruino/BangleApps#1416]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

**Description**
Q alarm app not saving configured days of week on any alarms.

**Expected**
Q alarm app saves days of week configured per alarm.

**Steps to recreate**
1. Create/alter any alarm within Q alarm.
2. Attempt to change default days of week.
3. Save alarm changes.
4. Alter same alarm
5. View days of week again
6. Will be default values. (Note: not just visual bug, alarms will go off every day regardless of settings)

**Comment by HilmarSt** [comment]
There's sth. wrong with storing the DoW setting in qalarm.json: No matter what and how many weekday(s) you disable, there's only one "false" and it's is always in the last position of _daysOfWeek_.
<code>
[{"t":66300000,"on":true,"rp":true,"as":false,"hard":false,"daysOfWeek":[true,true,true,true,true,true,true,false],"last":10}]
</code>

**Comment by bobrippling** [comment]
Looks like this was probably fixed by #1555, feel free to reopen if you see the issue
