### ISSUE TITLE
Configurable Analog Clock: Does not load

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#1418]
Hi,

I tried the Configurable Analog Clock on BangleJS2 and the screen gets stuck on "Loading...". In the Browser console I see 

> Uncaught Error: Module https://raw.githubusercontent.com/rozek/banglejs-2-simpled-clock-hands/main/ClockHands.js not found
 at line 10 col 351 in ac_ac.app.js
...k-hands/main/ClockHands.js'),complications:{tl:undefined,t:require('...

**Comment by johan-m-o** [comment]
Looks like a typo... It's supposed to be "simple" clock hands, not "simpled". @rozek

**Comment by rozek** [comment]
Thank you very much for your hints!

I've fixed the typo and changed the version number to 1.0.

A pull request is pending. After a successful merge, the new (corrected) version will be available in the official app loader - just watch for version 1.0!

**Comment by nxdefiant** [comment]
That was quick, thanks

**Comment by rozek** [comment]
well, here we say "Impossible things are done immediately, miracles take a little longer"

**Comment by rozek** [comment]
the pull request for my bug fix has just been merged
