### ISSUE TITLE
BangleJS2: Barometer does not show any value

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#1429]
The barometer just shows the background image, error in console:

> Uncaught Error: Unhandled promise rejection: Error: Cannot read property 'pressure' of undefined

Does it need a call to `Bangle.setBarometerPower(true)` first?

**Comment by HilmarSt** [comment]
also see the discussion at http://forum.espruino.com/conversations/372900

**Comment by gfwilliams** [comment]
added a workaround for now so the app works with existing firmware
