### ISSUE TITLE
Problem with "Bangle.CLOCK"

### ISSUE THREAD

**Issue by HilmarSt** [espruino/BangleApps#1437]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

In some apps / widgets <code>**Bangle.CLOCK**</code> is used to detect if a clock is running, e.g. in "Digital clock widget":
<code>if (!**Bangle.CLOCK**) WIDGETS["wdclk"]={...</code>

This seems not to work any more.

**Comment by gfwilliams** [comment]
Which clock faces have you tested on? Because I just tried here and it works fine for me.

If the clock calls  `Bangle.setUI("clock` *after* loading widgets then this will break, so that could be it?

**Comment by HilmarSt** [comment]
I'm using the Vector Clock, and you're right - Bangle.setUI("clock") was executed _after_ Bangle.loadWidgets() .
I'll create a PR to fix this.

**Comment by gfwilliams** [comment]
Great - thanks!
