### ISSUE TITLE
Deleting all clock apps prevents the start of the app menu

### ISSUE THREAD

**Issue by profriemke** [espruino/BangleApps#147]
If all existing clock apps are deleted (e.g. accidentially) the watch only shows a message that no clock app is present. The app menu is then not accessible.
Suggestion: If no clock is present, the app menu should be shown as standard.

**Comment by gfwilliams** [comment]
Thanks - that sounds like a great idea.

**Comment by brainfart-be** [comment]
Seeing the launcher directly felt weird, i decided to just add the BTN2 click to open the menu.

**Comment by MaBecker** [comment]
I suggest to start the About app.

**Comment by brainfart-be** [comment]
I personally removed it from my watch, i would end up with the same issue.
We can maybe make the smallest watch app possible with a message saying "to install a clock go to https://banglejs.com/apps#clock" or something like this.
(The #clock part is not yet live but the features was merged already)

**Comment by gfwilliams** [comment]
I think your current solution is nice and tidy for the moment. If someone doesn't have a clock it's extremely unlikely they'll have the About app I guess :)
