### ISSUE TITLE
[timerclk] Cannot remove alarm

### ISSUE THREAD

**Issue by f616** [espruino/BangleApps#1477]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

I have a persistent alarm set to everyday at 12:00:00 which cannot be removed and doesn't appear on the alarm list

**Comment by andrewgoz** [comment]
I've noticed that Timer Clock defaults to alarms being active. Try pressing the 'X' lots of times to make sure all alarms are deleted, then in the alarm that remains, press the blue button so it looks like a 'play' button (triangle). Then exit out by pressing the button - don't swipe to look at other alarms.

**Comment by f616** [comment]
That seems to "solve" the issue. Thank you

**Comment by Ronin0000** [comment]
Maybe this should be closed now that the issue is solved

**Comment by gfwilliams** [comment]
Thanks!
