### ISSUE TITLE
run 0.6 - Cadence never changes from 0

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1479]
### Affected hardware version

Bangle 2

### Your firmware version

2v12.32

### The bug

Run 0.6 setup with 
Box1 : Time, Box2: BPM, Box3:  STEPS, Box 4 Cadence.

The cadence never updated from 0 and stay at zero throughout the test walk.
Screenshot attached.
![download (2)](https://user-images.githubusercontent.com/3630481/154743851-123299c5-1b59-456f-8fc3-9c10bb38459f.png)

**Comment by copoer** [comment]
Here is a potential fix I am testing:
https://github.com/espruino/BangleApps/pull/1502

**Comment by copoer** [comment]
It seems to fix it. :+1:

**Comment by gfwilliams** [comment]
Thanks for the fix @copoer !
