### ISSUE TITLE
run 0.06 - powers on GPS when no gps derived data is displayed / configured

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#1480]
### Affected hardware version

Bangle 2

### Your firmware version

2v12.32

### The bug

Configured Run app as:
Box1 time, Box 2: BPM, Box 3: steps, Box 4: Cadence

My understanding is that none of these boxes require the GPS to be powered on
and that the GPS would not be powered on if was not needed.

A previous setting to disable the GPS was taken out as it was stated that the GPS would not be powered on if none of the boxes selected derived data from GPS fixes.

In this case I wanted to time the run, see heart rate but did not want to take the hit on the battery by turning the GPS on.

![download (2)](https://user-images.githubusercontent.com/3630481/154744564-6624062d-856c-4d92-96c2-f57be3810ceb.png)

**Comment by gfwilliams** [comment]
Fixed - was just requesting GPS when it didn't need it
