### ISSUE TITLE
Trouble setting "Year" in Settings, as the range is limited (-10  to +10)

### ISSUE THREAD

**Issue by VinceOPS** [espruino/BangleApps#15]
Hi,

First, thanks for the Bangle.js!

Is there any reason why this `min` and `max` have been set? This leads me to not being able to set a Year higher than 1980 once my watch is restored to UNIX timestamp :sweat_smile:  (01/01/1970).

https://github.com/espruino/BangleApps/blob/6d2627a2f4463f4e23c60189b65ec9faa6e151a8/apps/settings.js#L252

I'd be glad to propose a PR if it is reasonable to change it.

**Comment by shane-t** [comment]
As a workaround for now, I have found that if you set the year to max, then retreat from the menu, and then go back into it, you can keep incrementing it by 10 years (or use the GPS Time app which will set your clock without intervention)

**Comment by gfwilliams** [comment]
Hah - yeah, I can't think of a good reason for that - thanks for the spot! A PR would be great!

**Comment by VinceOPS** [comment]
@gfwilliams Hi there! Thanks for the prompt answer.
I'm a bit lost in the code right now, I'd like not to just propose a fix with some arbitrary values like `min: 1970` and `max: 3000`, but to add some tests, and understand where this `min`, `max`, `onchange` (etc) are used. Could you give me a few hints?

Thanks!

**Comment by gfwilliams** [comment]
It's using getFullYear which will be returning values like 2019 - so you'd be totally safe with the min/max you suggest.

Probably the best bet is to load `BangleApps/apps/settings.js` into the IDE, then make your changes and click 'upload' - it should temporarily run your modified settings app so you can check if things work ok?

**Comment by gfwilliams** [comment]
In terms of where they're actually used - this is the source code for the menu itself: https://github.com/espruino/EspruinoDocs/blob/master/modules/graphical_menu.js#L80
