### ISSUE TITLE
Feature Request: Barometer - Pressure change alerts

### ISSUE THREAD

**Issue by fparri** [espruino/BangleApps#1521]
Would that be possibile to add Air Pressure change alerts?

https://www.thoughtco.com/how-to-read-a-barometer-3444043

**Comment by gfwilliams** [comment]
You mean in the barometer app itself, or just as something that pops up in normal use?

It's definitely something that'd be pretty easy to do, but with it on your wrist the pressure will change a lot just due to changes in height as you walk up and down stairs, so I guess you'd have to be careful that didn't trigger anything.

**Comment by fparri** [comment]
I am testing a Huawei Watch GT Runner: it offers the possibility to enable or disable alerts for pressure drops, measuring the drop in hPA over the last 3 hours, with the following options:

2 hPa/3 h
2.5 hPa/3 h
3 hPa/3 h
3.5 hPa/3 h
4 hPa/3 h
4.5 hPa/3 h
5 hPa/3 h
5.5 hPa/3 h
6 hPa/3 h

I attach some pics

![01](https://user-images.githubusercontent.com/1544681/156017067-c10b6870-bfeb-4d81-9446-0839c0e6c03f.jpg)
![02](https://user-images.githubusercontent.com/1544681/156017071-0a8d4169-e1ad-471b-9fab-78a3adee1a57.jpg)
![03](https://user-images.githubusercontent.com/1544681/156017076-9e8fe056-6949-4cfb-a9f0-3ec344e338f2.jpg)

**Comment by gfwilliams** [comment]
Looks like a good idea - it could be handled as a widget pretty easily.

Honestly though, I've spent the entire day today *just* answering messages, so for me personally I don't have much time to implement something like this

**Comment by myxor** [comment]
I am working on a widget which implements this. Will create a merge request in the next days.

**Comment by fparri** [comment]
Just read and just seen your pull request. Looking forward to trying it! :)
Thanks a lot!

**Comment by myxor** [comment]
@fparri v0.02 is available since yesterday. Please give it a try and i am happy to receive feedback from you :)

**Comment by fparri** [comment]
> @fparri v0.02 is available since yesterday. Please give it a try and i am happy to receive feedback from you :)

Avsolutely. I'm going to update the app and try it tomorrow. Thanks a lot :))))))

**Comment by fparri** [comment]
@myxor I tried it yesterday. It worked perfectly. The only difference I noticed with the same feature on my Huawei GT Runner is that the GT Runner probably compensates pressure variation due to a change in altitude.
I got a pressure drop alert on the Bangle.JS 2 but not on the GT Runner. Not a huge deal, though. Thanks a lot again for your app :)

**Comment by myxor** [comment]
@fparri how do you think should the compensation Worky? Any ideas?

**Comment by fparri** [comment]
@myxor I am not an expert in this area, but I've found various correction tables online:

https://www.engineeringtoolbox.com/barometers-elevation-compensation-d_1812.html
https://novalynx.com/manuals/bp-elevation-correction-tables.pdf
https://airdensityonline.com/2016/11/corrected-and-uncorrected-barometer/

**Comment by myxor** [comment]
It could be that such or similar corrections are already included in the firmware of the barometer chip.
Maybe @gfwilliams can confirm this?

**Comment by thyttan** [comment]
Candidate for being closed - leave a comment if you object!

Rationale:
Done with [Barometer Alarm Widget](https://espruino.github.io/BangleApps/?q=widbaroalarm).

**Comment by gfwilliams** [comment]
Yes - looks like [Barometer Alarm Widget](https://espruino.github.io/BangleApps/?q=widbaroalarm) does this

@myxor I don't know about the corrections - you would have to look in the barometer datasheet. There is definitely *some* calculation going on at https://github.com/espruino/Espruino/blob/970089d785ed263f7f9434eba7a3fd8cb9158875/libs/banglejs/jswrap_bangle.c#L4577 though
