### ISSUE TITLE
[run] run cannot be started

### ISSUE THREAD

**Issue by bernhardreiter** [espruino/BangleApps#1561]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

Pressing the middle button does not change state from "stop" to "start" in v0.08.

### Details
* Upgraded to v0.08.
* Started gpsrec, tracking on, back
* Started run
* pressed middle button (tried pressing variations, if pressed to long the main menu loads, two short presses also do not work)
* Obeservation: "Stop" keeps being displayed. gps is green, BPM values changes. Everything else stays 0.

Expectation: Like before the middle button should start the counting (from "stop" to "start")

**Comment by gfwilliams** [comment]
Thanks - can reproduce here. Looks like it was caused by https://github.com/espruino/BangleApps/commit/2edad3887f734af66464636117ecb671e070fda7

I think if you have 'recorder' installed and enabled then it works, but otherwise it's broken. I'll get a fix in soon
