### ISSUE TITLE
Open Street Map has No Boundaries for scrolling.

### ISSUE THREAD

**Issue by Ronin0000** [espruino/BangleApps#1575]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

In open street map you can scroll off the edge of the map. It is an issue because if you scroll too far off the edge of the map you can lose where the map is and can’t get back to it.

**Comment by gfwilliams** [comment]
I think you can just press the button or tap to re-centre?

The idea was at some point you'd be able to upload more than one mapping area (which I guess could overlap) so maybe while clipping makes sense now, when that happens it may be something we don't want

**Comment by Ronin0000** [comment]
Oh, ok Thanks I did not realize you could do that!
