### ISSUE TITLE
LCARS clock the alarm can go bigger then 100

### ISSUE THREAD

**Issue by Ronin0000** [espruino/BangleApps#1576]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

In LCARS Clock the alarm can go past 100 and because my Bangle.js v2 has an issue where the screen is being touched when I am not touching it can produce a very large alarm, so that you have to tap a lot to get rid of the alarm. It would also be useful if the alarm had an option to be disabled.

**Comment by gfwilliams** [comment]
I notice you've filed 15 issues so far, and 5 in one day recently. It'd be great if you could contribute fixes for some of them because it'd be a full-time job for me to do everything you're requesting :)

**Comment by Ronin0000** [comment]
ok!
