### ISSUE TITLE
Bootloader 0.45 seems to have broken widget editor app

### ISSUE THREAD

**Issue by tompusey** [espruino/BangleApps#1590]
The widget editor changes only seem to work within the app, they revert back to defaults as soon as you leave the app.

**Comment by gfwilliams** [comment]
Can you run `Settings -> Utils -> Rewrite settings` please? It's possible you've still got some files left over from the 0v44 bootloader which we found had some issues

**Comment by tompusey** [comment]
Just tried that and it doesn't seem to change the behaviour.
