### ISSUE TITLE
Touch press/release events on BangleJs2

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#1592]
Currently I see no option to capture touch press and release events on the BangleJs2. The usual methods e.g. Bangle.on('touch'...) do only fire on release, so only short and long presses are evaluated.
E.on('touch', function(x, y, b) { ... }); which can do that according to the documentation is unsupported on the BangleJs.

**Comment by gfwilliams** [comment]
Can't you just use the 'drag' event? When the 'b' value changes that's a difference in whether the screen is touched or not

**Comment by nxdefiant** [comment]
That looks good, thanks and sorry for the noise.
