### ISSUE TITLE
Backup: Can not restore files with size=0

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#1593]
I had to restore the backup for my BangleJS1 today after a firmware update from v10 to v12 somehow made the clock unusable: The clock was still there, but I could not access the launcher any more.

So I tried to restore the backup, but at ~30% it complained about a file with zero size. In my case it was a files named hourstrike.json. I removed it from the zip file and restore worked.

**Comment by gfwilliams** [comment]
Do you have the error message that you saw?

To be honest it seems like a bit of a bug that anything is creating a 0 length file.

**Comment by nxdefiant** [comment]
I have not copied the exact error message. I just tried to create that scenario, but unfortunately I can not create a new Backup with the BangleJS1, it stops at ~95% and the watch writes "Memory" in red.
