### ISSUE TITLE
[Calendar] Dates at end of previous month off by one day

### ISSUE THREAD

**Issue by banglejsdev** [espruino/BangleApps#1602]
### Affected hardware version

Bangle 1, Bangle 2

### Your firmware version

2v12

### The bug

The days listed at the end of the previous month are off by one, as shown in the following screenshot:

![CalendarBug](https://user-images.githubusercontent.com/102075872/159363387-7f0559d5-d3e3-4df6-91c4-ea0d3f4adb31.jpg)

In case it's hard to tell, the last two days listed for the previous month (Feb.) in the first row, are 26 and 27 instead of 27 and 28. I've seen this for other months as well so don't believe it's specific to Feb. being the previous month.

Thanks for creating this app and also for adding the option to set the first day of the week to Sunday instead of Monday!

**Comment by nxdefiant** [comment]
Confirmed. lets just add 1: #1622
