### ISSUE TITLE
[Light Switch Widget] Problems with New Menu System

### ISSUE THREAD

**Issue by HilmarSt** [espruino/BangleApps#1607]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

Go to Settings -> Apps -> Light Switch

1. Issue:
Select the menu item "-- Control: Touch" and change the setting: The font is too big for the menu item and the text is not readable.

2. Issue:
Select the menu item "-- Flash: Timeout" and change the setting to a value > 10 sec. : Value is set to 0.5s

**Comment by gfwilliams** [comment]
Ok, thanks. Looks like the settings screen re-implements wrapping/min/max for some reason rather than using its own. I'll fix that now.
