### ISSUE TITLE
[Run] Error Low Memory

### ISSUE THREAD

**Issue by dapgo** [espruino/BangleApps#1608]
### Affected hardware version

Bangle 1

### Your firmware version

2v12

### The bug

UI: error LOW memory and blank screen

Console:
2v12 (c) 2021 G.Williams
Execution Interrupted
at line 2 col 2704 in run.app.js
...r.bg=parentBg==null?g.theme.bg:parein function "prepareLazyRender" called from line 2 col 2826 in run.app.js
...oClear,drawList,rects,bgCol);
                              ^
in function "prepareLazyRender" called from line 2 col 2826 in run.app.js
...oClear,drawList,rects,bgCol);
                              ^
in function "prepareLazyRender" called from line 2 col 4192 in run.app.js
...sToClear,drawList,this.rects,null);for(var h in rectsToClear)delete this.rects[h];var...
                                                       ^
in function "render" called from line 24 col 15 in run.app.js
layout.render();
              ^
Interpreter error: [
  "LOW_MEMORY",
  "MEMORY"
 ]
New interpreter error: LOW_MEMORY,MEMORY

**Comment by gfwilliams** [comment]
What apps do you have installed and what app are you running?

**Comment by dapgo** [comment]
the app is id":"run","version":"0.10",

Today after removing few apps, i was able to open Run but as soon as I click btn2-start i produces a

Execution Interrupted during event processing.
Interpreter error: [
  "MEMORY"
 ]
New interpreter error: MEMORY
ERROR: Ctrl-C while processing interval - removing it.
Execution Interrupted during event processing.
Interpreter error: [
  "CALLBACK",
  "LOW_MEMORY",
  "MEMORY"
 ]
New interpreter error: CALLBACK,LOW_MEMORY,MEMORY

and the mem status with "Run" app open 
 ={free: 294, usage: 2290, total: 2584, history: 5,
  gc: 0, gctime: 10.55908203125, blocksize: 13, stackEndAddress: 536925632, flash_start: 0,
  flash_binary_end: 459956, flash_code_start: 1610612736, flash_length: 524288 }

with "Run" app closed
={ free: 1511, usage: 1073, total: 2584, history: 20,
  gc: 0, gctime: 6.50024414062, blocksize: 13, stackEndAddress: 536925632, flash_start: 0,
  flash_binary_end: 459956, flash_code_start: 1610612736, flash_length: 524288 }

**Comment by dapgo** [comment]
[{"id":"verticalface","version":"0.09","files":"verticalface.info,verticalface.app.js,verticalface.img"},{"id":"helloworld","version":"0.02","files":"helloworld.info,helloworld.app.js,helloworld.img"},{"id":"bledetect","version":"0.03","files":"bledetect.info,bledetect.app.js,bledetect.img"},{"id":"fileman","version":"0.03","files":"fileman.info,fileman.app.js,fileman.img"},{"id":"torch","version":"0.02","files":"torch.info,torch.app.js,torch.wid.js,torch.img"},{"id":"UI4swatch","version":"0.01","files":"UI4swatch.info,UI4swatch.app.js,UI4swatch.img"},{"id":"widclkbttm","version":"0.03","files":"widclkbttm.info,widclkbttm.wid.js"},{"id":"files","version":"0.07","files":"files.info,files.app.js,files.img"},{"id":"testuserinput","version":"0.06","files":"testuserinput.info,testuserinput.app.js,testuserinput.img"},{"id":"banglerun","version":"0.10","files":"banglerun.info,banglerun.app.js,banglerun.img"},{"id":"gpsrec","version":"0.27","files":"gpsrec.info,gpsrec.app.js,gpsrec.img,gpsrec.wid.js,gpsrec.settings.js","data":"gpsrec.json;.gpsrc?"},
{"id":"thermom","version":"0.05","files":"thermom.info,thermom.app.js,thermom.img"},{"id":"widbt","version":"0.07","files":"widbt.info,widbt.wid.js"},
{"id":"notifyfs","version":"0.12","files":"notifyfs.info,notify"}
,{"id":"widclk","version":"0.06","files":"widclk.info,widclk.wid.js"},{"id":"toucher","version":"0.07","files":"toucher.info,toucher.app.js,toucher.settings.js","data":"toucher.json"},{"id":"weatherClock","version":"0.05","files":"weatherClock.info,weatherClock.app.js,weatherClock.img"},{"id":"weather","version":"0.15","files":"weather.info,weather.app.js,weather.wid.js,weather,weather.img,weather.settings.js","data":"weather.json"},
{"id":"wid_edit","version":"0.01","files":"wid_edit.info,wid_edit.boot.js,wid_edit.settings.js","data":"wid_edit.json"},{"id":"android","version":"0.07","files":"android.info,android.app.js,android.settings.js,android.img,android.boot.js","data":"android.settings.json"},
{"id":"setting","version":"0.42","files":"setting.info,setting.app.js,setting.img","data":"setting.json"},{"id":"messages","version":"0.26","files":"messages.info,messages.app.js,messages.settings.js,messages.img,messages.wid.js,messages","data":"messages.json,messages.settings.json"},{"id":"alarm","version":"0.15","files":"alarm.info,alarm.app.js,alarm.boot.js,alarm.js,alarm.img,alarm.wid.js","data":"alarm.json"},{"id":"boot","version":"0.45","files":"boot.info,.boot0,.bootcde,bootupdate.js"},{"id":"run","version":"0.10","files":"run.info,run.app.js,run.img,run.settings.js","data":"run.json"},{"id":"grocery","version":"0.02","files":"grocery.info,grocery.app.js,grocery.img,grocery_list.json"},{"id":"todolist","version":"0.01","files":"todolist.info,todolist.app.js,todolist.img","data":"todolist.json"}

**Comment by dapgo** [comment]
after removing "notifyfs" and "widbt" *, I am  able to use "Run" and it consumes around 1200 

* BTW  this battery widget  also was failing showing 0%, just after removing it shows 97%
and same with command
>E.getBattery()
=97

**Comment by gfwilliams** [comment]
Great, glad it's sorted! I'm surprised `notifyfs` used anything though. Also `widbt` is one of the defaults so shouldn't use too much.

Looking at the list, you do have widclk and widclkbttm installed - so presumably you don't need two onscreen clocks at once?

> BTW this battery widget also was failing showing 0%

I don't actually see a battery widget in that list of installed apps? Which one were you using?

If you can see easy ways to reduce memory usage in apps I'm all for PRs, but to a certain extent I'm in a lose-lose position here. Everyone wants more features, more flexibility, more apps, and nobody actually wants to spend any time making things more memory efficient because that's boring. I do my best, but I'm pretty limited with what I can do - and I don't think limiting users to installing 2 widgets at once would make anyone happy.

I **did** recently made some big changes for memory usage in Espruino, so cutting edge builds (or 2v13 when released) should be significantly better and may fix your problems.

**Comment by dapgo** [comment]
> Great, glad it's sorted! I'm surprised `notifyfs` used anything though. Also `widbt` is one of the defaults so shouldn't use too much.
> 
> Looking at the list, you do have widclk and widclkbttm installed - so presumably you don't need two onscreen clocks at once?

not really :D , probably i installed both to test something and i forgot to clean after

> > BTW this battery widget also was failing showing 0%
> 
> I don't actually see a battery widget in that list of installed apps? Which one were you using?

"id": "widbat","version": "0.09"
> If you can see easy ways to reduce memory usage in apps I'm all for PRs, but to a certain extent I'm in a lose-lose position here. Everyone wants more features, more flexibility, more apps, and nobody actually wants to spend any time making things more memory efficient because that's boring. I do my best, but I'm pretty limited with what I can do - and I don't think limiting users to installing 2 widgets at once would make anyone happy.

High spec devices usually make people forget about efficiency. :o
I would try to pay a look and see what can be optimized, because i run and  i like to have many apps installed.
> I **did** recently made some big changes for memory usage in Espruino, so cutting edge builds (or 2v13 when released) should be significantly better and may fix your problems.

cool
