### ISSUE TITLE
[1024 Game] Game Bleeds Over Reset Game Menu In You Swipe While In Menu

### ISSUE THREAD

**Issue by Ronin0000** [espruino/BangleApps#1609]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

If you click the Reset Game button and swipe while it shows you the prompt the game will bleed back over the menu.

**Comment by chiefdaft** [comment]
Hi Ronin0000,
Thanks for testing it, I was able to replicate the issue (bug). I'll see if I can fix this soon.
Cheers,
Jelco
