### ISSUE TITLE
[Close Button] Does not show on 1024 Game.

### ISSUE THREAD

**Issue by Ronin0000** [espruino/BangleApps#1615]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

The Close Button Should show on every screen that is not the clock. I am not sure why it does not show on this app only.

**Comment by gfwilliams** [comment]
The close button? You mean the newish widget that displays the close button? If apps don't display widgets then you won't see it - that could be the issue?

**Comment by Ronin0000** [comment]
Yes the close button:
![image](https://user-images.githubusercontent.com/89286474/159934619-c0da1a72-3b9e-4d68-aed6-be4c35bcf685.png)
It should show on every app that shows the widgets except the clock. Here it does not show on this game:
![image](https://user-images.githubusercontent.com/89286474/159934465-1ef16c3b-b459-4433-b8f5-97ca54aceccb.png)
But on every other app that shows widgets except clocks it does show the button:
![image](https://user-images.githubusercontent.com/89286474/159935011-5884b14f-9bcb-4861-9046-3747e583ce41.png)

**Comment by rigrig** [comment]
This happens because the game says it is a clock:
https://github.com/espruino/BangleApps/blob/0a347ee03166662d5dbed0eb3d7ba292079dd15f/apps/game1024/app.js#L479-L480

**Comment by chiefdaft** [comment]
Removing line _Bangle.setUI("clock");_ let's the close button to appear and it can close the app if you don't hit the undo button accidentally. I'll fix this issue.

**Comment by Ronin0000** [comment]
I see now, Thanks!
