### ISSUE TITLE
Running code at boot time

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#163]
Right now you have 2 options:

* Add `.boot/1/2/3` (boot0 already used) which runs ant *every boot*
* Add `myfile.wid.js` which is loaded whenever an app runs that uses widgets

But using `.bootX` can't be done for apps, because 2 apps using `.boot1` would conflict.

So maybe we should have `myfile.boot.js` which is run at startup by the bootloader?

**Comment by DerGuteWolf** [comment]
Then you could also move the alarm specific stuff from boot0 to alarm.boot.js...
