### ISSUE TITLE
alarm 0.17 does not buzz

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#1667]
BangleJS2, every app up to date according to the apploader. I have set up an alarm at 12:00 for testing with default settings.  At 12:00 nothing happened.

I would attach the alarm.json, but I can not find it in the the espruino ide->device storage, has the file been renamed?

Update: seems to be now sched.json:
```
[{"t":43200000,"on":true,"rp":false,"as":false,"dow":127,"last":0,"vibrate":".."},{"t":43200000,"on":true,"rp":true,"as":false,"dow":127,"last":0,"vibrate":"---"},{"t":25200000,"on":true,"rp":true,"as":false,"dow":127,"last":0,"vibrate":"..","day":7},{"t":36000000,"on":true,"rp":true,"as":false,"dow":127,"last":0,"vibrate":"..","day":7}]
```

Also I can no longer edit/remove the alarm at 12:00 with the alarm app. When I click on the alarm it immediately goes back to the alarm selection.

Also the update removed all my timers, I warning/migration would have been nice.

**Comment by alessandrococco** [comment]
Latest Alarm & Timer app needs the new `sched` lib: https://banglejs.com/apps/?id=sched Is it installed on your bangle? (I don't know if the app loader installs it automatically during the update)

**Comment by nxdefiant** [comment]
It is installed according to the apploader, version 0.01

**Comment by storm64** [comment]
It seems the 12:00 alarm is doubled, maybe nobody tested to alarms with the same time.

**Comment by nxdefiant** [comment]
So 43200000 shall be the 12:00 clock alarm? You sure?

boot.js:
```
    var currentTime = (time.getHours()*3600000)+(time.getMinutes()*60000)+(time.getSeconds()*1000);
```
does not look to get to 43200000 for 12:00

**Comment by storm64** [comment]
Good point, I haven't checkt it, but yes it is:
```
// time in ms -> { hrs, mins }
function decodeTime(t) {
  t = 0|t; // sanitise
  var hrs = 0|(t/3600000);
  return { hrs : hrs, mins : Math.round((t-hrs*3600000)/60000) };
}
decodeTime(43200000);
```
`={ hrs: 12, mins: 0 }`

**Comment by nxdefiant** [comment]
> Did the old alarm system work fine for you?
Yes

> I just reset my time before 12 and can reproduce, looking into this now
great, because there also is another bug:
sched/boot.js
```
    if (active[0].last == time.getDate() || t < -60000) t += 86400000;
```
Please reset active[0].last when alarm is saved, because when I create an alarm at e.g. 12:00 and later set it for 13:00 it won't strike today 13:00

**Comment by nxdefiant** [comment]
Confirmed, works better. Thanks.
