### ISSUE TITLE
[alarm] On new alarm, time is reset on dow change

### ISSUE THREAD

**Issue by storm64** [espruino/BangleApps#1676]
### Affected hardware version

Bangle 2

### Your firmware version

2v12.126

### The bug

On creating a new alarm or changing a previously created one, a changed time (Hours and/or Minutes) is reset on opening the day of week selection menu.

I usually go through and set the configs from top to bottom, when doing so I often need to set the time twice.

I would suggest to either save the time on each change or move the day of week selection menu to the top.

### Steps to reproduce:
1. Open `New Alarm >`
2. Change `Hours   12` or `Minutes   0`
3. Open `Days   SMTWTFS`
4. Go back :red_circle:

-> Time values are reset to `Hours   12` and `Minutes   0`

**Comment by alessandrococco** [comment]
Bug found! I'll send a PR later.
