### ISSUE TITLE
[run] restore ability to pause a run

### ISSUE THREAD

**Issue by bernhardreiter** [espruino/BangleApps#1712]
### Affected hardware version

Bangle 2

### Your firmware version

2v12

### The bug

Should be possible to pause  a run, which current version of run, a press of the button will stop the measurement completely.
After pressing the button again, it will ask if the old track should be overwritten (yes, no, new). No option continues the run.

Observation: in older versions of run, someone could pause a run, like when waiting before a train crossing, by pressing a button. 

Expected: There should be  a simple possibility to pause a run. A short press of the button works nicely for this in elder versions.

**Comment by Darin755** [comment]
I can confirm this. I would love to have this feature as it is the only thing preventing me from using the banglejs 2 full time.

**Comment by gfwilliams** [comment]
Just fixed
