### ISSUE TITLE
[Bug] AGPS update loading icon doesn't disappear

### ISSUE THREAD

**Issue by hasmar04** [espruino/BangleApps#1732]
When updating AGPS from the App Loader, once it is complete the upload icon continues to show the loading wheel, even though it has shown as complete in the lower banners.

**Comment by alessandrococco** [comment]
I noticed the same issue with **Languages** app also 🤔

**Comment by gfwilliams** [comment]
I imagine it's related to custom apps then... Maybe the promise doesn't complete?
