### ISSUE TITLE
[Alarms & Timers] Can't Back out of selecting weekdays

### ISSUE THREAD

**Issue by andrewgoz** [espruino/BangleApps#1735]
### Affected hardware version

Bangle 2

### Your firmware version

2v13

### The bug

When configuring Days of the Week for a new alarm, the red Back button at the top left doesn't work.

1. Open the Launcher
2. Select "Alarms"
3. Select "New Alarm"
4. Select "Days"
5. Attempt to tap the Back button

The "Alarms & Timers" app is v0.22.

**Comment by alessandrococco** [comment]
I already fix this in #1729
