### ISSUE TITLE
Quick Launch: Configuration should be under app settings

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#1760]
Currently when starting the "Quick Launch" app from #1626 from the launcher only a configuration window is seen. I would prefer this to be under Settings->Apps instead.

@frigis1 Any opinion on that? This app was a nice idea btw.

**Comment by frigis1** [comment]
Thank you kindly! Sounds good, do you think it's best to have it only under the settings menu and not in the launcher?

**Comment by nxdefiant** [comment]
I would say so, since it is a background task/widget, like e.g. hour chime. And the launcher would have one app to scroll over. Though the description should contain a sentence that the configuration is now under app settings.

**Comment by frigis1** [comment]
PR created, again thanks for the suggestion!

**Comment by nxdefiant** [comment]
wow, that was fast. thx
