### ISSUE TITLE
[New menu system] Increase the number of characters per line

### ISSUE THREAD

**Issue by alessandrococco** [espruino/BangleApps#1761]
Is it possible to increase the number of characters per line when a second line exist? Now a third row is created too early.

An image is better than a thousand words:

![image](https://user-images.githubusercontent.com/2331798/165632648-f8fcea90-f7fc-4f98-b4ad-4db497f9efd3.png)

**Comment by storm64** [comment]
Found this bug while testing your alarm-qol-dow branch, too.
It is fixed and merged already (espruino/Espruino#2182).
You just need to update to the latest [cutting edge build](https://www.espruino.com/Download#banglejs2).

**Comment by alessandrococco** [comment]
@storm64 Great, thank you!

**Comment by alessandrococco** [comment]
Just tested, it works like a charm, thanks!
