### ISSUE TITLE
Alarm: Day of week settings should not always start on sunday

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#1780]
Right now the day of week settings in the alarm app always has Sunday as first day of the week. Dependent on the locale it should switch to Monday as first day. Problem is: This seems to be not yet provided by the locale or am I missing something?

So the alternatives are:
1. Add week-starts-on-monday to locale
2. Add week-starts-on-monday to alarm settings
Any opinions on this?

**Comment by alessandrococco** [comment]
Hi @nxdefiant,

in the last days I made various changes to the alarms app and the "Week starts on Sunday" always bothered me so I started to thinking about it. This morning I made some updates to the `date_utils` module to handle the start of the week (not pushed yet) as I'd want to add this _qol_ improvement to #1773)

The module works

![image](https://user-images.githubusercontent.com/2331798/166106349-9afe011e-f1e8-445c-90ba-47a916a7546d.png)

now I need to integrate this to the alarms app (maybe tomorrow).

---

At the moment we have nothing that says "the week start on Monday/Sunday". I'd like to add a global option (maybe in `System -> Locale`?) Moreover we could include a default in each locale but the user can change it using the Settings app.

**Comment by nxdefiant** [comment]
Great, I see you got it covered. Good for us not living in USA :)

**Comment by alessandrococco** [comment]
In the sched library the days of week are stored as binary:

```
  dow : 0b1111111, // Binary encoding for days of the week to run alarm on
    //  SUN = 1
    //  MON = 2
    //  TUE = 4
    //  WED = 8
    //  THU = 16
    //  FRI = 32
    //  SAT = 64
```

Question: if the "Week starts on Monday" system setting is `true` should I consider MON = 1, TUE = 2 ... SUN = 64? Or should I keep as is?

**Comment by nxdefiant** [comment]
I would keep the API unchanged and just change it in the user interface.

**Comment by alessandrococco** [comment]
Some updates!

Improved `System / Locale` menu (renamed to `Time Options` or `Time Settings`)

![image](https://user-images.githubusercontent.com/2331798/166138511-7d2fa6b9-719e-4756-a1c0-1d576f4c315c.png) ![image](https://user-images.githubusercontent.com/2331798/166138521-d5068bee-0cb8-4870-a6fe-491ca375287a.png)

`Alarms & Timers` app:

- Start week on Monday:

![image](https://user-images.githubusercontent.com/2331798/166138560-309eadf1-5e80-4060-a260-1c256243c583.png)

- Start week on Sunday:

![image](https://user-images.githubusercontent.com/2331798/166138667-48bef098-fc70-495c-acf3-6f78536ff1ad.png)

---

There are still some bugs but I'm working on it!

**Comment by alessandrococco** [comment]
Beta versions of **Alarms & TImers** and **Settings** apps:

- https://alessandrococco.github.io/BangleApps/?id=setting
- https://alessandrococco.github.io/BangleApps/?id=alarm

**Comment by nxdefiant** [comment]
ok, will check the beta this evening.
There is another issue: In sched when showing the alarm the day of week is ignored. This can be reproduced the following way:
- Add an alarm in the future with day of week setting = not today
- Add other alarm after the first one that is enabled for today
Result: sched will show both alarms at the time of the second.

Adding a check for day of week at the bottom of sched.js should help here, e.g.
```
let active = require("sched").getActiveAlarms(alarms);
active = active.filter(alarm => alarm.dow >> (new Date()).getDay() & 1);
```

@alessandrococco Could you fix that please.

**Comment by nxdefiant** [comment]
First test feedback, tested with BangleJS1:
The settings text is too long, there is overlap between label & value.

**Comment by alessandrococco** [comment]
Thank you!

> First test feedback, tested with BangleJS1:
> The settings text is too long, there is overlap between label & value.

🤔 I could abbreviate the day to Mon/Sun. Is that enough? 

> There is another issue: In sched when showing the alarm the day of week is ignored. This can be reproduced the following way:
>- Add an alarm in the future with day of week setting = not today
>- Add other alarm after the first one that is enabled for today
>  **Result: sched will show both alarms at the time of the second.**

Sorry, I don't understand the issue (English is not my mother tongue and maybe I'm missing something 🤔)

**Comment by nxdefiant** [comment]
Mon/Sun sounds good.

I'm afraid the English problem is probably more on my site..

Lets try this again. This code in sched.js:
```
// Check for alarms
let alarms = require("sched").getAlarms();
let active = require("sched").getActiveAlarms(alarms);

if (active.length) {
  // if there's an alarm, show it
  showAlarm(active[0]);
} else {
  // otherwise just go back to default app
  setTimeout(load, 100);
}
```
does not check for the day of week. Which is why I would change:
```
diff --git a/apps/sched/sched.js b/apps/sched/sched.js
index 7c97600d..1d76df6e 100644
--- a/apps/sched/sched.js
+++ b/apps/sched/sched.js
@@ -69,6 +69,8 @@ function showAlarm(alarm) {
 // Check for alarms
 let alarms = require("sched").getAlarms();
 let active = require("sched").getActiveAlarms(alarms);
+active = active.filter(alarm => alarm.dow >> (new Date()).getDay() & 1); // check valid day of week
+
 if (active.length) {
   // if there's an alarm, show it
   showAlarm(active[0]);
```

**Comment by alessandrococco** [comment]
I added some logs at the end of the sched.js to better understand the issue, now it's clearer but I'm not 100% sure about your fix.

Examples:

Alarm 23:10, SMTWTFS, REPEAT YES --> This will fire (Correct)
Alarm 23:10, S_TWTFS, REPEAT YES --> This will NOT fire (Correct)
Alarm 23:10, S_TWTFS, REPEAT **NO** --> This will NOT fire --> Not sure if this is correct: with repeat NO the alarms should fire one time only, regardless of the day of the week (this is the reason I show "Repeat Once" instead of "Repeat S_T..." when repeat is No

**Comment by nxdefiant** [comment]
Your second test case does fire for me when there is a later one that should fire:

1. Alarm 23:10, S_TWTFS, REPEAT YES
2. Alarm 23:11, SMTWTFS, REPEAT YES

=> You will see two alerts at 23:11
