### ISSUE TITLE
[sleepphasealarm] Unable to download data with v0.05

### ISSUE THREAD

**Issue by leinad9905** [espruino/BangleApps#1789]
### Affected hardware version

Bangle 1

### Your firmware version

2v13

### The bug

I have a bangle.js v1 watch. Could you let me know if this works only on v2 or it is another issue? The app works as expected but I'm unable to download or view the data.

**Comment by nxdefiant** [comment]
I have not tested that with the Bangle 1, but it should work as with the Bangle 2. Anyway I will do the test with the Bangle 1 later.

In the meantime can you please go to the [IDE](https://www.espruino.com/ide/), open the device storage, download sleepphasealarm.json and attach it here?

**Comment by nxdefiant** [comment]
And btw, what do you mean with download? The only currently available option is to select the day of wakeup and plot the corresponding data, there is no option do download the data you see in the plot as e.g. csv yet.

**Comment by storm64** [comment]
The sleepphasealarm does not support any logging of data. You might get confused with the sleeplog app, that is available on the Bangle.js 2.

**Comment by nxdefiant** [comment]
@leinad9905 Is this still an issue or can this be closed?

**Comment by thyttan** [comment]
Candidate for being closed - leave a comment if you object!

Rationale:
>@leinad9905 Is this still an issue or can this be closed?
