### ISSUE TITLE
[app/android] request/idea: http feature

### ISSUE THREAD

**Issue by Rarder44** [espruino/BangleApps#1807]
### Affected hardware version

Bangle 2

### Your firmware version

2v13

### The bug

I open this issue to talk about the http implementation. 
(I don't know if for this discussion it is better to write on the forum or here)
I'm trying to make an app that uses the "http" feature introduced in the custom version of gadgetbridge.
I found a small problem: using the current code there is no way to go back, having the answer, to the request.

I made a small implementation where each request is associated with an ID (random / pseudorandom) which is passed to gadgetbridge; when the app has the answer, it forwards it to the smartwatch with the ID as well.
The snippet works with Promise to reduce an http request to something like this:

`http (url) .then ((result) => {
      var data = JSON.parse (result.resp);
      // TODO: ...
}). catch (function (err) {
     console.log ("Promise Rejected -" + err);
});`

If you like the implementation, I commit the changes for both gadgetbridge and android.
(maybe we need to look at the performance but I don't think it uses a lot of ram)

**Comment by Rarder44** [comment]
exactly.
  i think it's better to use a multi-concurrent approach if you want to implement the "http ()" function in the android app boot so that you can use it in any app.
thinking of a single request, it should be foreseen that there can still be two requests at the same time and should put them in a queue ... at this point it is better to make a queue of pending requests in order to take advantage of the parallel downloads from the android app

**Comment by gfwilliams** [comment]
This is done now - multiple requests work concurrently
