### ISSUE TITLE
Settings: widgets

### ISSUE THREAD

**Issue by rigrig** [espruino/BangleApps#182]
I was thinking that maybe it would be nice if we could add widget settings to the settings app, instead of having separate "apps" just to configure a widget?

Something like
* A widget can set `WIDGETS["mywidget"].settings` to a function to handle settings
* The settings app gets a new submenu "Widgets", containing (only) all widgets that have a `settings` property
* Ideally widgets also set `name`, which is used as menu entry
    - If not set, fall back to the `WIDGETS` key? So it would just show as "mywidget"
    - Or should `.settings` contain both a name and a callback?
    - Maybe we could get the name from `apps.json`? Seems like not all widgets use their  `id` as `WIDGETS` key though

So you'd have something like this:
```js
  function settings(back) {
    const mySettingsMenu = {
        '': { 'title': 'My Widget' },
        'Sound': {
            value: false,
            onchange: s => {s ? Bangle.beep() : false} // TODO: save new value
        },
        '< Back': back // provided by caller (settings app)
    };
    E.showMenu(mySettingsMenu)
  }
  WIDGETS["mywidget"]={
    /* other properties go here */
    name:"My widget",
    settings:settings,
  };
```

**Comment by gfwilliams** [comment]
That sounds like a good idea. Maybe this could be more general though?

For instance if there was an `app.settings.json` it could be shown and loaded up. It's not just widgets that could benefit from this.

In terms of implementation there's `appname.info` that's auto-generated by the app loader, so we could add an entry in there if a settings file exists on upload.

**Comment by rigrig** [comment]
That does seem a better solution, I'll give implementing something like that a try.

**Comment by gfwilliams** [comment]
Nice - thanks! For detecting settings and setting the relevant bit in the app.info, just copy/paste this:

https://github.com/espruino/BangleApps/blob/master/js/appinfo.js#L61,L62

Then finding a list of apps with settings would look a lot like:

```
var apps = s.list(/\.info$/).map(app=>s.readJSON(app,1)).filter(app=>app&&app.settings);
```
