### ISSUE TITLE
[Settings App] Syntax Error

### ISSUE THREAD

**Issue by d3nd3** [espruino/BangleApps#1883]
https://github.com/espruino/BangleApps/blob/a32233948271912f7d73ee9f6a429fe6bc8d288c/apps/setting/settings.js#L550

I can't see the `turn off` option in settings app. I looked here, it seems the syntax might be incorrect? They are separated by commas, even though its not an object {} like.  Or the issue is somewhere else? Not sure.

Or if that is valid syntax, the turn off should be for Bangle 1 too.

**Comment by d3nd3** [comment]
I think the commas "," should be replaced with ";".

**Comment by gfwilliams** [comment]
Argh, thanks! I'll get this fixed now.

Kind of hoped that the lint would have picked that up!

**Comment by gfwilliams** [comment]
fixed with https://github.com/espruino/BangleApps/commit/6b8cf13f6c635efc1392c82c8a95f2927ba65e4f
