### ISSUE TITLE
[run] Actual pause button?

### ISSUE THREAD

**Issue by Darin755** [espruino/BangleApps#1907]
It would be nice to be able to pause my run. I can stop it and then start it with the append option but that starts the distance tracker from 0. It would be nice to have a simple way of pausing it temporarily and then resuming it without hassle.

**Comment by pavelmachek** [comment]
Yes, pause button would be nice. I guess it is more important when user is walking than when running. Battery does not last for all-day trip and pause could help.

**Comment by gfwilliams** [comment]
Thanks - I guess once stopped, if the button is pressed again it could ask you if you want to resume or start a new run?

**Comment by Darin755** [comment]
Now that I've had this watch a while I have gotten used to stopping and starting my runs. I just use the append button in order to combine them
