### ISSUE TITLE
[FEATURE REQUEST] Allow distance to stay in meters/kilometers and not switch to miles after 1000m

### ISSUE THREAD

**Issue by KeFF98** [espruino/BangleApps#1933]
### Affected hardware version

Bangle 1

### Your firmware version

2v13

### The bug

The distance automatically switch to miles after reaching 1000 meters, i'd like the option for it to stay in meters/kilometers.

**Comment by gfwilliams** [comment]
This is identical to https://github.com/espruino/Espruino/issues/2209 - which got fixed yesterday. If you use cutting edge builds it's fine.

**Or** even with the current builds if you just install the `Languages` app it'll fix it
