### ISSUE TITLE
[Gadgetbridge] Notifications cause blank screen

### ISSUE THREAD

**Issue by TheLastProject** [espruino/BangleApps#1941]
### Affected hardware version

Bangle 2

### Your firmware version

2v14

### The bug

Notifications just show a pure white screen with no content whatsoever.

This happens both upon receiving a notification through Gadgetbridge (0.67.1) or when manually viewing it by going to Menu -> Messages or clicking the widget in the top-left.

Gadgetbridge Debug gives the following output:
```
{
  "t": "notify",
  "id": 1654853728",
  "subject": "Test",
  "body": "Test",
  "sender": "Test",
  "tel": "Test"
}
```

Installed apps:
About (v0.12)
Lock Widget (v0.06)
Bluetooth Widget (v0.08)
Messages (v0.39)
Android Integration (v0.10)
Weather (v0.15)
Health Tracking (v0.15)
My Location (v0.07)
Circles clock (v0.12)
Bootloader (v0.48)
Launcher (v0.13)
Alarms & Timers (v0.31)
Settings (v0.48)
Scheduler (v0.12)
Alarm & Timer ETA (v0.01)
Battery Level Widget (with percentage) (v0.16)
Gadgetbridge Music Controls (v0.10)
Gadgetbridge Debug (v0.01)
App Manager (v0.07)

**Comment by holycow234234** [comment]
It might be something in 0.39? I reverted locally to 0.38 and it seems to be working again

**Comment by DZPM** [comment]
Had the same issue. Uninstalled & reinstalled some apps, and it's working again.

I'm suspicious of the messages apps:
- https://github.com/espruino/BangleApps/tree/master/apps/messages
- https://github.com/espruino/BangleApps/tree/master/apps/android
- https://github.com/espruino/BangleApps/tree/master/apps/messagesmusic
- https://github.com/espruino/BangleApps/tree/master/apps/gbmusic

**Comment by gfwilliams** [comment]
I think an uninstall and reinstall might fix it. I believe it was an issue with the Layout library which was fixed last week (which didn't involve a version bump in anything).

Can you let me know if it doesn't? But I think this is fixed now.

**Comment by TheLastProject** [comment]
Yup, uninstalling and then installing Messages fixed it. Thanks!
