### ISSUE TITLE
[Bluetooth Widget with notification] FEATURE Request

### ISSUE THREAD

**Issue by andiohn** [espruino/BangleApps#1971]
### Affected hardware version

Bangle 2

### Your firmware version

2v14

### The bug

Simply, it would be nice to be able to have no icon when connected and red bluetooth when disconnected. I don't need to know when there isn't a problem, just when there is. :)

**Comment by gfwilliams** [comment]
Do you care about the notifications? Why not just make a new Bluetooth widget based on the original simple widget, but with the logic you describe. It'd only take a minute :)

**Comment by pebl-hank** [comment]
https://github.com/espruino/BangleApps/pull/2011 introduces Settings for the plugin. It should be no big deal to add this feature in future versions using the configuration.

**Comment by pebl-hank** [comment]
Added this to the PR.

**Comment by gfwilliams** [comment]
Closed with https://github.com/espruino/BangleApps/pull/2134
