### ISSUE TITLE
[sleeplog] data is one hour too early

### ISSUE THREAD

**Issue by jdekarske** [espruino/BangleApps#2034]
### Affected hardware version

Bangle 2

### Your firmware version

2v14

### The bug

The output graph shown is shifted one hour from what actually happened.
![download](https://user-images.githubusercontent.com/20480052/178074817-3cdbcf82-5705-492d-878f-ac9d0c361689.png)
This night I was actually asleep from ~22:40 to ~07:50. My clock time is correct and automatically updated from GadgetBridge.

It is currently 14:53, but the watch shows this:
![download (1)](https://user-images.githubusercontent.com/20480052/178075137-294a2ab7-3c53-483e-b703-e507fe8cc9fc.png)

@storm64

**Comment by jdekarske** [comment]
Thanks for the note. I might try and tackle it in the coming weeks then.

**Comment by storm64** [comment]
Hi @jdekarske,
I did a rework of the app quiet a while ago. If you didn't mind testing it look at this post:
[https://github.com/espruino/BangleApps/issues/1517#issuecomment-1133193558](https://github.com/espruino/BangleApps/issues/1517#issuecomment-1133193558)

**Comment by jdekarske** [comment]
Your version works, thanks! Is there anything holding you back from pushing upstream?

**Comment by gfwilliams** [comment]
Let's leave this open until https://github.com/espruino/BangleApps/issues/1517#issuecomment-1133193558 gets merged?

**Comment by jdekarske** [comment]
thanks @storm64 :)
