### ISSUE TITLE
[Website]: Unable to upload `settings` with nn_NO as locale

### ISSUE THREAD

**Issue by zerodogg** [espruino/BangleApps#2060]
### Affected hardware version

Bangle 2

### Your firmware version

2v14

### The bug

When uploading the settings app with nn_NO as the selected locale in the webapp under "More", the process crashes with `[error] Upload failed, TypeError: Cannot read properties of null (reading '2')`.

**Comment by gfwilliams** [comment]
Thanks! Just fixed I think - by the look of it this would have broken setting upload for anything

**Comment by gfwilliams** [comment]
(fixed in development app loader)
