### ISSUE TITLE
[run application] question, bug?

### ISSUE THREAD

**Issue by pglez82** [espruino/BangleApps#2075]
Hi.
Yesterday I tried the run application in my banglejs1. The application looks very nice and after fixing the position and pressing BTN2, it started recording my running session. The issue is that the interface gets frozen while recording, not updating the time, pace or heartbeat rate. Only when I stop recording by pressing BTN2 again I can see some data about the session.

Is this behaviour expected?

Device: Banglejs 1
Firmware version: 2v12
App version: v0.14

Regards,
Pablo

**Comment by gfwilliams** [comment]
> Firmware version: 2v12

Please can you update your firmware and report back? This is extremely likely to be your problem (that the run app relies on some features that were introduced in 2v13/2v14 firmwares)

**Comment by pglez82** [comment]
I have updated to 2v15 and the application is running fine. I can close this.
Thanks.
