### ISSUE TITLE
Way Pointer update failed, Error: Dependency of 'waypoints' listed, but nothing satisfies it!

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#2077]
The error "Way Pointer update failed, Error: Dependency of 'waypoints' listed, but nothing satisfies it!" appears when updating "Way Pointer" for Bangle JS1. Is there a reason why [waypoints](https://github.com/espruino/BangleApps/tree/master/apps/waypoints/metadata.json) was made only compatible with Bangle Js 2?

**Comment by gfwilliams** [comment]
Thanks! Sorry about that - it should work fine on Bangle.js 1 as well, it was just a mistake. just fixed
