### ISSUE TITLE
[widram - Ram Widget] TypeError in debug-log when opening Settings

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2123]
@HilmarSt @adamschmalhofer 

### Affected hardware version

Bangle 2

### Your firmware version

2v15.14 (Had the error message on 2v15 as well)

### The bug

Description:
When Ram Widget is installed and I open the Settings app I get debug-message "TypeError: TypeError: Assignment to a constant". Also, the widget is not shown when the Settings app is launched.

Expected behaviour:
To not get the error message and for the widget to be shown when the Settings app is launched. The widget doesn't even have a settings page, so it seems weird the error message should appear under these circumstances.

Steps to reproduce:
1. Have a launcher, Ram Widget and Settings app installed.
2. Display debug info somehow, via Web IDE or on the Bangle itself.
3. Open Settings app and the error message shows and the widget disappears.

**Comment by gfwilliams** [comment]
Thanks! Just fixed - not sure how that happened but it was creating a global variable called BANGLEJS2!
