### ISSUE TITLE
[app/openstmap] Does not work through GadgetBridge

### ISSUE THREAD

**Issue by ggodlewski** [espruino/BangleApps#2136]
### Affected hardware version

Bangle 2

### Your firmware version

2v15

### Describe the bug

When trying to use osm maps app from GadgetBridge 0.70.0-banglejs the tiles are not loaded. See below image (remote devtools connected to webview):

![Screenshot at 2022-09-22 19-31-30](https://user-images.githubusercontent.com/818238/191813823-a1981b37-c815-483f-b237-ab229aa172c1.png)

Remote web tools show: `custom.html:275 Mixed Content: The page at 'https://banglejs.com/apps/android.html?q=map' was loaded over HTTPS, but requested an insecure image 'http://a.tile.openstreetmap.org/0/0/0.png'. This request has been blocked; the content must be served over HTTPS.`

### Expected behavior

Be able to upload tiles to bangle from android

### Steps

* Connect Bangle to GadgetBridge
* Go to apps manager
* Go to openstmap

**Comment by gfwilliams** [comment]
Thanks! That debug info really helps!

It looks like openstreetmap works fine over HTTPS so I've just swapped map tiles over to using that, so it should be fine now I hope
