### ISSUE TITLE
[App Loader] Will install Dragboard on textinput dependency when other keyboard is already installed

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2167]
### Affected hardware version

Bangle 2

### Your firmware version

2v15.29 (had this on previous fw versions as well)

### The bug

Often when I install an app with a dependency on the type 'textinput' the keyboard 'Dragboard' is installed as well, regardless of if a keyboard is already installed or not.

If any other keyboard with type 'textinput' specified in its metadata is already installed on the watch Dragboard should not be installed when 'textinput'-type is a dependency.

To reproduce:
1. Install Multitap Keyboard.
2. Disconnect and reconnect the Bangle to the App loader.
3. Install an app with 'textinput'-type dependency, e.g. 'Noteify'. (Scheduler is also installed even if it is already installed when installing Noteify  - so this seems like a general problem with dependencies)

**Comment by thyttan** [comment]
One solution to this could be to add ```"noOverwrite":true``` to the lib.js files entry in metadata.json.  I think this would mean an installed keyboard would not be overwritten in the described scenario.

Keyboards have also been discussed in issue #1682.

**Comment by gfwilliams** [comment]
Thanks - I'll look into this. There is code to handle this at:

https://github.com/espruino/EspruinoAppLoaderCore/blob/6857957f5aedfd9d175ecbf8e49d08bb167b8128/js/index.js#L651

So either it's broken or being called before existing apps get loaded
