### ISSUE TITLE
[App Loader] Feature suggestion: Add app id's to apps tags automatically

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2172]
Sometimes I will try to search for the app id instead of its name on the App Loader which often returns no result. It would be neat if searching for an app id would show the corresponding app entry on the App Loader.

EDIT: Maybe add the short name (converted to lower case) to tags as well.

**Comment by gfwilliams** [comment]
Yes, that's a good idea. It always used to do this, and at some point search got tweaked and it stopped

**Comment by gfwilliams** [comment]
Ok, should be fixed with https://github.com/espruino/EspruinoAppLoaderCore/compare/be7115722d8e85d1a890585d2812d5ff6079762c...371fa63ae0cd69d5be52a4189400190e86491651#diff-3f689a613b62130589affae189bdfbcff8533286dcf50c288ccf61bd9b59c11c 

search should be WAY better now

**Comment by thyttan** [comment]
Very nice, thanks!
