### ISSUE TITLE
[apploader] [feature request] - free/used memory

### ISSUE THREAD

**Issue by dapgo** [espruino/BangleApps#2195]
### Affected hardware version

Bangle 1, Bangle 2

### Your firmware version

2v15

### The bug

Scenario:
From the AppLoader (webpage or Gadgbetbridge) it is not possible to know the amount used/free storage memory, and I consider this info important and useful for end users.

Expected:
In the" More" page and under "Device info" section, status about memory can be shown.In 

Workaround: 
Open web IDE and execute _require("Storage").getStats()_

**Comment by gfwilliams** [comment]
I'd be happy to merge a PR that added that functionality... I guess you could do a percent bar with `used+trash+free` shown
