### ISSUE TITLE
Convert apps to use `require("widget_utils").hide()/show()` rather than duplicating code

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#2196]
Currently every app that wants to hide widgets does so with its own code. I just added a library and it'd be nice to change apps to use this.

Apps that look like they need changes right now are:

- [x] apps/lcars/lcars.app.js
- [x] apps/advcasio/app.js
- [x] apps/neonx/neonx.app.js
- [x] apps/pebbled/pebbled.app.js
- [x] apps/notanalog/notanalog.app.js
- [x] apps/aiclock/aiclock.app.js
- [x] apps/macwatch2/app.js
- [x] apps/limelight/limelight.app.js
- [x] apps/cassioWatch/app.js
- [x] apps/daisy/app.js
- [x] apps/pebble/pebble.app.js
- [x] apps/thering/app.js
- [x] apps/rebble/rebble.app.js
- [x] apps/imageclock/app.js
- [x] apps/widviz/widget.js
- [x] apps/bwclk/app.js
- [x] apps/circlesclock/app.js (still includes fallback code)
- [x] apps/90sclk/app.js
- [x] apps/widviztime/widget.js ?

**Comment by Darin755** [comment]
Did you mean convert?

**Comment by myxor** [comment]
Circlesclock is done with https://github.com/espruino/BangleApps/pull/2202

**Comment by gfwilliams** [comment]
Just to add - for anyone else looking at this, widget_utils now contains `slideOn` which allows the widgets to be slid onto the screen with a downwards swipe

**Comment by thyttan** [comment]
#2342 for aiclock

**Comment by Rarder44** [comment]
#2227 for rebble

**Comment by thyttan** [comment]
Maybe this can be closed since #2492 was merged?

**Comment by gfwilliams** [comment]
Yes,great - thanks!
