### ISSUE TITLE
QuickLaunch 0.03: up/down swipe inverted

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#2207]
An up-swipe  (lower to upper) now calls the "down"-app and vice versa. Looks like [ud is wrong in boot.js](https://github.com/espruino/BangleApps/blob/master/apps/quicklaunch/boot.js#L26)

According to the [documentation](http://www.espruino.com/Reference#t_l_Bangle_swipe) -1 is up and 1 is down.

Notify @halemmerich

**Comment by halemmerich** [comment]
Thanks, good catch. I have now fixed this within https://github.com/espruino/BangleApps/pull/2208 .

**Comment by nxdefiant** [comment]
thx
