### ISSUE TITLE
[App Loader] Sorting by favourited not an ordered descent

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2229]
### Affected hardware version

N/A

### Your firmware version

N/A

### The bug

If I sort by favourited on the app loader there will not be a ordered descent from highest to lowest number in the hearts.

I expect the number in the heart to represent how many bangle's have favourited the app, and for the order to go from most to least favourited.

1. Go to banglejs.com/apps.
2. Sort by: 'Favourited'.
3. Scroll through the apps and observe.

Screenshot showing the bug:
![Screenshot from 2022-11-04 20-46-07](https://user-images.githubusercontent.com/97237430/200064443-c427dda3-6dbb-4a02-900e-7190ce6a029e.png)
_'iOS Integration' has no number in the heart while the apps around it does. 'Alarms and Timers' has a higher number than 'Languages' but is sorted after it._

**Comment by gfwilliams** [comment]
Thanks - yes, it seems it didn't do a compare properly when there was no data for one of the apps
