### ISSUE TITLE
Issue drawing when lcdMode is set to 80x80 or 120x120

### ISSUE THREAD

**Issue by brainfart-be** [espruino/BangleApps#223]
I wanted to test different mode for the display. 
I don't manage to make this code draw a white square (either in emulator and on the device)
or even clear the screen
when the "Bangle.setLCDMode()" is commented, it work like expected.

```
// Initialise display
Bangle.setLCDMode("120x120");

// Store screen dimensions
let W = g.getWidth();
let H = g.getHeight();

function draw(){
g.clear();
  console.log(W, H);
  g.setColor(1,1,1);
  g.fillRect(10,10, 110,110);
}

setInterval(draw, 500);

```

Maybe i'm doing something wrong

**Comment by paulcockrell** [comment]
Do you need to add `g.flip()` to invoke the draw

**Comment by brainfart-be** [comment]
Ooooh thank's !
I saw that g.flip function in a lot of code i read but didn't imagine that could be it (time to check the doc to understand what's happening behind!
