### ISSUE TITLE
[Swipe menus] Not working on newer firmwares

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2230]
### Affected hardware version

Bangle 2

### Your firmware version

2v15.90

### The bug

'[Swipe menus](https://banglejs.com/apps/?q=swscroll)' stopped working on newer firmwares. 

I will look at this and try to fix it sooner or later. I'll comment here when I begin. If someone else wants to look at this before I get to it please go ahead! :)

**Comment by thyttan** [comment]
After some testing I found it was the custom bootloader I had installed that caused the bug. Using the Bootloader 0.52 from the official app loader solves the problem.

**Comment by gfwilliams** [comment]
I think also the swipe menus were updated on friday so maybe you just didn't have those

**Comment by thyttan** [comment]
> I think also the swipe menus were updated on friday so maybe you just didn't have those

Hmm, I don't think so. There's only the 0.01 version on the development app loader, which I committed September 22.
