### ISSUE TITLE
[Swipe to clock] Doesn't work if 'fast switching' apps

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2262]
### Affected hardware version

Bangle 2

### Your firmware version

2v15.136

### The bug

The method swp2clk uses to decide if it should be active or not does not seem to work when fast switching ( Bangle.load() ) to the app where it's told to be active.

@crazysaem

**Comment by halemmerich** [comment]
Good find, since fast loading does not need to call `load` wrapping only the `load` is not enough. This is not new, since loading other apps with `eval(s.read("app.js"))` has the same problem.
I have done pull request #2264 fixing this for the newer firmwares.

**Comment by thyttan** [comment]
This is fixed with #2264 merged.
