### ISSUE TITLE
[Light Switch Widget] Feature request: Save brightness to setting.json

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2268]
@storm64

I'd like it if Light Switch Widget updated the global brightness setting when releasing from sliding to change the brightness level. Maybe it would be best to add it as an option.

I tried implementing this, but it was harder than I expected.

This is what I tried to add at a couple of places:
```
        let storage = require("Storage");
        let settingJs = storage.readJSON("setting.js");
        settingJs.brightness = value;
        print(settingJs.brightness); // to see if the code executes
        storage.writeJSON("setting.js",settingJs);
```

**Comment by storm64** [comment]
If I remember correctly the boot code is rewritten when a change in the settings.js is recognized. And to prevent this to happen quite frequently, I chose to use a separate position to store the brightness value.

**Comment by thyttan** [comment]
Ah, I see. That makes sense. I'll close this as not planned.
