### ISSUE TITLE
Quick Launch v0.06 fails to start any app

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#2286]
On With firmware 2v15.93 Quick Launch fails to start any app on swipe, in the console i get:

> Uncaught Error: Function "load" not found!
 at line 17 col 865 in .boot0
...rc))reset("upapp");else Bangle.load(settings.upapp.src);}if(ud==1&&...
                                     ^
in function called from system

Bootloader is v0.53.

**Comment by nxdefiant** [comment]
I'll try a firmware update in the evenning.

**Comment by halemmerich** [comment]
See #2287

**Comment by gfwilliams** [comment]
as in https://github.com/espruino/BangleApps/issues/2287 -please can you confirm your current bootloader version, and try again after updating?

**Comment by nxdefiant** [comment]
Lets continue in #2287 as it seems to be the same issue.
