### ISSUE TITLE
Special Chars for   "id": "aclock"

### ISSUE THREAD

**Issue by MaBecker** [espruino/BangleApps#23]
just stumbled over special chars in the app name aclock.

>require('Storage').list()
=[
  ".bootcde",
  "+aclo\xEB\xEF%",       <---- guess some hidden chars in app.json
  "-aclock",
  "*aclock",
  "+sbat",  ...
  "+setting",
  "-setting",
  "=setting",
  "@setting",
  "*setting"
 ]

**Comment by MaBecker** [comment]
Some more Infos:

* loaded Bootloader, than Settings and than AnalogClock 
* After resetting without loading any code and reloading the list looks correct.
* Display show "No Clock found" and menu entry has a "   Dead aclock" entry.

**Comment by gfwilliams** [comment]
Have you tried reloading? I just looked in apps.json and there is nothing wrong there, so it could be there's some strange glitch. Could actually be because you've installed a new firmware over an old one. I'd be interested to see whether this ever happens again after a Storage.eraseAll

**Comment by MaBecker** [comment]
Thanks, yes might be just did a extra eraseAll with  Banglejs.com - About - Remove all Apps.

>require('Storage').list()
=[  ]

so lets close it and reopen if it happens again
