### ISSUE TITLE
[Alarms & Timers] Process of creating a new alarm/timer is confusing

### ISSUE THREAD

**Issue by dustin-richards-was-here** [espruino/BangleApps#2300]
### Affected hardware version

Bangle 2

### Your firmware version

2v15

### Describe the bug
Not a bug so much as a feature suggestion. It order to create an new alarm/timer, you must set up the alarm/timer with the menu, then *press the side button*. There isn't a note of this anywhere in the app. Ideally, this process would be a bit more intuitive so that someone who has never used the app before doesn't struggle to start an alarm/timer. Note that I'm not suggesting that the side button behavior be changed, just that an additional menu item be added that's a bit more obvious and does the same thing as pressing the side button in the menu.

### Expected behavior
The first time I used the app, I expected there to be a button at the bottom of the menu labelled "Confirm", "Create", or something along those lines.

### Steps to reproduce
1. Open Alarms & Timers
2. Choose `New...`
3. Choose `Alarm` or `Timer`
4. Panic because you can't figure out how to confirm your selections
5. Press the side button
6. Realize that's how you confirm and be confused
7. Create this issue

**Comment by gfwilliams** [comment]
Ahh - thanks! Yes, you can actually go back by tapping the red arrow in the top-left as well.

But yes, adding something like 'confirm' makes a lot of sense!
