### ISSUE TITLE
[slopeclock] Doesn't respect time locale

### ISSUE THREAD

**Issue by dustin-richards-was-here** [espruino/BangleApps#2317]
### Affected hardware version

Bangle 2

### Your firmware version

2v15

### Describe the bug
Despite having the locale set to 12-hour time, slopeclock shows 24-hour time.

### Steps to reproduce
1. Set locale to 12-hour time
2. Wait for it to be after noon
3. Clock shows 24-hour time

### Expected behavior
Clock should respect the locale setting and show 12-hour time.

**Comment by gfwilliams** [comment]
Thanks - looks like @eyecreate fixed this now

**Comment by dustin-richards-was-here** [comment]
Perfect! Looking forward to updating - hours over 12 confuse my American brain.
