### ISSUE TITLE
[Messages Music] Can't install/update

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2321]
@rigrig

### Affected hardware version

Bangle 2

### Your firmware version

2v16.11

### The bug

Can't install Messages Music v0.03, error message:

>Device connection failed, Error: Dependency of 'messagelib' listed, but nothing satisfies it!

I think there is a confusion of 'messageslib' and 'messages' maybe? The former of the two doesn't seem to exist, and the name is still messages for the library. I think?

Reproduce:
1. Connect to the development app loader
2. Try installing or updating 
3. Get the error message quoted above.

'messageslib' is also mentioned in the [README.md for Messages](https://github.com/espruino/BangleApps/blob/master/apps/messages/README.md):

>`require("messages")` (provided by `messagelib`) calls `Bangle.emit("message", "text", {/** the message */})`

**Comment by rigrig** [comment]
> I think there is a confusion of 'messageslib' and 'messages' maybe?

That's it, thanks for pinging me!
