### ISSUE TITLE
Add 'Update All' button, and show how many apps can be updated

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#237]
As the title. It'd be nice to be able to just click once and update everything

**Comment by Purple-Tentacle** [comment]
But, this should not include unknown apps (apps installed by another app loader).
No idea what happens when you update them though.

**Comment by gfwilliams** [comment]
> this should not include unknown apps

It won't. You only get an option to update when apps are known, because that's when it knows there is a new version?
