### ISSUE TITLE
[slopeclock++] Uncaught Error: Font bitmap must be a String

### ISSUE THREAD

**Issue by myxor** [espruino/BangleApps#2394]
### Affected hardware version

Bangle 2

### Your firmware version

2v16

### The bug

I do not have time right now to work on this therefore i just drop the error which i sometimes see here:

```
Uncaught Error: Font bitmap must be a String
 at line 2 col 3710 in slopeclockpp.app.js
...HQ=="),100+(scale<<8)+(1<<16));return this;
                                         ^
in function called from line 2 col 5202 in slopeclockpp.app.js
...n(1,0).setFont("PaytoneOne");g2.setColor(1).drawString(minSt...
                              ^
at line 2 col 5202 in slopeclockpp.app.js
...n(1,0).setFont("PaytoneOne");g2.setColor(1).drawString(minSt...
                              ^
in function "draw" called from line 2 col 5463 in slopeclockpp.app.js
draw();
     ^
in function "callback" called from line 2 col 6242 in slopeclockpp.app.js
...raw();}if(callback)callback();}
                               ^
in function called from system
>
```

**Comment by gfwilliams** [comment]
Any hints on reproducing this? Or it just happens occasionally?

All I can think is maybe there's a memory leak, or for some reason memory gets fragmented and it can't allocate the string (but that *shouldn't* be an issue here as it should work even with a fragmented string)

**Comment by myxor** [comment]
It happens from time to time when the watch is idle (e.g. lying on the desk).
Then the clock crashes it is drawn just partly (just the hours and the minutes are missing) and it is no longer updated until reset with the button.

**Comment by gfwilliams** [comment]
Looks like it was the `E.toString` in the font that did it. We might have to watch out for that - very occasionally memory would get fragmented enough that it couldn't allocate a flat string, then the command would fail.

Should be fixed now
