### ISSUE TITLE
ios app integration causes memory overload (0.11 ios integration, 0.58 UI)

### ISSUE THREAD

**Issue by hudmarc** [espruino/BangleApps#2402]
Every day or so my watch will crash and show a `New interpreter error: LOW_MEMORY,MEMORY` error in red text on the bottom of the screen, followed by all watch functions failing until I restart the watch. I've tracked it down to the iOS integration, because when I do a memory dump from the watch most of it is this message:
```
Bangle.ancsMessageQueue = [ 
  { 
    "event": "add", 
    "uid": 18, "category": 0, "categoryCnt": 18, "silent": true, "important": false, 
    "preExisting": true, "positive": false, "negative": true }, 
  { 
    "event": "add", 
    "uid": 19, "category": 0, "categoryCnt": 19, "silent": true, "important": false, 
    "preExisting": true, "positive": false, "negative": true }, 
  { 
    "event": "add", 
    "uid": 20, "category": 0, "categoryCnt": 20, "silent": true, "important": false, 
    "preExisting": true, "positive": false, "negative": true }, 
  { 
    "event": "add", 
    "uid": 21, "category": 0, "categoryCnt": 21, "silent": true, "important": false, 
    "preExisting": true, "positive": false, "negative": true }, 
  { 
    "event": "add", 
    "uid": 22, "category": 0, "categoryCnt": 22, "silent": true, "important": false, 
    "preExisting": true, "positive": false, "negative": true }, 
  { 
    "event": "add", 
    "uid": 23, "category": 0, "categoryCnt": 23, "silent": true, "important": false, 
    "preExisting": true, "positive": false, "negative": true }, 
  { 
and so on and so forth for over 1500 lines, taking up about 80% of the memory dump.
```
I'm assuming these are past notifications, and also that they must be iOS related because of the reference to ANCS, and I'm not sure why there's so many of them. Maybe the iOS integration isn't clearing out old notifications? I assume a fix would involve erasing these events when new ones come in, or erasing old events every few hours. Also, googling this issue yields zero hits and no useful information.

**Comment by gfwilliams** [comment]
Thanks for tracking this down! It's an odd one - it looks like maybe `NRF.ancsGetNotificationInfo` can maybe end up never returning sometimes... Do you still get messages in that state, or were they not arriving?

I guess if the iPhone disconnected while `ancsGetNotificationInfo` was being called, that would do it.

I've just made some changes to the iOS app (in the development app loader) which should help, and I also pushed a new cutting edge Bangle.js firmware that should at least try and 'reject' the promise returned by ancsGetNotificationInfo if there are any problems.

Maybe you could give those a try and see if they help?

**Comment by gfwilliams** [comment]
Excellent, thanks! Yes, `ancsMessageQueue` should be empty.

> get it disconnected while ancsGetNotificationInfo was being called

Do you think this might have been the issue? It definitely would have broken things before.
