### ISSUE TITLE
appusage.json not updated

### ISSUE THREAD

**Issue by BartS23** [espruino/BangleApps#2405]
Is it possible that the appusage.json is no longer updated?

About 4 weeks ago I installed my own app on my 2 watches. It does not show up in appusage.json as a favorite or installed.

All the app loaders I use (browser and Gadgetbridge) submit the analytics data.

**Comment by gfwilliams** [comment]
No, I think it's fine. I just checked the server and it was updated at midnight last night.

Which apps were they? I can see if it got reported. Are you sure you had the toggle to report app usage stats enabled?

**Comment by BartS23** [comment]
Yes, the switch is turned on and the data is also transmitted.

For example "rmkAndroid" is one of this apps.
