### ISSUE TITLE
Lock Widget 0.07 , not disappearing when BTN is pressed

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#2409]
### Affected hardware version

Bangle 2

### Your firmware version

2v16.24

### The bug

Allow the screen to lock

Now click the button
The LCD will come on but the lock icon does not clear.

Configuration:
  FW 2.16.34
  Bootloader 0.55
  Settings 0.55
  Launcher 0.20
  Anton 0.11
  Lock Widget 0.07

**Comment by gfwilliams** [comment]
Do you see anything on the Web IDE if you connect and try and unlock?

Those are basically the factory apps and I have a watch here with them running, and it works fine.

So I wonder whether something has got broken on your watch? It might explain https://github.com/espruino/BangleApps/issues/2413 as well

**Comment by hughbarney** [comment]
Can reproduce on 2.16.45 as well.
The issues goes away if you install another widget.  Eg the standard battery widget.
Will check the IDE now.

**Comment by gfwilliams** [comment]
> So seems a problem when widlock is the ONLY widget.

Ahh, right! So it's basically that when the widget is hidden, it takes no space and drawWidgets thinks there is no widget bar. Fixed now - more info in https://github.com/espruino/BangleApps/issues/2413#issuecomment-1357430792
