### ISSUE TITLE
LCD Clock - not handling widgets properly

### ISSUE THREAD

**Issue by hughbarney** [espruino/BangleApps#2413]
### Affected hardware version

Bangle 2

### Your firmware version

2v16.45

### The bug

The LCD clock does not appear to be handling widgets properly.

There are a few disolay issues:
1. The initial display has the PM/AM DAY / DATE field overlap the bar in the middle
2. When the lock screen kicks in the top of the 2 squares at the top are overwritten.
3. When Firmware Clock Info is used the font is reduced to such a point that it cant be read.
It looks like the width is being estimated on the length of the string rather than using `g.stringWidth(str);`
to get the pixels that the string will use up.  This is more accurate and will not suffer from full stops
being calculated as a full width character in the version string of the firmware.

screenshots attached
![download](https://user-images.githubusercontent.com/3630481/208315688-c2398d34-74e0-465f-82c9-957f7055fb97.png)
![download (1)](https://user-images.githubusercontent.com/3630481/208315695-deead13e-f375-459b-85db-9e03fdf6c262.png)
![download (2)](https://user-images.githubusercontent.com/3630481/208315697-be218ed8-9274-484d-8c08-788f88b7f84b.png)

**Comment by gfwilliams** [comment]
What apps do you have installed? Do you see any errors in the IDE?

Because I just installed this on a watch again here and it work fine

**Comment by gfwilliams** [comment]
> When Firmware Clock Info ...

You can check in the code yourself but it does get the string width properly. It's just that with the font it has, you're limited to either 1x or 2x scaling - and maybe 1x is too small to be easily visible.

**Comment by hughbarney** [comment]
Issue goes away when a second widget is installed.  Seems related to #2409.

**Comment by gfwilliams** [comment]
Ok, this is a tricky one. I think you will find that pretty much every single app using appRect fails like this if you have *just* the lock widget installed.

I've just 'fixed' this by making the lock widget take up 1px even when it's not shown. It seems a shame to have to do this when it's a very rare case though, and I think you in fact campaigned for `widlockunlock` so you probably wouldn't even use this anyway?
