### ISSUE TITLE
[widmessages] Showing only generic icon on all apps

### ISSUE THREAD

**Issue by Kedlub** [espruino/BangleApps#2416]
### Affected hardware version

Bangle 2

### Your firmware version

2v16

### The bug

The widmessages widget stopped showing the right icons for all apps. For example, Home Assistant has a custom icon, which is visible in the messages app, but it shows the basic black/white envelope on the widget. After some troubleshooting, it seems that it happens on both Android and iOS devices. Even a clean install didn't help.

### Expected behavior
A widget that displays the correct icon

### How to reproduce
Connect Bangle.js to any mobile device
Receive notifications from any app that should have an icon
See that in messages the correct icon is shown, but on the widget, it is not

**Comment by gfwilliams** [comment]
Ahh, interesting - thanks! Yes, I can see this too now.

Just put a fix in in the development app loader
