### ISSUE TITLE
Gadgetbridge falsely interpretes UTF-8 as ISO 8859-1

### ISSUE THREAD

**Issue by Xaseron** [espruino/BangleApps#244]
It looks like the Gadgetbridge notification getting falsely encoded to ISO 8859-1.
Special characters like `äöüß` are getting encoded like in this debug table: https://www.i18nqa.com/debug/utf8-debug.html

I've tried to dig through the code but i didn't find the location where the conversion is applied.

**Comment by gfwilliams** [comment]
Thanks for letting us know! This was something that needed to be fixed in Gadgetbridge. I've just done it, but it could take a while for the next build to come that contains it

**Comment by Xaseron** [comment]
Does the watch not support UTF-8?

**Comment by gfwilliams** [comment]
No, Strings are just 8 bit so there's just ISO 8859-1.
