### ISSUE TITLE
[BW Clock] Updated time draws over Clock Info selected boarder

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2459]
### Affected hardware version

Bangle 2

### Your firmware version

2v16.45

### The bug

When the clock info is selected there's a boarder around it. This overlaps with the time so it ends up painted over with black when the time updates. See image.

![download (2)](https://user-images.githubusercontent.com/97237430/211001030-3bde37d5-7942-4ef5-8408-fc64cb4e2122.png)

**Comment by gfwilliams** [comment]
Fixed with https://github.com/espruino/BangleApps/pull/2471
