### ISSUE TITLE
[BW Clock] Can't open launcher correctly when plugging in charger...

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2477]
### Affected hardware version

Bangle 2

### Your firmware version

2v16.49

### The bug

... except if the battery clock info was already shown prior to connecting the charger.

Reproduce:
1. Have BW Clock open
2. make sure to not be on the battery clock info
3. connect charger
4. battery clock info is automatically displayed
5. press hardware button
6. The UI stops responding to screen or hardware button input
7. (after a second or two the  analog clock widget is displayed if installed)
8. (Long press HW button to trigger `load()`ing clock anew, which works)

I think this might be what @BartS23 points out in https://github.com/espruino/BangleApps/pull/2471#discussion_r1064500843

### Installed apps

kbmulti (0.05)
widbthide (0.01)
widram (0.03)
calculator (0.07)
activityreminder (0.10)
pomoplus (0.05)
widanclk (0.02)
kbtouch (0.02)
run (0.14)
heartzone (0.01)
wohrm (0.09)
sevenmin (0.01)
banglexercise (0.03)
sleeplog (0.12)
swp2clk (0.04)
torch (0.11)
hrm (0.11)
lightswitch (0.06)
boot (0.55)
recorder (0.20)
spotrem (0.07)
podadrem (0.07)
sleepphasealarm (0.12)
annoy (0.01)
messages (0.58)
widmsggrid (0.04)
messageicons (0.03)
messagesmusic (0.05)
slopeclock (0.04)
tetris (0.01)
smpltmr (0.07)
weather (0.23)
circlesclock (0.23)
alarm (0.37)
android (0.20)
setting (0.56)
dragboard (0.07)
aiclock (0.07)
widminbat (0.02)
notify (0.12)
quicklaunch (0.08)
taglaunch (0.02)
altimeter (0.02)
messagelist (0.02)
health (0.20)
bwclk (0.28)
dtlaunch (0.22)
sched (0.19)
widalarm (0.01)
swscroll (0.02)
fastload (0.03)

All updated just recently via development app loader.

**Comment by gfwilliams** [comment]
Is this definitely with the 'new' BW Clock that uses 'addInteractive'?

**Comment by thyttan** [comment]
>Is this definitely with the 'new' BW Clock that uses 'addInteractive'?

Yes

**Comment by thyttan** [comment]
Small addition below:

Reproduce:
1. Have BW Clock open
2. make sure to not be on the battery clock info
3. connect charger
4. battery clock info is automatically displayed
5. press hardware button
6. The UI stops responding to screen or hardware button input
7. (after a second or two the  analog clock widget is displayed if installed) **(the bottom part of BW Clock will also redraw so the "Fastloading..." message is partially hidden)**
8. (Long press HW button to trigger `load()`ing clock anew, which works)

**Comment by thyttan** [comment]
Debug output from Web IDE, sorry for not adding it to begin with.

```
>
{"t":"status","bat":89,"chg":0}
Uncaught Error: clearInterval(undefined) not allowed. Use clearInterval() instead.
 at line 92 col 54 in clock_info
clearInterval(this.interval); delete this.interval; Bangle.r...
                           ^
in function "hide" called from line 227 col 16 in clock_info
      itm.hide();
               ^
in function "menuHideItem" called from line 289 col 58 in clock_info
    menuHideItem(menu[options.menuA].items[options.menuB]);
                                                         ^
in function "remove" called from line 299 col 24 in bwclk.app.js
clockInfoMenu.remove();
                     ^
in function "kill" called from line 324 col 10 in bwclk.app.js
    kill();
         ^
in function "a" called from line 2 col 168
...e;delete Bangle.uiRemove;a()}g.reset();if(c){if("updown"==c)...
                              ^
in function called from line 1 col 31
Bangle.uiRemove?(Bangle.setUI(),(__FILE__=a)||(a=".bootcde")...
                              ^
at line 1 col 115
..."Storage").read(a))):load(a)
                              ^
in function called from line 75 col 11 in .boot0
    o(name);
          ^
at line 75 col 12 in .boot0
    o(name);
           ^
in function "o" called from line 902 col 8 in .boot0
o(f);
   ^
in function "load" called from line 1 col 408
...))}c?Bangle.load(b.launcher):eval('E.showMessage("No Launche...
                              ^
in function called from system
Uncaught Error: clearInterval(undefined) not allowed. Use clearInterval() instead.
 at line 92 col 54 in clock_info
clearInterval(this.interval); delete this.interval; Bangle.r...
                           ^
in function "hide" called from line 227 col 16 in clock_info
      itm.hide();
               ^
in function "menuHideItem" called from line 289 col 58 in clock_info
    menuHideItem(menu[options.menuA].items[options.menuB]);
                                                         ^
in function "remove" called from line 299 col 24 in bwclk.app.js
clockInfoMenu.remove();
                     ^
in function called from system
>
{"t":"status","bat":89,"chg":1}
Uncaught Error: clearInterval(undefined) not allowed. Use clearInterval() instead.
 at line 92 col 54 in clock_info
clearInterval(this.interval); delete this.interval; Bangle.r...
                           ^
in function "hide" called from line 227 col 16 in clock_info
      itm.hide();
               ^
in function "menuHideItem" called from line 289 col 58 in clock_info
    menuHideItem(menu[options.menuA].items[options.menuB]);
                                                         ^
in function "remove" called from line 299 col 24 in bwclk.app.js
clockInfoMenu.remove();
                     ^
in function "kill" called from line 324 col 10 in bwclk.app.js
    kill();
         ^
in function "a" called from line 2 col 168
...e;delete Bangle.uiRemove;a()}g.reset();if(c){if("updown"==c)...
                              ^
in function called from line 1 col 31
Bangle.uiRemove?(Bangle.setUI(),(__FILE__=a)||(a=".bootcde")...
                              ^
at line 1 col 115
..."Storage").read(a))):load(a)
                              ^
in function called from line 75 col 11 in .boot0
    o(name);
          ^
at line 75 col 12 in .boot0
    o(name);
           ^
in function "o" called from line 902 col 8 in .boot0
o(f);
   ^
in function "load" called from line 1 col 408
...))}c?Bangle.load(b.launcher):eval('E.showMessage("No Launche...
                              ^
in function called from system
> 
```
