### ISSUE TITLE
[widget utils/Fastload Utils] Initial .hide() will not hide widgets when fast loading, needs a .show() first

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2478]
### Affected hardware version

Bangle 2

### Your firmware version

2v16.49

### The bug

First discussed in https://github.com/espruino/BangleApps/pull/2464#issuecomment-1375354642.

I experience this with Podcast Addict Remote and Remote for Spotify, when fast loading from BW Clock (using Quick Launch) and from Desktop Launcher (both showing widgets) using Fastload Utils installed on the watch. The bug is not present if not using Fastload Utils.

I have yet to see if this bug is present when switching to other apps than the two mentioned using .hide(). I have also not tried launching them from other clocks or launchers.

Please propose other apps utilizing .hide() for testing this bug.

Reproduce:
1. Install Desktop Launcher and Fastload Utils
2. open Podcast Addict Remote
3. Notice widgets are not hidden.

### Installed apps

kbmulti (0.05)
widbthide (0.01)
widram (0.03)
calculator (0.07)
activityreminder (0.10)
pomoplus (0.05)
widanclk (0.02)
kbtouch (0.02)
run (0.14)
heartzone (0.01)
wohrm (0.09)
sevenmin (0.01)
banglexercise (0.03)
sleeplog (0.12)
swp2clk (0.04)
torch (0.11)
hrm (0.11)
lightswitch (0.06)
boot (0.55)
recorder (0.20)
spotrem (0.07)
podadrem (0.07)
sleepphasealarm (0.12)
annoy (0.01)
messages (0.58)
widmsggrid (0.04)
messageicons (0.03)
messagesmusic (0.05)
slopeclock (0.04)
tetris (0.01)
smpltmr (0.07)
weather (0.23)
circlesclock (0.23)
alarm (0.37)
android (0.20)
setting (0.56)
dragboard (0.07)
aiclock (0.07)
widminbat (0.02)
notify (0.12)
quicklaunch (0.08)
taglaunch (0.02)
altimeter (0.02)
messagelist (0.02)
health (0.20)
bwclk (0.28)
dtlaunch (0.22)
sched (0.19)
widalarm (0.01)
swscroll (0.02)
fastload (0.03)

**Comment by thyttan** [comment]
```
/*
1. Upload this script to a file "testWU.js" via Web IDE.
2. Navigate the watch to a clock/launcher/app with remove-function specified and widgets shown (I use BW Clock).
3. In console field enter "Bangle.load('testWU.js')".
4. Notice if widgets are hidden or not (Most of the time they would not be hidden for me and be interactable ,e.g. Light Switch Widget, the red back button will be hidden but interactable).
5. Click hardware button to load the user chosen clock (for the following steps it should have a remove function, or specify another app in the back function below)
6. Notice if widgets are shown or not (On BW Clock they are shown as expected).
7. In console field again enter "Bangle.load('testWU.js')".
8. Notice if the widgets are hidden or not (They are not hidden for me).
9. In console field again enter "Bangle.load('testWU.js')".
10. Notice if the widget are hidden or not (This time they are hidden for me, however if I tap upper left corner the back widget still executes and if I tap the upper right corner Light Switch Widget will be triggered).
11. Press hardware button to load the user chosen clock.
12. Notice if widgets are shown (they are shown for me).

The expected behavior would of course be that the widgets are always hidden when testWU.js is launched.
*/

{
g.clear();

  Bangle.setUI({
    mode : "custom",
    back : ()=>{Bangle.load();},
    remove : ()=>{require('widget_utils').show();}
  });

  Bangle.loadWidgets();
  require('widget_utils').hide();
}
```

**Comment by gfwilliams** [comment]
@halemmerich any ideas about this one?

**Comment by halemmerich** [comment]
@thyttan I have tried your steps with BWClock and I see the same behaviour there.
Tests with Anton and newly fastloadable Berlin Clock do not show the problem.

So at first glance I would suspect a problem in BWClock. It does not seem to use widget_utils for hiding and showing the widgets so that is probably the cause or at least part of it.

**Comment by thyttan** [comment]
I'll try adding widget utils in BW Clock then, then we can check it off on #2196 as well. I looked at doing that before but didn't really understand the current handling of widgets though 🙃 Maybe I'll get it this time.

**Comment by thyttan** [comment]
So when I add widget utils to BW Clock .hide() works directly with the test code above as well as the two aforementioned apps.

However, interactable widgets such as the back button (via setUI back function) and Light Switch Widget will still be triggered if I touch where they usually are.

**Comment by thyttan** [comment]
Aha! :)

**Comment by thyttan** [comment]
I don't know if something should be done so .hide() works even in the case when loading from a clock app which doesn't use widget_utils? Otherwise it's ok with me to close this.

#2492 Converts all remaining clocks to use widget_utils.

**Comment by halemmerich** [comment]
I don't think that is easily doable. The problem was BWClock attempting the same things as widget_utils (renaming and changing `draw`/`_draw`). So essentially converting everything to widget_utils and having an eye on future changes trying to do something like it should solve this.

**Comment by thyttan** [comment]
Thank you both for checking this out!

**Comment by gfwilliams** [comment]
> I think that is expected since hide/show currently only handles the drawing code, not the listeners of the loaded widgets.

Yes, it is. Not ideal but I think for most cases it's not an issue.

> I don't know if something should be done so .hide() in an app works even in the case when loading from a clock app which doesn't use widget_utils? 

Fast load should only work for apps that have 'opted in' by adding `remove` listener - so really if an app has added 'fast load' and it's breaking other stuff because of something like its widget hiding, that means that whoever added it didn't test it properly.
