### ISSUE TITLE
Feature request: low power mode

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2502]
When the battery goes below a low battery level, enter low power mode only showing the time, not allowing any other features and no backlight. I imagine this would be baked into the firmware, but I guess an app could accomplish most of these things as well. Inspiration for the request: https://youtu.be/VXSUQSpBYTo?t=327

**Comment by gfwilliams** [comment]
I seem to remember this being requested before as well, but given the relatively long battery life normally it's probably not super high priority.

There are still some things (like alarms) that it's expected would function, but I bet this could be made into an app (maybe with some changes to the `boot` app to restrict what gets loaded).

**Comment by myxor** [comment]
It could also do some changes to the settings, e.g.:

- LCD brightness
- LCD timeout
- Disable auto heart rate measurement in health app
- Overwrite setGPSPower() function?
- ...

**Comment by hughbarney** [comment]
* turn wake on twist off

**Comment by pavelmachek** [comment]
I would not mind having something like this. I left GPS logging running for too long, and result was crashed watch and lost time. It would be more friendly to go to some kind of "safe mode" (only showing time, GPS off) when battery goes to 5%.

**Comment by gfwilliams** [comment]
Thanks - while I'm not a great fan of a general low power mode as I mentioned above, I can totally imagine cases like yours where GPS gets left on, in which case it would be really handy to have the watch automatically turn it off if the battery got too low.

I could be wrong here but it feels like really GPS is the only 'big power draw' thing that might get turned on that'd flatten the watch battery in less than a day (apart from the backlight, but it'd be rare that anyone was able to turn that on and leave it on).

Maybe turning GPS off automatically should be built into the watch itself

> and result was crashed watch

What actually happened? You mean the watch just turned off? Or there was some other issue?

**Comment by bobrippling** [comment]
I've [pushed up an app](https://github.com/espruino/BangleApps/pull/2684) that does a fair chunk of this - if anyone fancies giving it a go, let me know what you think / PRs also welcome.
