### ISSUE TITLE
[app/inspire] Not available in the store

### ISSUE THREAD

**Issue by trufae** [espruino/BangleApps#2513]
### Affected hardware version

Bangle 2

### Your firmware version

2v16

### The bug

My PR was merged last week but i still dont see it listed in the development page of the bangleapps site. did i missed anything?

**Comment by gfwilliams** [comment]
No - the update from the development app loader at https://espruino.github.io/BangleApps/ to the main one is kicked off manually by me every so often, and I'm a bit busy recently so didn't have a chance to do it.

I've just started it now so your app should appear in maybe 30 minutes

**Comment by trufae** [comment]
Uhm , sorry but its still not there

**Comment by nxdefiant** [comment]
It does show up for me for BangleJS1, do you expect it to be installable for BangleJS2? because it is not configured to do so
https://github.com/espruino/BangleApps/blob/master/apps/inspire/metadata.json#L10
