### ISSUE TITLE
Heart Rate Recorder : how to download the data?

### ISSUE THREAD

**Issue by dariosalvi78** [espruino/BangleApps#257]
How can the files generated by Heart Rate Recorder be downloaded?

Thanks!

**Comment by brainfart-be** [comment]
Using the IDE ( https://www.espruino.com/ide/ ) you can read file from the device (the Database icon on the middle bar)

You can also write a script using Puck.js

**Comment by Purple-Tentacle** [comment]
You can click on an arrow pointing down in the app loader as well.
https://banglejs.com/apps/#

**Comment by gfwilliams** [comment]
As @Purple-Tentacle  says:
