### ISSUE TITLE
Uninstalling an app that includes a widget leaves behind global handlers (e.g Torch App)

### ISSUE THREAD

**Issue by PaulMcGuinness** [espruino/BangleApps#262]
If you install 'Torch' app then uninstall it, the 4 button press still exists but blanks the screen.

**Comment by Didgeridoohan** [comment]
Did you uninstall from banglejs.com/apps, or from the App Manager on the device?

I saw this behaviour when removing the Torch with the App Manager on the watch, but not when using the App Loader.

Meant to bring that up, but forgot. Thanks for the reminder.

**Comment by PaulMcGuinness** [comment]
From the app manager, I'll try from the loader, cheers.

**Comment by PaulMcGuinness** [comment]
That did the trick. Note to self; Only install / uninstall from banglejs.com/apps 👍

**Comment by gfwilliams** [comment]
Opening as I'd like to fix the app manager :)

**Comment by Didgeridoohan** [comment]
Quick fix... Nice!
