### ISSUE TITLE
Language pack breaks settings menu

### ISSUE THREAD

**Issue by paulcockrell** [espruino/BangleApps#263]
# Issue
Language pack breaks settings menu labels / values. (Only tested with EN_GB) 

# Actual result
Some settings menu options/values display '[native code]' instead of expected label.

# Expected result
Correct settings menu labels displayed in English.

# Notes
Uninstall language app and menu back to normal

**Comment by MaBecker** [comment]
Hi,

can you please add pictures to fix this - thanks.

**Comment by paulcockrell** [comment]
@MaBecker 
![IMG_20200409_074406](https://user-images.githubusercontent.com/260514/78871755-1a8a7a80-7a40-11ea-9824-52ea71c25108.jpg)

**Comment by gfwilliams** [comment]
Thanks - just fixed this with ea32401ba6fc944825c94dad69e27a5da61159c0

I'd spotted it once before but assumed I was using a broken dev firmware :)
