### ISSUE TITLE
App Install Failed, Undefined

### ISSUE THREAD

**Issue by NovaDawn999** [espruino/BangleApps#2636]
### Affected hardware version

Bangle 2

### Your firmware version

2v16

### The bug

Clicking "Install Default Apps" on stable or dev apploader results in an error message "app install failed, undefined". Results in no apps being installed.

Expected it to restore the default set of apps after removing current apps.

1. connect to apploader
2. "More..."
3. "Install Default Apps:"

Additional steps:
- Reinstalled 2v16
- installed 2v16.xxx build
- attempted from gadgetbridge
- attempted from pc
- Tried on Stable and Dev app loaders

### Installed apps

boot (0.57)

**Comment by gfwilliams** [comment]
Thanks - just reproduced here, I'll try and get a fix in soon
