### ISSUE TITLE
[time] System time gains 10-or-so seconds a day

### ISSUE THREAD

**Issue by pavelmachek** [espruino/BangleApps#2649]
### Affected hardware version

Bangle 2

### Your firmware version

The one from FOSDEM

### The bug

Watch seems quite inaccurate; after few days without synchronization, time is off by minute or two. Auto-sync-on-gps widget helps here, but I wonder if we could do better.

**Comment by nxdefiant** [comment]
You could try https://banglejs.com/apps/?id=widadjust

**Comment by pavelmachek** [comment]
Thanks, widadjust solves the problem nicely. I guess it is hw problem we can do little about, and widadjust is adequate solution.
