### ISSUE TITLE
[astrocalc] sun/moon positions are wrong

### ISSUE THREAD

**Issue by pavelmachek** [espruino/BangleApps#2651]
### Affected hardware version

Bangle 2

### Your firmware version

The one from FOSDEM

### The bug

Sunrise/sunset times are right, but azimuth degrees are wrong. Both for current position and for sunrise (and others). For example for sunrise it indicates time 6:17 (which is ~ right for prague) but degrees: -87.

**Comment by nxdefiant** [comment]
This uses https://github.com/mourner/suncalc any chance you can check if this is an upstream problem?

**Comment by nxdefiant** [comment]
Just checked, according to https://github.com/mourner/suncalc is 0° is south. I will just add 180°.
