### ISSUE TITLE
HRM doesn't turn off

### ISSUE THREAD

**Issue by yshui** [espruino/BangleApps#2674]
### Affected hardware version

Bangle 2

### Your firmware version

2v16

### The bug

The heart rate monitor is on the whole time, draining battery quickly.

I tried to `Bangle.setHRMPower(false)` but that doesn't work either. Even after restarting the watch (holding the button), it's still on. it only turns off when I am not wearing it.

Maybe it's a boot app turning it on, how can I diagnose what's turning it on?

**Comment by bobrippling** [comment]
If you use [the IDE](https://www.espruino.com/ide/), what's on `Bangle._PWR` ?

**Comment by yshui** [comment]
I suspect maybe I reset the watch after HRM is turned on, which cleared the timers what was going to turn it off?
