### ISSUE TITLE
[BW Clock/BW Clock Lite/Clock Info Module] Battery gfx shows a solid filled square instead of battery icon

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2749]
### Affected hardware version

Bangle 2

### Your firmware version

2v17.106

### The bug

It now looks like this:
![image](https://github.com/espruino/BangleApps/assets/97237430/a05c7af9-9cf7-4ed2-8ebe-664f8cfe3119)

Before https://github.com/espruino/BangleApps/commit/cde38188150acedc2950da8d4ade74aa5283a826 there was a static battery icon where the filled square is.

Expected behavior would be for the new dynamic icon introduced with https://github.com/espruino/BangleApps/commit/cde38188150acedc2950da8d4ade74aa5283a826 to be shown, as it is on e.g. Pebble++ clock face.

### Installed apps

notify (0.12)
podadrem (0.07)
spotrem (0.07)
android (0.23)
lightswitch (0.06)
widanclk (0.02)
backswipe (0.02)
torch (0.11)
calculator (0.07)
agenda (0.13)
smpltmr (0.07)
kbmulti (0.05)
widram (0.03)
widbthide (0.01)
messageicons (0.05)
widalarm (0.01)
boot (0.57)
runplus (0.18)
dtlaunch (0.23)
agpsdata (0.06)
messagesmusic (0.05)
alarm (0.41)
hrmmar (0.02)
taglaunch (0.03)
swscroll (0.03)
messagegui (0.65)
longpressbuzz (0.01)
bwclklite (0.33)
bwclk (0.32)
widmessages (0.05)
clkinfostopw (0.03)
recorder (0.23)
health (0.23)
quicklaunch (0.15)
polymath (0.01)
fastload (0.04)
sched (0.22)
fastreset (0.01)
setting (0.60)
clock_info (0.03)
messages (0.59)
drained (0.03)
widminbat (0.03)
powermanager (0.10)
pebblepp (0.01)

**Comment by gfwilliams** [comment]
Ahh - thanks! That's an annoying one - so the main issue is that BW Clock/Lite set BG and FG to the same thing (which I just fixed), but then ideally asImage would be able to create an image string that was transparent.

I could hack up something for that, but I think instead I will fix it properly in the Espruino firmware as hopefully now those clocks are fixed there won't be any more immediate problems
