### ISSUE TITLE
[widget_utils] swipe-down Widgest are not rotated when Lefty flip enabled.

### ISSUE THREAD

**Issue by kamilkrz** [espruino/BangleApps#2767]
### Affected hardware version

Bangle 2

### Your firmware version

2v17, 2v17.71(Cutting Edge)

### The bug

The bug
"Slide down" gesture to show hidden widgets shows wrong when clock is set up in lefty LCD orientation

**Comment by gfwilliams** [comment]
Hi, thanks - so just to be clear, what actually happens? They respond to a swipe down from the top, but then they slide in from the bottom?

The may be a firmware issue since the overlay is handled in that, and I guess it should probably honour the system rotation setting

**Comment by gfwilliams** [comment]
Ok, thanks - I've just put a fix in but you'll have to update your Bangle to the latest 'cutting edge' firmware fot it
