### ISSUE TITLE
Time does not update on screen wake-up until you re-open morph clock

### ISSUE THREAD

**Issue by PaulMcGuinness** [espruino/BangleApps#279]
If you start the device the clock shows 1am, then syncs to the phone / gps and shows 6:15am (as an example), and won't show 7:15am till you've pressed BTN2 and selected Morph Clock again.

**Comment by gfwilliams** [comment]
Where are you syncing time from? Gadgetbridge, or the App loader?

**Comment by PaulMcGuinness** [comment]
No idea - How can I tell

**Comment by PaulMcGuinness** [comment]
@gfwilliams - Ok, more testing, and I don't think it has anything to do with time syncing.

Here is the scenario:-

My locale is set to +1 (BST)
LCD Wakeup set "On Twist" to "On"

Put watch on desk. Leave for >1 hr pick up and screen comes to life showing Morphing Clock but shows UTC time (+0 hrs) 

Press BTN2, select Morphing Clock again and correct BST (+1) shows.

**Comment by gfwilliams** [comment]
Does the clock 'morph' to the new time at all after a second or two?

It's set up so that when you power the screen on, it shows the old time, then morphs to the new one...

**Comment by PaulMcGuinness** [comment]
It morphs to the "wrong" time, then when you press BTN2 and go back to it, it just shows the "right" time.

**Comment by gfwilliams** [comment]
Are you sure all the software is up to date? This used to be an issue with very early bootloader versions but it was solved at least a month ago.

**Comment by PaulMcGuinness** [comment]
Definitely. Just in case there are some gremlins in the system, how can I do a complete 'wipe and factory reset' to a total 'clean' Bangle?

**Comment by gfwilliams** [comment]
If you go to https://banglejs.com/apps/, then `About`, and `Install Default Apps`, that should erase everything and start again

**Comment by PaulMcGuinness** [comment]
I'll try that later and let you know if it solves it.

**Comment by PaulMcGuinness** [comment]
Seems to have fixed it. I suspect it was an issue with legacy bits of code / settings during updating rather than uninstalling / re-installing.

**Comment by PaulMcGuinness** [comment]
Ok - This has nothing to do with TimeZones. I've just replicated this from a 'Wiped' device and attached a video to demonstrate the issue.

Essentially;

Let display go to sleep.
Pickup device and move around a bit so screen lights up.
Clock shows time it went to sleep.
Press BTN2 x 2  and correct time shows.

 ([bangle_test.zip](https://github.com/espruino/BangleApps/files/4504759/bangle_test.zip)

**Comment by PaulMcGuinness** [comment]
Just tested it again, and it seems the morph freezes when the screen wakes up (by motion)

![20200420_192809](https://user-images.githubusercontent.com/124485/79786654-b61fc300-833d-11ea-9fb1-db2b698be0e4.jpg)

**Comment by gfwilliams** [comment]
Wow, interesting. So literally just a fresh install by 'Install default apps' (nothing else) and wake up with motion and it hangs mid-morph? Does it happen all the time, or just sometimes? I tried once or twice here with a fresh install and couldn't reproduce it.

**Comment by PaulMcGuinness** [comment]
The mid-morph has only happened once. But the "Show the last time" happens every time - Even if I wake it up by pressing BTN1. I did the "Install default apps", but that just seems to cycle an uninstall / install process. Is there a more 'proper' way to factory reset the firmware (without taking it apart and using pogo-pins etc.)

**Comment by gfwilliams** [comment]
Install default apps should do it properly - it totally clears the whole flash area then re-installs everything. Updating the watch firmware may help though: https://www.espruino.com/Bangle.js#firmware-updates

**Comment by PaulMcGuinness** [comment]
Just had the same frozen morph after blowing new FW onto it :-(

Is it something to do with the 'Twist' screen wakeup?

**Comment by Didgeridoohan** [comment]
I just realised I've been seeing something similar with the binary clock the past couple of days. Once in a while when the screen wakes up, the clock is frozen and need a refresh (long press BTN3) to start ticking again.

Will take a closer look now...
