### ISSUE TITLE
[Bangle 1] How to receive notifications from iOS

### ISSUE THREAD

**Issue by trumbitta** [espruino/BangleApps#2793]
I have successfully paired my Bangle 1 with my iPhone 8, both from the BT system settings and from the nRF Connect iOS app.
Both times it also asked me if I wanted my watch to receive notifications and I chose "Yes"
I have installed the iOS app on the watch + the messages app etc

I made somebody send me an SMS, but when it arrived on my iPhone, nothing showed up on my watch and the messages app is empty.

What am I doing wrong?

**Comment by gfwilliams** [comment]
Just having the iOS app on the Bangle and *then* pairing with the phone *should* be enough.

What firmware do you have on the Bangle? If it's older firmware then something might not be implemented that should be

**Comment by trumbitta** [comment]
Apparently it does get notifications for reminders, but not for SMS

**Comment by gfwilliams** [comment]
Ok, that's odd - I'm pretty sure iOS is capable of sending SMS notifications (which it would do in the same way as reminders).

Can any other users of Bangle.js 1 or 2 confirm that they do/don't get updates for SMSs?

**Comment by Mineinjava** [comment]
Not sure if this is still relevant but I get all notifications from my phone (ios 17.1) on the bangle.js 2

**Comment by gfwilliams** [comment]
Thanks! Ok, I think this can be closed then - iOS notification handling is the same on Bangle.js 1/2
