### ISSUE TITLE
[E.showMenu] Title of selected item in options array appears in subsequent list

### ISSUE THREAD

**Issue by philipandresen** [espruino/BangleApps#2816]
### Affected hardware version

Bangle 2

### Your firmware version

2v18

### Description
When using the array version of menus along with E.showMenu (as described in the docs), while navigating from one menu to another, the selected item on the first menu appears in the second menu.

### Expected Behaviour
The second menu renders normally and the first menu can no longer be seen.

### Reproduction steps
1. Open web IDE, write the following code. Note that only the first menu needs to be the "array" type to reproduce.
```
let menu = [
  { title:"A"},
  { title:"B"},
  { title:"C", onchange:function() { E.showMenu(submenu); } },
];
menu[""] = { title:"Hello" };

let submenu = {
  "" : { title : "World", back : function() { E.showMenu(menu); } },
  "One" : undefined,
  "Two" : undefined,
  "Three" : undefined,
  "Four" : undefined
};

E.showMenu(menu);
```
2. When the code loads, select item "C".
3. Note that the second menu renders normally but with "C" superimposed (this follows scrolling motions too).
4. Note that the menu item that lingers from one to the other is the one you pressed to navigate.

The lingering button cannot be interacted with, but it can be cleared when an element underneath it is pressed such that it refreshes its render.

### Root cause hypothesis:
Relevant file: https://github.com/espruino/Espruino/blob/bc52028cb9271c4901259c6d399835715c2868a8/libs/js/banglejs/E_showMenu_Q3.js#L4
The issue I think becomes pretty clear when you compare the code for handling "onchange" versus an object-type-menu that just has items that are functions. In the case where we are seeing the bug we have:
```
if (item.onchange) item.onchange(item.value);
scr.scroll = l.scroller.scroll; // set scroll to prev position
show(); // redraw original menu
```
And in the case where we have no bug we haveL
```
if ("function" == typeof item) item(l);
else if ("object" == typeof item) {
```

#### Proposed solution:
Add an "onSelect" parameter that would be distinct from "onchange" in that it would just execute the function and not do anything else afterward. This would allow the array type menu to be closer in functionality to the object type menu without any backwards compatibility issues. I will see about getting a PR together if that seems like a good solution.

#### Alternate proposal:
Take a value returned by "onchange" and decide whether or not to render again based on that. Upside to this would be that it's close to the same programmatic contract with the users. Downside would be there's a greater likelihood of regressions for users that may be returning values that are ignored currently.

### Alternate hypothesis
It is possible that I should not be using `onchange` for navigation. There may be some other parameter that's more suitable that isn't documented. I will close this if I find such a thing!

### Installed apps

Default apps only plus one custom keyboard library [kbmatry]

**Comment by nxdefiant** [comment]
There is a known workaround to use setTimeout to have the onchange callback called after the draw and not nice versa.

`{ title:"C", onchange:function() { setTimeout(() => E.showMenu(submenu)) } },`

**Comment by philipandresen** [comment]
> There is a known workaround to use setTimeout to have the onchange callback called after the draw and not nice versa.
> 
> `{ title:"C", onchange:function() { setTimeout(() => E.showMenu(submenu)) } },`

That's good to know. Is this issue a duplicate by chance? I did look around but didn't see anything open.

**Comment by stweedo** [comment]
I wasn't aware of this bug, but I did run into it in one of my menus and thought I was doing something wrong. Using a setTimeout fixed it.
```
setTimeout(() => {
  E.showMenu(createMainMenu());
},(0));
```
Thank you :)

**Comment by gfwilliams** [comment]
Thanks - in the old menu style (`{ "text": function}`) this shouldn't be an issue - as @philipandresen noted it seems this only happens for menus where you have an `onchange` handler.

I think the nicest option is actually to make the menu detect if it's still 'active' (eg if `setUI` was called during the `onChange` handler) and only redraw if so... so that should fix any other issues in code where `setTimeout` had to be added as well.

I've just put a fix in for this, so I think we're good now
