### ISSUE TITLE
[gpsrec] Switch File ID does not except changes

### ISSUE THREAD

**Issue by vkuehn** [espruino/BangleApps#2870]
### Affected hardware version

Bangle 2

### Your firmware version

2v18

### The bug

Buttom - GPS Recorder - File

When selecting file an up and down arrow are shown for the file ID but a change is not accepted

### Installed apps

Messages
Android
GPS Recorder
Health Tracking
OpenStreetMap

Rest is default

**Comment by gfwilliams** [comment]
Ok, thanks - does the normal `Recorder` app work ok for you? https://banglejs.com/apps/?id=recorder

The `GPS Recorder` app hasn't been updated in a while and isn't recommended - the standard Recorder should to everything it does, plus much more

**Comment by vkuehn** [comment]
the gps recorder has worked nicely so far. I'll check the Recorder App

**Comment by vkuehn** [comment]
record app works fine, just exausted battery in an hour. feel free to close the issue

**Comment by thyttan** [comment]
>record app works fine, just exausted battery in an hour.
Does 'gps recorder' have the watch lasting longer? Do you have a sense why in that case?

**Comment by bobrippling** [comment]
Might be todo with how easily it finds satellites - going to close this with the original issues being sorted as mentioned though :)
