### ISSUE TITLE
Suggestion: Screenshots for Apps

### ISSUE THREAD

**Issue by brainfoolong** [espruino/BangleApps#288]
For the web based view on https://banglejs.com/apps/, i really miss one thing since the very first beginning: Screenshots. I want to see, how this will look, directly on this page.

In my opinion it could be accomplished very easily:

1. Allow a folder named `screenshots` in an app directory.
2. Filter out all JPG/PNG and if one exist, display a screenshot button in the app row on the website.
3. Display all screenshots on click of that button.

If i could help you with that, let me know what i should do. I probably can modify the needed scripts that generate the website.

![image](https://user-images.githubusercontent.com/1684236/79104056-0f03c000-7d6e-11ea-8e7b-2307d634b3a8.png)

**Comment by paulcockrell** [comment]
If you find the Mario Clock in the app store, notice its `Read more...` link, click that link to open its README file, in which you see a screen shot of the app. Is that what you are after?

**Comment by brainfoolong** [comment]
Oh. Yep, that's what i searched for actually. Didn't knew of the Readme feature.
