### ISSUE TITLE
[backswipe] Feature Request: Disable on some keyboard libraries

### ISSUE THREAD

**Issue by thyttan** [espruino/BangleApps#2910]
There might be an app where it makes sense for backswipe to be active generally but the user uses a keyboard library that uses the right swipe for it's interface. In this situation it would be ideal if backswipe did not execute when the keyboard was active in the app, but was otherwise active.

Edit: An example app and keyboard combination is `podadrem` + `kbmulti`.

**Comment by bobrippling** [comment]
I think this ties in with a few other event handler discussions that've been going on recently (e.g. #2743).
We have `E.stopEventPropagation()` to skip subsequent handlers, but there's not the opposite - a way to ignore the event in favour of a subsequent handler, although it's something we could do, e.g.

```javascript
handler = () => {
	var onSwipe = Bangle["#onswipe"];
	if (typeof onSwipe !== "function") {
		var i = onSwipe.indexOf(handler);
		if (i >= 0 && i < onSwipe.length - 1) {
			// there's another handler after us, defer to it
			return;
		}
	}

	// normal swipe handling code
};

Bangle.on("swipe", handler);
```

**Comment by thyttan** [comment]
An example app and keyboard combination is `podadrem` + `kbmulti`.

**Comment by thyttan** [comment]
>We have E.stopEventPropagation() to skip subsequent handlers, but there's not the opposite - a way to ignore the event in favour of a subsequent handler, although it's something we could do, e.g.

I haven't tried to see if `E.stopEventPropagation()` added to `kbmulti` solves the issue. I'll try that.

**Comment by thyttan** [comment]
Adding `E.stopEventPropagation();` to `kbmulti` didn't help. 

I guess there are at least two other ways to go about this feature request besides your idea @bobrippling.

If there was a boolean telling whether or not `textinput` is active that condition could be added to the if-statement in `backswipe`-s `goBack` function.

Or something along these lines:

>Thinking out loud:
> When starting a listener with `Bangle.on()` or in `Bangle.setUI()` maybe there could be an argument passed that specified priority/where in the order of handlers it should run? The argument could have values reflecting first/last position or a number of "priority groups". Maybe nesting would be possible so you could say "this handler should run last in priority group 1" or "this handler should be run in subgroup 2 in priority group 3".

_Originally posted by @thyttan in https://github.com/espruino/BangleApps/issues/2743#issuecomment-1546910113_

**Comment by gfwilliams** [comment]
> maybe there could be an argument passed that specified priority/where in the order of handlers it should run?

I actually added `Bangle.prependListener` for exactly this. While a third parameter would be nice it's not spec compliant - `prependListener` is.

You just need to be careful when using it as it's only in cutting edge builds at the mo (or 2v19) so would have to have a fallback.

**Comment by thyttan** [comment]
>You just need to be careful when using it as it's only in cutting edge builds at the mo (or 2v19) so would have to have a fallback.

Do you mean doing `Bangle.prependListener&&Bangle.prependListener()` like with `stopEventPropagation()`?
