### ISSUE TITLE
Too many widgets installed breaks app/widget settings. LOW_MEMORY

### ISSUE THREAD

**Issue by Didgeridoohan** [espruino/BangleApps#295]
Testing some of the new apps I noticed that @msdeibel's Battery Chart (v0.05) seems to break App/Widget Settings (tested with Settings v0.13). With Battery Chart installed it's simply not possible to enter that sub menu.

**Comment by msdeibel** [comment]
Hmm, Battery Chart doesn't even use Settings. I just updated to settings 0.13 and cannot confirm this. I can enter the submenu for Gadgetbridge and BatterWidget and also make changes in there.

**Comment by Didgeridoohan** [comment]
I'll check more. It might be that there are other apps/widgets clashing as well. I tired several times though, and it was reproducible. It also caused my connection to the App Loader to fail while retrieving my apps...

**Comment by msdeibel** [comment]
Aww damn. In line 11 of the widget I currently have `var settings = {};`. That could be the culprit, even though I don't experience the issue as I said. I'll fix that at some point tomorrow.

**Comment by Didgeridoohan** [comment]
I just found that it only seems to happen if I also have Battery Widget with percent installed.

**Comment by Purple-Tentacle** [comment]
I suspect a memory issue.
I have the same problem with my 'Active Pedometer' widget.
There should be messages in the IDE.

**Comment by Didgeridoohan** [comment]
I'll check the IDE and see what pops up.

**Comment by Didgeridoohan** [comment]
Yup, definitely a memory thing. Seems like I simply had too many widgets and not anything specific to a certain widget.

**Comment by Purple-Tentacle** [comment]
Problem is, that widgets are loaded and displayed in the settings app. So they take a lot of memory.

**Comment by gfwilliams** [comment]
Is it specifically the app/widget settings menu that breaks? Because maybe we could tweak that to avoid requiring so much memory?

**Comment by Didgeridoohan** [comment]
From what I saw I couldn't enter either the Apps/Widget settings or the Select clock sub menus.

**Comment by gfwilliams** [comment]
Just pushed some changes that should help with memory usage

**Comment by Didgeridoohan** [comment]
Seems to have done it's job just right. No issues now (except if you install way more widgets than could even be displayed, but then things really start to break and you can't even open the launcher).

**Comment by gfwilliams** [comment]
I'll close this for now then.

I wonder whether we need something in the bootloader that'll handle the low memory event and display a warning?
