### ISSUE TITLE
[lcdclock] Rendering issue in version 0.04

### ISSUE THREAD

**Issue by sculpordwarf9** [espruino/BangleApps#2970]
### Affected hardware version

Bangle 2

### Your firmware version

2v18

### Describe the bug
After upgrading to v0.04, the clockface looks strange. It seems the whole clockface moves upwards and collides with the widgets:
![IMG_0300](https://github.com/espruino/BangleApps/assets/134924539/679aed25-56ba-42ff-99d3-ad011532da73)
Problem persists after I lock then unlock the screen:
![IMG_0301](https://github.com/espruino/BangleApps/assets/134924539/bd0265b6-d03d-4977-96cd-4302daee9ea2)

### Expected behavior
Clockface looks normal after I apply the workaround below:
![IMG_0302](https://github.com/espruino/BangleApps/assets/134924539/f0a136e9-a338-4689-b437-0d3ed4bcb63e)

### Step to reproduce
1. Open Settting
2. Go back to clockface by long pressing the button.

### Workaround
Go to app launcher and then go back by touching the arrow on top left of the screen.

**Comment by bobrippling** [comment]
I can't reproduce the bug here but I believe I know what the issue is. Would you mind trying out #2971?

I've deployed it to [my app pages here](https://bobrippling.github.io/BangleApps/?q=lcdclock).

**Comment by gfwilliams** [comment]
Heh, looks like we were both on this. I've just fixed it :)
