### ISSUE TITLE
App loader not building compiledC statements

### ISSUE THREAD

**Issue by glemco** [espruino/BangleApps#2972]
### Affected hardware version

Bangle 2

### Your firmware version

2v18

### The bug

I'm writing an app usign a consistent amount of native code (to render QR codes). I used the compiledC function as described [here](https://www.espruino.com/InlineC) and everything works fine if I upload from IDE, but if I install the app from the app loader, the C part is not compiled.
I tried both with pretokenizer and without, am I missing something? 

The app can be found in [cards](https://glemco.github.io/BangleApps/?q=cards) (I will probably open a draft PR soon).

**Comment by gfwilliams** [comment]
Unfortunately this was expected behaviour, as the inline C compiler needed some extra info to be able to create firmware. But I believe it's sorted now - at least in the dev app loader.
