### ISSUE TITLE
[sched] Alarms not firing and uneditable.

### ISSUE THREAD

**Issue by JAVAHTML1** [espruino/BangleApps#2985]
### Affected hardware version

Bangle 2

### Your firmware version

2v18

### The bug

Schedular App not firing alarms. Alarms, timers, and events uneditable in the App loader.

Expected to feel alarms going off. Expecting to be able to edit the alarms in the App loader.

Ways to reproduce:
Unknown.

### Installed apps

widbt_notify (0.17), calculator (0.07), waypoints (0.01), info (0.03), hrm (0.11), blackjack (0.03), ptlaunch (0.15), files (0.08), powersave (0.03), magnav (0.06), altimeter (0.03), henkinen (0.01), launch (0.20), gpssetup (0.02), gpsautotime (0.04), clicompleteclk (0.03), widdevst (0.03), gpsmagcourse (0.01), bledetect (0.04), widminbat (0.03), drained (0.03), lightswitch (0.07), rpnsci (0.03), shownearby (0.02), messageicons (0.05), messages (0.60), notify (0.13), mylocation (0.10), compass (0.09), boxclk (0.05), thermom (0.07), messagegui (0.73), folderlaunch (0.03), gpsinfo (0.12), promenu (0.02), runplus (0.21), astrocalc (0.05), rescalc (0.04), gipy (0.20), multitimer (0.07), fastload (0.06), recorder (0.30), clock_info (0.07), kbtouch (0.04), batchart (0.12), speedalt (0.13), qrcode (0.06), health (0.26), fileman (0.03), boot (0.59), poweroff (0.03), setting (0.63), sched (0.22), widalarm (0.01), alarm (0.42), openhaystack (0.01)

**Comment by nxdefiant** [comment]
What do you mean by "uneditable"? Can you edit the alarms on the watch?

**Comment by gfwilliams** [comment]
What do you mean by `uneditable in the App loader`? You mean you don't see an option to edit them from the app loader but there isn't one and you have to edit from the watch itself?

> Schedular App not firing alarms

If I create an alarm and go back to the clock, it works fine me here. Or is the issue that you're creating an alarm but then not exiting the scheduler app, and the alarm isn't firing?

**Comment by JAVAHTML1** [comment]
By `uneditable in the App loader` I mean if I try to edit my alarms using the Scheduler app on the App loader, it doesn't load the editing menu. I can try to edit the alarms in the alarms app on the watch, but they never go off.

**Comment by nxdefiant** [comment]
Can you please download the sched.json with the [web ide](https://www.espruino.com/ide/) and attach the file here?

**Comment by JAVAHTML1** [comment]
My watch does not have sched.json on it.

**Comment by thyttan** [comment]
> By `uneditable in the App loader` I mean if I try to edit my alarms using the Scheduler app on the App loader, it doesn't load the editing menu. I can try to edit the alarms in the alarms app on the watch, but they never go off.  

Is this in the Gadgetbridge itegrated App Loader or via a separate web browser? Which browser and operating system in the latter case?

**Comment by nxdefiant** [comment]
ok, the interface.html fails when sched.json does not exist, this is a bug.

Now the other problem:
@JAVAHTML1 Can you try to edit an alarm on the watch and after that: Does sched.json exist now?

**Comment by JAVAHTML1** [comment]
No. The file does not exist
Boot0:
[boot0.txt](https://github.com/espruino/BangleApps/files/12563533/boot0.txt)
I am using the Bangle.js Developer App Loader on Chrome Browser with MacOS Ventura.

**Comment by nxdefiant** [comment]
ok, so I assume the alarm also does not exist when you reopen the alarm app.

Can you please go to the IDE and connect to the Bangle. Then create an alarm, what appears in the IDE console?

**Comment by JAVAHTML1** [comment]
The output is: "Uncaught Error: Cannot read property 'unlockSide' of undefined
 at line 2 col 244 in lightswitch.js
...ocked();if(locked&&data.dir===w.unlockSide)Bangle.setLocked();if(...
                                   ^
in function called from system
 ____                 _
|  __|___ ___ ___ _ _|_|___ ___
|  __|_ -| . |  _| | | |   | . |
|____|___|  _|_| |___|_|_|_|___|
         |_| espruino.com
 2v18 (c) 2021 G.Williams
Uncaught Error: Cannot read property 'tapSide' of undefined
 at line 2 col 287 in lightswitch.js
...le.setLocked();if(data.dir===w.tapSide&&(w.tapOn==="always"||locked...
                                     ^
in function called from system
Uncaught Error: Cannot read property 'unlockSide' of undefined
 at line 2 col 244 in lightswitch.js
...ocked();if(locked&&data.dir===w.unlockSide)Bangle.setLocked();if(...
                                   ^
in function called from system
> 
"

**Comment by thyttan** [comment]
I wonder if doing a settings rewrite would fix your problem: Settings->Utils->Rewrite settings

**Comment by gfwilliams** [comment]
That error comes from the `lightswitch` app by the look of it, and the error is probably stopping the rest of the code from running.

Please can you try uninstalling the lightswitch app and see if that fixes it? I'm not sure in this case settings rewrite (which just updates `.boot0`) would help - boot0 looks fine to me

**Comment by bobrippling** [comment]
I believe the issue is that `lightswitch` registers a tap listener in [its boot code](https://github.com/espruino/BangleApps/blob/0b96c2f063209df9bbe8fd7fae715a17a33d3726/apps/lightswitch/boot.js#L15), and the tap listener accesses the widget's `unlockSide` and `tapSide` properties, from the two errors above.

<detail>
<summary>Errors</summary>

```
Uncaught Error: Cannot read property 'tapSide' of undefined
at line 2 col 287 in lightswitch.js
...le.setLocked();if(data.dir===w.tapSide&&(w.tapOn==="always"||locked...
^
in function called from system
```
```
Uncaught Error: Cannot read property 'unlockSide' of undefined
at line 2 col 244 in lightswitch.js
...ocked();if(locked&&data.dir===w.unlockSide)Bangle.setLocked();if(...
^
in function called from system
```

The first error (`tapSide`) is reachable if `locked` is false, since the [first `if`]() shortcircuits
</detail>

There's one odd thing though:
- `lightswitch` [initialises `w`](), so it can't be undefined
