### ISSUE TITLE
What about a README.md template for _example_

### ISSUE THREAD

**Issue by MaBecker** [espruino/BangleApps#300]
Checking existing README.md files to compile a template 

```
# <App/WidgetName>

Describe the app/widget.........

add screen shots to the app folder and link then  into this file with ![](<name>.png)

## Usage

describe how to use it 

##Features 

Name the function 

##Controls

name the key and what they are used for

## Requests 

name who should be contacted for requests


## Creator

your name 
```

This list is just a suggestion, so please name section to be added, discussed or removed.

**Comment by gfwilliams** [comment]
Sounds like a good plan. I think in a lot of cases this could be optional, but it'd be nice to have all the READMEs look kind of similar to it's easy to fine the info
