### ISSUE TITLE
gipy: Link to issues in Readme is broken

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#3010]
Original statement is:

`[https://github.com/wagnerf42/BangleApps](here)`

This results is a link "https://banglejs.com/apps/apps/gipy/here" with the text "https://github.com/wagnerf42/BangleApps" 

Please note that https://github.com/wagnerf42/BangleApps does not have issues enabled.

@wagnerf42

**Comment by nxdefiant** [comment]
And as Bangle.js app developers, do "we" actually want to have bugs reported in private repositories?

**Comment by wagnerf42** [comment]
i've enabled the issues but i think it's actually better to have them here where other people might find it.

**Comment by gfwilliams** [comment]
> i think it's actually better to have them here where other people might find it.

Yes, absolutely! I believe it is possible to format a link for a new issue such that it assigns someone to the issue if you do want to be notified of issues: https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-url-query
