### ISSUE TITLE
gipy: Please allow to disable powersaving

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#3011]
As a follow up to the discussion in #2923 I see basically two options:

1. Add a setting to disable powersaving
2. Read the global lcd settings and only execute the powersave code if the wake on twist/face up are enabled.

**Comment by nxdefiant** [comment]
@wagnerf42

**Comment by wagnerf42** [comment]
i guess i'll just add a setting to disable the powersaving.

**Comment by wagnerf42** [comment]
it's included in the incoming release

**Comment by nxdefiant** [comment]
Cool, thanks.
