### ISSUE TITLE
[kineticscroll] Only use scrolling momentum at end of touch

### ISSUE THREAD

**Issue by dustin-richards-was-here** [espruino/BangleApps#3028]
### Affected hardware version

Bangle 2

### Your firmware version

2v18

### Description
With `kineticscroll`, scrolling without lifting finger at end of scroll will result in menu continuing to scroll past stop point. 

### Expected behavior
I propose that this is more consistent with scrolling implementations on phones and the like, where scrolling action is one-to-one while finger is down and momentum is only used when finger is lifted in the middle of a scrolling motion.

**Comment by halemmerich** [comment]
Scrolling behaviour has been updated in #3296. I think that will match expectations from other touch devices a bit closer.
