### ISSUE TITLE
Adding locale.duration

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#304]
We have stuff for absolute time, distance, temperature, but I think it also makes sense to have a nicely formatted duration. For example in the stopwatch, or other apps...

* <2 minutes => `23 sec`
* <60 minutes => `1 min 23`
* `1 hr 23`

something like that?

**Comment by MaBecker** [comment]
maybe also have

* \> 24 h => `1 d  2 hr 23`

**Comment by srl295** [comment]
It would be best to make this a polyfill of the actual ecma402 functions, https://github.com/tc39/ecma402/issues/47

Actually, I'll make an issue about that general topic and see what I can do.
