### ISSUE TITLE
Banglejs and Espruino website down

### ISSUE THREAD

**Issue by Darin755** [espruino/BangleApps#3047]
I know this is likely the wrong place for this but I noticed that all of the Espruino websites are down including the forms.

Does anyone know when they will be back up? Does anyone know what is happening?

I will close this issue once they come back online

**Comment by ccchan234** [comment]
#metoo, i have sent an email to gw to noticify he/christine.

**Comment by nxdefiant** [comment]
Seems to be back

**Comment by nxdefiant** [comment]
...and down again

**Comment by Darin755** [comment]
I get the feeling that no one is in the office. I guess I'll just wait till Monday

**Comment by gfwilliams** [comment]
Hi - yes, sorry - it's fixed now. There was a server issue while I was away.
