### ISSUE TITLE
[hrmaccevents] (v0.03) crashes when calling Puck.connect

### ISSUE THREAD

**Issue by dariosalvi78** [espruino/BangleApps#3059]
### Affected hardware version

Bangle 2

### Your firmware version

2v19

### The bug

When clicking on the "Start" button in the app home page in the browser, nothing happens. Opening the JS console gives me the following:

```
Uncaught TypeError: Puck.connect is not a function
    at connect (custom.html:253:8)
```

I can see that the issue only appears on the official "app store", because in the source code, updated 5 days ago, the issue should have been solved!

Also notice that the version on the "app store" is 0.03, which is the same as on github, even though the source code is definitely different.

### Expected behavior
The watch should start streaming data to the web application.

### Steps to reproduce
Just open the hrmaccevents web application and click on Start.

**Comment by gfwilliams** [comment]
This has been fixed already in the development app loader, and should go live next time I update the main website.

There were some decent size changes so I didn't want to just put it live straight away until it had been tested for a while
