### ISSUE TITLE
Automatic translation need fixing

### ISSUE THREAD

**Issue by npalix** [espruino/BangleApps#3134]
What is the mean of "back" here ?

https://github.com/espruino/BangleApps/blob/76c6bd858fa44df743e1c310dc2970462ed2cd2c/lang/fr_FR.json#L158C12-L158C12

The automatic translation (blame message) has used "dos" which is the back of the body.

**Comment by nxdefiant** [comment]
no, back as in "go to previous menu". I think your change to "retour" is correct.

**Comment by npalix** [comment]
See 53e3675
