### ISSUE TITLE
Firmware Update fails if "Automatically reload watch after app App Loader actions" is on

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#3153]
If "Automatically reload watch after app App Loader actions" under "More..."->"Advanced Options" is turned on the firmware update is never executed. The watch just restarts without flashing the new firmware.

The firmware update works again after disabling above option and flashing another version (e.g. reflashing 2v19 before update to 2v20 succeeds).

**Comment by bobrippling** [comment]
I believe #3154 will have the fix, [deployed to my gh-pages](https://bobrippling.github.io/BangleApps/?id=fwupdate)

**Comment by nxdefiant** [comment]
nice one, thanks.
