### ISSUE TITLE
Combine myprofile and medicalinfo apps?

### ISSUE THREAD

**Issue by jt-nti** [espruino/BangleApps#3164]
I just spotted the new [My Profile app](https://github.com/espruino/BangleApps/tree/master/apps/myprofile) and it seems like a nice more generic alternative to the [Medical Information app](https://github.com/espruino/BangleApps/tree/master/apps/medicalinfo) which I've been neglecting.

Would it be ok/worth combining the two? cc @nxdefiant

**Comment by nxdefiant** [comment]
I have no argument against it, so fine with me.

Or we split only the generic height and weight from medicalinfo into myprofile and keep the more medical stuff like bloodType in medicalinfo?
