### ISSUE TITLE
[Drained] Unable to exit clock with Drained as clock

### ISSUE THREAD

**Issue by JAVAHTML1** [espruino/BangleApps#3168]
### Affected hardware version

Bangle 2

### Your firmware version

2v19

### The bug

I was attempting to change the clock, but on the small screen I accidentally set Drained has my clock. I was expecting to be able to go back to the launcher to change this, but when you attempt to exit to the launcher, it will ask if you want to restore watch to full power. No matter which option you pick, it will return to the clock, which is Drained. You therefore can't exit Drained. To reproduce this issue, install drained and set it as your clock in settings.

### Installed apps

I cannot check my apps, because drained disables BLE when running.

**Comment by thyttan** [comment]
Sorry to hear this!

If you haven't already done so, by pressing and holding the hardware button you will eventually be presented with a recovery menu.

Maybe we should not categorize this as a clock that is selectable as the default one?

**Comment by nxdefiant** [comment]
See [Bangle.js2#recovery-menu](https://www.espruino.com/Bangle.js2#recovery-menu) on how to reach recovery menu and booth without loading any code. You can use the [IDE](https://www.espruino.com/ide/) to edit/remove the setting.json to switch to another clock.

Notify @bobrippling

**Comment by bobrippling** [comment]
I've actually had this myself too when I uninstalled my main clock.

I've improved the menu so you can get to the settings straight from `drained`, and enable bluetooth too, which will enable to you upload another clock and set it up (#3170). Thanks for the feedback!

**Comment by bobrippling** [comment]
It looks like something's trying to run `setting.json` as code, when it's just a settings / json file.

What's in `.boot0`?

**Comment by nxdefiant** [comment]
I would just try settings->utils->Rewrite settings

**Comment by thyttan** [comment]
I believe you managed to connect to the Web IDE by now right? If so you can either delete or edit and save the file there.

**Comment by thyttan** [comment]
I think so, but I got unsure (that's why I deleted my comment, sorry)

**Comment by nxdefiant** [comment]
In the IDE try to execute the code
`storage.write(".boot0","eval(require('Storage').read('bootupdate.js'));");`

see https://github.com/espruino/BangleApps/blob/master/apps/setting/settings.js#L608

**Comment by bobrippling** [comment]
There's also the `"Rewrite Bootloader"` menu option which does this, if you can get to the [recovery menu](https://github.com/espruino/BangleApps/issues/3168#issuecomment-1913671591)

**Comment by bobrippling** [comment]
Glad to hear, and my pleasure - thanks for the feedback :)
