### ISSUE TITLE
fwupdate: Bootloader version not recognized

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#3172]
The firmware version is not recognized in fwupdate, only the crc is disabled:
> Your current firmware version is 2v20.27 and DFU is unknown (CRC 1418074094).

**Comment by nxdefiant** [comment]
Should https://github.com/espruino/BangleApps/blob/master/apps/fwupdate/custom.html#L99 be crcs[1] instead of crcs[2]?

**Comment by nxdefiant** [comment]
Should https://github.com/espruino/BangleApps/blob/master/apps/fwupdate/custom.html#L99 be crcs[1] instead of crcs[2]? Looks like this is only a two-element-array @gfwilliams?

**Comment by gfwilliams** [comment]
sorry - yes, looks like i messed up - I've just fixed it
