### ISSUE TITLE
[BTHome] Sents multiple events

### ISSUE THREAD

**Issue by pinq-** [espruino/BangleApps#3243]
### Affected hardware version

Bangle 2

### Your firmware version

2v21.31

### The bug

Front menu buttons trigger multiple or same event on home assistant. (in the image button 4 and button 5 are trigger)
![kuva](https://github.com/espruino/BangleApps/assets/10464992/b7a1c7da-a058-4c15-98f4-fa6255aacdc7)
reproduce:
If you first press one button in front, it only triggers one event, but if you press second button after that, it triggers both. 
Expected behavior
Every button triggers individual event. 

### Installed apps

launcer, touche keyboard, BTHome, Clock info, pebble++, Rings, Run, Scheduler, welcome.

**Comment by bobrippling** [comment]
@gfwilliams I think this is one of yours, maybe intentional behaviour?

**Comment by gfwilliams** [comment]
Thanks for the report! How long did you leave it between pressing buttons 4 and 5?

I'm just looking at the code and it seems we do cancel the button press, but only after 30 seconds of inactivity - so if you pressed a second button within that time it'd end up re-reporting both.

I've just fixed that I hope so if you update to 0.02 it should be fixed!
