### ISSUE TITLE
Blood glucose widget Xdrip has stopped displaying

### ISSUE THREAD

**Issue by tompusey** [espruino/BangleApps#3257]
Since the 0.03 update the widget no longer displays

**Comment by atjn** [comment]
Sorry about that! I caught the mistake and have a fix for it in #3214

If that PR is not merged tomorrow, I can create a separate pull request for it :)

**Comment by bobrippling** [comment]
Thanks for the report - @atjn do you know how this got past the linter? I'd expect it to pick up on `p180` not being defined

**Comment by tompusey** [comment]
Thanks for looking into this, much appreciated.

**Comment by gfwilliams** [comment]
@atjn do you have any idea why the linter would have thrown up and error and requested you to make this change? 

It would be really good to know, as if we found out we might be able to run it again before #3213 was merged and see if it broke any other apps

**Comment by atjn** [comment]
@gfwilliams the linter was complaining about the variables `r`, `x` and `y` that are defined underneath `p180`.

It was not a linting error, I made the mistake of also commenting out `p180` despite it not being necessary. I remember how I made the mistake and it required quite a few things to accidentally happen at the same time. I don't think there is any need to go into detail, but one of the unlucky accidents was that I am used to work in an environment where all `eslint:recommended` rules are enabled, and in that case the linter would have always caught this mistake. #3214 enables the rule that would have caught my mistake.

**Comment by atjn** [comment]
The good news is that this was the only bug I found (that was made by me) when going through #3214, which suggests to me that there are no other or at least only a few other bugs introduced.

**Comment by tompusey** [comment]
That's fixed it, thanks all. Being able to see my blood sugar at a glance is unbelievably helpful.

**Comment by gfwilliams** [comment]
@tompusey glad it's fixed! Nice to see the Bangle being used for something like this where it's not just a fun toy but something genuinely helpful :)

@atjn thanks! I kind of assumed you'd got the Linter to auto-fix this, rather than doing it all yourself! That's an immense amount of work, so thanks for all the time you're putting into this!

**Comment by atjn** [comment]
@gfwilliams thanks for acknowledging that, it means a lot :) Unfortunately the linter cannot auto-fix any of the rules I have enabled, so it's been a lot of work, but I am happy to help!
