### ISSUE TITLE
Deprecate currency information in `locale`

### ISSUE THREAD

**Issue by atjn** [espruino/BangleApps#3269]
The `locale` app gives the name of the currency that is most commonly used in that locale. I suggest removing that information because I don't think it is useful. If you need to show a price in a local currency, you need to know what the local currency is, but also what the conversion is between your currency and the local currency. If you don't have both, none of them is useful. To get the conversion rate, you need to connect to some online service, and if you can do that, it should be simple to also get the local currency for at given locale.

My argument that it is not useful seems to be confirmed by the fact that no apps in this repository uses the currency information.

The reason I care about this, is because in #3268 I propose that you move to use the CLDR dataset for locales, but CLDR does not provide information about which currency each locale uses. Therefore to get that information, you need to import a different dataset and I could not find any industry standard datasets like CLDR, so it is a [somewhat questionable source](https://www.npmjs.com/package/country-locale-map). If this information isn't useful anyways, I think it is best to remove it.

If you agree, I would propose that we redesign the module such that if you query the currency information, it will always return `GBP` and will log a warning that currency information is no longer supported.

**Comment by gfwilliams** [comment]
Yes, I think that's a good plan. I never really liked having currency in there anyway. The docs on locale in EspruinoDocs and the default implementation in Espruino would need changing too.
