### ISSUE TITLE
kickstarter bangle  uncaught error cannot read property "dark"

### ISSUE THREAD

**Issue by DG12** [espruino/BangleApps#3279]
### Affected hardware version

Bangle 1

### Your firmware version

2v08

### The bug

uncaught error cannot read property "dark"

Bangle 1: firmware update instructions discuss only bangle.2

### Installed apps

espruinoterm (0.01)
tilthydro (0.01)
ruuviwatch (0.05)
setting (0.70)
ios (0.16)
acmaze (0.04)
aclock (0.13)
dane_tcr (0.07)
widbt (0.04)
widbat (0.05)
boot (0.60)
launch (0.20)
mclock (0.08)
about (0.15)
widadjust (0.03)
alpinenav (0.03)
widalarm (0.02)
antonclk (0.11)
files (0.08)
bledetect (0.04)
blescan (0.01)
widid (0.03)
calculator (0.07)
mitherm (0.01)
widram (0.03)
sensortools (0.06)
coretemp (0.05)
widdevst (0.03)
fileman (0.03)
gpstime (0.05)
widgps (0.09)
widminbt (0.01)
findphone (0.04)
widver (0.03)
weather (0.26)
wid_edit (0.05)
widtbat (0.02)
thermom (0.07)

**Comment by gfwilliams** [comment]
You're on firmware 2v08 which is REALLY old - you need to update to the latest watch firmware *and* update to all the latest apps.

Ideally update the firmware and once that is done, go to the app loader and `reinstall default apps` which should give you the latest of everything
