### ISSUE TITLE
Lock event not declared in Typescript

### ISSUE THREAD

**Issue by paul-arg** [espruino/BangleApps#3289]
Hello,

I am trying to use `Bangle.on('lock', function (on, reason) {});` in a Typescript file, but the `lock` event does not seem to be declared in Typescript.

This error is raised: 

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '"lock"' is not assignable to parameter of type '"midnight"'.ts(2769)
main.d.ts(3747, 10): The last overload is declared here.
```

Might there be some more events not yet ported to Typescript?

Thanks

**Comment by gfwilliams** [comment]
I'm not sure what's wrong, because it's definitely defined in https://github.com/espruino/BangleApps/blob/master/typescript/types/main.d.ts#L3630

**Comment by paul-arg** [comment]
Ah, I think TS is not happy because I am using the arguments `on` and `reason`.
If I just call `Bangle.on("lock", function (on: boolean) {});` without `reason` the error disappears.
It looks like `reason` was not added to the TS declaration.

**Comment by gfwilliams** [comment]
Looking at it, as far as I can tell I think the `lock` typescript is automatically created, so it's just that `reason` was added semi-recently (6 months?) and the typescript decls haven't been updated since then
