### ISSUE TITLE
Sort by Favourited/Installed by default?

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#3329]
Right now, we don't sort, which results in (I guess) something alphabetical (outside of system apps which are pulled first) - eg if you search for clock faces: https://banglejs.com/apps/?c=clock

Since we only show 30 apps by default, it doesn't really seem fair that the first apps always shown are the ones beginning with numbers or 'A'.

So if we do have installations/favourite data available I reckon we should try and sort by that by default, and then at least the apps people like or have installed most get surfaced.

Any thoughts on what's better? Favourites or Installs?

**Comment by thyttan** [comment]
I'd probably go with favourites.

Another option could be some calculation involving both. But that's probably better left for later if using only one or the other feels unfair.

**Comment by halemmerich** [comment]
Maybe some sort of "Discover" tab/filter/tag would be helpful for new users. It would only contain apps not yet installed, sorted by "Favourited".

**Comment by bobrippling** [comment]
Yeah I'll chuck in a vote for favourites - I suppose that shows user intent rather than just that it's been installed
