### ISSUE TITLE
Torch app activated unintentionally by quickly moving cursor down in settings menu

### ISSUE THREAD

**Issue by lightnin** [espruino/BangleApps#342]
When quickly moving down in the settings menu with the torch app installed, the torch comes on (exiting the menu). It would be better to 1) suppress the torch when in settings or large menu driven apps, or 2) Use a combination of button presses to activate the torch that are unlikely to be used in other situations like navigating menus, or as a last resort 3) Make 4 quick presses of button 1 trigger the torch instead of button 3, since this is less likely to happen in menus that start from the top. Whereas 4 quick presses of the button that moves you down the large menu that starts from the top is something likely to happen quite often.

**Comment by gfwilliams** [comment]
Yeah, I think right now it's too difficult to try and suppress the torch app - we could detect menus but there'd only be something else where it was annoying.

I'll change it to up-down-up-down or something
