### ISSUE TITLE
[clkinfocal] Clock Info - Calendar format dd MMM shows day twice

### ISSUE THREAD

**Issue by vczb** [espruino/BangleApps#3429]
### Affected hardware version

Bangle 2

### Your firmware version

BangleJS 2 - 2v21

### The bug

![WhatsApp Image 2024-05-20 at 14 44 30](https://github.com/espruino/BangleApps/assets/51221635/f9082d0b-5885-47c7-8162-cc5b93971a68)

In the "Pebble++ Clock" with "Calendar Clockinfo," when using the format `dd MMM`, the day appears twice. First, you can see the day at the top inside the icon, then below again along with the month.

I suggest removing the day from the bottom to show just:

```
20
May
```

Another option is to add a new date format, perhaps `dd MM` (or something similar).

---

App code:

https://github.com/espruino/BangleApps/blob/master/apps/clkinfocal/clkinfo.js

---

If this issue makes sense, I would love to work on it.

Thanks a lot.

### Installed apps

- All default apps except Anton Clock
- Pebble++ Clock
- Calendar Clockinfo

**Comment by bobrippling** [comment]
Sounds good, I don't think @hughbarney you'd have any objections?

**Comment by vczb** [comment]
Since there are no objections I will start to work on it
