### ISSUE TITLE
[Run]  1st screen broken UI

### ISSUE THREAD

**Issue by kachna** [espruino/BangleApps#3623]
### Affected hardware version

Bangle 2

### Your firmware version

2v24

### The bug

When it is started the Run/Run+ (both affected) application shows blank screen with dots on left side. It looks that app is somehow working. When I push the button dots react and start changing.
![screenshot](https://github.com/user-attachments/assets/96a4b997-b51a-4829-9a24-0706108b1b47)

After swipe right I can see 2nd screen with heart monitor which looks well.
![screenshot (1)](https://github.com/user-attachments/assets/9522c7f7-0d0e-430f-99fe-b0d05bf51c61)

### Installed apps

sched (0.26), alarm (0.48), setting (0.72), boot (0.62), antonclk (0.11), about (0.15), widlock (0.08), widbat (0.12), widbt (0.09), widid (0.03), welcome (0.14), notify (0.14), health (0.30), widalarm (0.02), gpsinfo (0.13), hrm (0.13), gpstime (0.05), files (0.08), runplus (0.27), recorder (0.44), openstmap (0.30), poweroff (0.04), dtlaunch (0.25), ptlaunch (0.15)

**Comment by bobrippling** [comment]
Yeah I'd say this is related to the layout change (see #3617)

**Comment by gfwilliams** [comment]
Fixed now, sorry about that. If you re-update the run app from the development app loader it'll be fine
