### ISSUE TITLE
App sorting order in launcher

### ISSUE THREAD

**Issue by jl-cs** [espruino/BangleApps#364]
Is there a way to sort the installed apps they appear in when in the launcher?
It also might be possible to write an app for that so the sortorder could be adjusted directly on the watch or even better enhance the settings app for this. Would someone be interested in something like that, besides me?

My naive approach would be something like this:
- add a subsetting in the settings app for app sortorder
- there list all installed apps with sortorder `let jsonObj = require("Storage").readJSON("app.info", "r");`
- make sortorder adjustable (like LCD brightness) `jsonObj.sortorder = -5;`
- save changed sortorder for app `require("Storage").writeJSON("app.info", jsonObj);`

Thanks in advance for your feedback.

**Comment by gfwilliams** [comment]
Right now there's no way to specify it via UI, but as you noted there is a `sortorder` field. I think that'd be a really neat addition.

I guess the only issue is upgrading apps would likely change the sort order. To work around that I guess it could be implemented in the App Loader?

For on-watch, if you create a file called `foobar.settings.js` then the Settings menu will pick it up (under 'App/Widget Settings') so that'd be a really easy way to add the option for people if they wanted it.

**Comment by jl-cs** [comment]
Thank you for your feedback!

Could you elaborate what you mean by implementing it in the app loader? What would that change in terms of the upgrading issue?

Also, could you please point me to the part of the documentation where I can read up on the usage of the `foobar.settings.js` file? Is this a kind of plug-and-play mechanism to add a submenu in the settings-app for the sorting functionality I suggested?

Again, thanks for your feedback and also all the work you do on Espruino. You're amazing!

**Comment by gfwilliams** [comment]
Hi! 

> Could you elaborate what you mean by implementing it in the app loader?

I mean have a menu in https://banglejs.com/apps/ 

That's mean that the app loader could be aware of a change in sort order for apps, and would know to change the `sortorder` field on any new `app.info` files it uploaded.

> where I can read up on the usage of the foobar.settings.js

https://github.com/espruino/BangleApps#adding-configuration-to-the-settings-menu

> Is this a kind of plug-and-play mechanism to add a submenu in the settings-app for the sorting functionality I suggested?

Yep, that's right :)

**Comment by jl-cs** [comment]
Thanks for the quick response.

> I mean have a menu in https://banglejs.com/apps/
> 
> That's mean that the app loader could be aware of a change in sort order for apps, and would know to change the `sortorder` field on any new `app.info` files it uploaded.

Now I get what you mean, I've confused the app loader with the app launcher.

> > Is this a kind of plug-and-play mechanism to add a submenu in the settings-app for the sorting functionality I suggested?
> 
> Yep, that's right :)

Ok then this will be my starting point. Thanks again.

One last question: would a pull request to the settings app be a good idea to publish the `foobar.settings.js`-version when done or what would you propose in order to make it publicly available for the bangle.js community?

**Comment by gfwilliams** [comment]
I'd just add another 'app'. Just an entry in `apps.json` mentioning your settings.js file should do it - but if you have any troubles let me know and I can sort that bit out

**Comment by jl-cs** [comment]
Thinking about the right place for this I think it might fit better into the existing "App Manager" App [https://github.com/espruino/BangleApps/tree/master/apps/files](url)
I think I'll add a submenu there so the "Settings" app won't be clogged even more. My watch is already running near RAM max. capacity when using the "Settings" app.

**Comment by jl-cs** [comment]
I finally found the time, so please see [this pull request](https://github.com/espruino/BangleApps/pull/401)
