### ISSUE TITLE
Bug: Morphing Clock: 27:58 instead of 07:58

### ISSUE THREAD

**Issue by myxor** [espruino/BangleApps#365]
This morning i was able to see this on the Morphing Clock:

The watch was lying on the desk over night and it showed me **27:58** instead of the **07:58** which would be correct.
After holding BTN3 it switched back to the correct time.

See attached picture:

![IMG_20200430_075841](https://user-images.githubusercontent.com/1397377/80677431-230f2780-8ab9-11ea-9efa-0da89bdb5b5d.jpg)

**Comment by gfwilliams** [comment]
Interesting - thanks! Are you sure the clock firmware was up to date? There were a few changes recently that should have helped with stuff like this.

**Comment by myxor** [comment]
Ah sorry, forgot to write: i am on 2v05.439 firmware and v0.04 of the Morphing Clock.

**Comment by myxor** [comment]
The same happened again this night with the 2v05.27 firmware build.

![IMG_20200502_095646](https://user-images.githubusercontent.com/1397377/80859935-a3be5700-8c64-11ea-8aab-577706500c9d.jpg)

**Comment by gfwilliams** [comment]
Ok, thanks. Got this fixed now :)
