### ISSUE TITLE
settings.js showAppSettingsMenu() expects .info file for every settings file

### ISSUE THREAD

**Issue by nxdefiant** [espruino/BangleApps#366]
Hi,

in showAppSettingsMenu() an *.info-file is read for every *.settings file:
```
      const a=storage.readJSON(id+'.info',1);
      return {id:id,name:a.name,sortorder:a.sortorder};
```

When developing the .info-file is not yet present. While readJSON() will not throw an exception the next line will because it can not access "name" on "a" which is undefined. To avoid this situation can we provide a default value? e.g.

```
const a=storage.readJSON(id+'.info',1) || {name: id};
```

Alternative: Can we make readJSON() throw the exception? This should provide a more readable error.

**Comment by gfwilliams** [comment]
Just done - thanks! I think just carrying on regardless is the best plan - if there's an error for a non-developer user we don't want it to just silently stop working
