### ISSUE TITLE
[Bug] 'no launcher' message stays drawn under clocks that do not fully clear

### ISSUE THREAD

**Issue by Bzly** [espruino/BangleApps#386]
![screenshot (2)](https://user-images.githubusercontent.com/6991971/81161812-16d90d80-8f84-11ea-861c-901cf8309e08.png)

Bug introduced in v0.04 - https://github.com/espruino/BangleApps/commit/bf5bf91967eb37d703533ce775f57aa8b31696f8 - as far as I can tell. 

Clock digits get cleared by the no launcher message, then on interval if a digit would change, it is drawn over the top. 

Perhaps non-trivial to solve without getting the entire thing to redraw (bad). Low priority because who walks around rocking no launcher?

**Comment by gfwilliams** [comment]
Thanks - that's interesting. I guess most other clocks would have issues too, but might overwrite the whole screen. I guess I could change it so Bangle.js just displays that message for 2 seconds then reboots?

**Comment by Bzly** [comment]
Yes, you're quite right, it will and does effect all other clocks that do not entirely re-draw. I don't quite know how I missed that...

**Comment by gfwilliams** [comment]
Fixed now I think
