### ISSUE TITLE
Morph clock does not update first digit

### ISSUE THREAD

**Issue by avanc** [espruino/BangleApps#389]
I leave my watch on the bedside table at night and grab it in the morning, it does not update the first digit (2, as go went to bed ad 23:00) anymore. The other digits update (morph) correctly:
![IMG_20200507_064918215](https://user-images.githubusercontent.com/2905029/81256178-fcf50480-902f-11ea-8b2a-16122c49d0c5.jpg)

It was 6:49 at that moment.

Btn3-Longpress updates the screen correctly.

**Comment by avanc** [comment]
I just realised that there is also a glitch in the Bluetooth icon. It shows the grayed out icon correctly, and part of the blue (active) Bluetooth icon. But I'm not sure if this already happened yesterday after I disconnected the watch from charging.

**Comment by Didgeridoohan** [comment]
Wasn't this fixed a couple of days ago? Ref:
https://github.com/espruino/BangleApps/issues/365
https://github.com/espruino/BangleApps/commit/7d8d1a8f6f34d135ab9d13fa5438cdac5f8fce10

Have you updated to Morph Clock v0.05?

**Comment by avanc** [comment]
Ah, I missed that update. Sorry.
