### ISSUE TITLE
Pretokenisation breaking some apps

### ISSUE THREAD

**Issue by paulcockrell** [espruino/BangleApps#416]
I see there is pretokenisation enabled by default now in the app loader. When installing some apps this breaks them in some way.

Is there some guidance on how to modify apps to be correctly pretokenised?

In my case its the good old MarioClock that drew me to this issue.

Example output captured in IDE: 
```
Uncaught SyntaxError: Got '(' expected ':'
 at line 50 col 10
getstatus(){
         ^
```

**Comment by gfwilliams** [comment]
Thanks - that looks like something I need to fix in the pretokeniser with some urgency. It should be inserting a space between 'get' and 'status' - I think it could be a regression caused by acorn now classing 'get' as a reserved word.

Are you aware of any others that are broken?
