### ISSUE TITLE
Upload failed, TypeError: Espruino.transform is not a function

### ISSUE THREAD

**Issue by cmF3** [espruino/BangleApps#420]
After updating to **espruino_2v05.82_banglejs.zip** uploading any app to the Bangle.js via the AppLoader fails with the error message ```Upload failed, TypeError: Espruino.transform is not a function```. This makes the Bangle.js effectively unusable.

Steps to reproduce:
* Flash **espruino_2v05.82_banglejs.zip**
* Afterwards, Connect via the AppLoader
* Choose About -> Install Default Apps
* This will fails with "Unknown Error"
* The Bangle.js now contains 0 Apps
* Attempt to upload any App from the Library
* Observe error message noted above

**Comment by Didgeridoohan** [comment]
It's not 2v05.82 specific. I'm seeing the same on 2v05.73, although I haven't installed Default Apps. I just wanted to update the bootloader to v0.17.

**Comment by johanbove** [comment]
@gfwilliams I am getting the same error as OP.
"Removing all apps" works, but then the process fails with the "Espruino.transform" error.

**Comment by johanbove** [comment]
Checking _espruinotools.js_ and it seems the function "`Espruino.transform()`" is added all the way at the end of the file. This seems to make it miss being included in the final Espruino object. The function declaration looks out of place; could something have gone wrong with the compilation?

**Comment by johanbove** [comment]
This could be related to the fixes done for https://github.com/espruino/BangleApps/issues/416

**Comment by gfwilliams** [comment]
Damn, sorry - that'll teach me for pushing 'minor' changes at night. I'll get it sorted now

**Comment by gfwilliams** [comment]
Just fixed. Please can you try now?

**Comment by cmF3** [comment]
I have just tested uploading apps on the dev version of BangleApps and the issue persists.

I did not perform any firmware update or anything else.

**Comment by gfwilliams** [comment]
What about https://banglejs.com/apps/ ? Sometimes GitHub tends to cache things for a while.

**Comment by gfwilliams** [comment]
Just to add - you shouldn't need a firmware update or anything - it was purely an app loader issue

**Comment by cmF3** [comment]
"Install Default Apps" finished without error and the Bangle works again.

Is there any functional difference between the app loader on github.io and on banglejs.com?

**Comment by gfwilliams** [comment]
Phew, that's great - thanks!

> Is there any functional difference between the app loader on github.io and on banglejs.com?

The one on banglejs.com can sort by newest/recently updated, but that's it.

Supposedly the github.io one is the newest, but because I can control banglejs.com and I disable caching, if I've pushed some code change right out to both at the same time, chances are it'll hit banglejs.com first - but only by a few minutes

**Comment by johanbove** [comment]
Confirming with a quick test in the console of https://banglejs.com/apps/ that "Espruino.transform()" is back. Thank you @gfwilliams
