### ISSUE TITLE
gpx file import

### ISSUE THREAD

**Issue by fritz681** [espruino/BangleApps#435]
Can you make gpx file import?
See partial example:
![Bildschirmfoto vom 2020-05-20 15-44-42](https://user-images.githubusercontent.com/65665673/82453516-ea0f1500-9ab0-11ea-9611-8799036731b4.png)

**Comment by gfwilliams** [comment]
I guess you figured this out, but you can import KML files which are pretty similar: https://banglejs.com/apps/#route

**Comment by dapgo** [comment]
There is problem with the .KML files, and it is that most android apps manage and export .GPX. 
So having a import .GPX function would be very convenient for route viewer and . GPS recorder apps
