### ISSUE TITLE
UTF-8 characters in js files no longer converted

### ISSUE THREAD

**Issue by nebbishhacker** [espruino/BangleApps#463]
Commit https://github.com/espruino/BangleApps/commit/0c0fc9ac8f223c496d50855c04c001550173bee5 seems to have changed how non-ascii characters in js files are handled. Before, they would be interpreted as UTF-8 and converted to ISO 8859-1. Now they aren't converted at all, which means that mutlibyte UTF-8 characters are interpreted as multiple ISO 8559-1 characters.

Is this intentional?

I bring this up because I was trying to figure out why the string "turn 360° around" in the compass app was suddenly being rendered as "turn 360Ā° around"

**Comment by gfwilliams** [comment]
Oh great :/ Yes, it was intentional - images/etc would get corrupted on upload otherwise.

However I hadn't really banked on UTF-8 in code that was uploaded. I'll push a fix now that'll only do binary for stuff that isn't js/json/etc
