### ISSUE TITLE
heart: Only record every x amount of time to save battery

### ISSUE THREAD

**Issue by hasmar04** [espruino/BangleApps#467]
Instead of continuously monitoring heart rate in the heart app, allow a time frame to be specified and one record is added during each period. 
Could extend battery life and also removes repetitive data from the file.

**Comment by gfwilliams** [comment]
Thanks - yes, that sounds like a great plan. Usually no need for recording in that kind of detail

**Comment by hasmar04** [comment]
I might try and do it in my free time. Bought this watch to learn javascript, so this is probably a good way to start.

**Comment by hasmar04** [comment]
Looks like this has been implemented as part of the Health Tracking app, so closing this issue.
