### ISSUE TITLE
could not load some locale - btoa UTF8 issue

### ISSUE THREAD

**Issue by matjaz** [espruino/BangleApps#469]
I get following Error

    The string to be encoded contains characters outside of the Latin1

For exampple CZ and SI does not work.

see https://attacomsian.com/blog/javascript-base64-encode-decode

**Comment by gfwilliams** [comment]
Thanks for letting me know. I'll have a go at tweaking this. I kind of assumed when the locales were contributed they were tested, unless something has broken :/

**Comment by gfwilliams** [comment]
Wow, well that sucked.

Turns out a bunch of locales in there had never been tested and had chars that were never in the correct charset.

Should be better now though
