### ISSUE TITLE
Alarms: unable to save

### ISSUE THREAD

**Issue by pasniak** [espruino/BangleApps#506]
I tried to schedule New Alarm. I selected hour, minute, then Save and pressed BTN2 and... nothing happened at the time I entered! I first thought it's normal behaviour but the watch did not vibrate at all nor any message was displayed.

**Comment by nxdefiant** [comment]
Could it be the problem with the multiple alarm.json?

**Comment by gfwilliams** [comment]
Hi - this was fixed a month or two ago, but you'll need to update your firmware: https://www.espruino.com/Bangle.js#firmware-updates

Please can you ensure you're on up to date watch firmware? 2v06 at the moment.

Then do `About -> Install default apps` from the app loader to clear storage - and the issue should go away and no longer appear.

**Comment by pasniak** [comment]
About (btw: which unfortunately comes alphabetically before Alarms...) confirmes I have 2.06 (just flashed it). I installed default apps (so only have 5 items in BTN2 menu). Still `Save` does nothing.

**Comment by gfwilliams** [comment]
Can you try `Remove all apps` first? The `Install Default Apps` button should have done it, but maybe it failed somehow.

**Comment by pasniak** [comment]
I just did that full cleanup (so no boot) and install /9 default apps. I do `Alarms` > `New Alarm` > `Save`. Nothing else - and nothing worthwhile happens... is alarm supposed to appear in some list?

**Comment by gfwilliams** [comment]
Thanks - just tried, and I can reproduce here.

Sorry about this - it looks like the change to add 'auto-snooze' was completely untested :( 89909c07464458e665260c4251348c625fa2d5ee
