### ISSUE TITLE
GATT Failed while upgrading firmware

### ISSUE THREAD

**Issue by pasniak** [espruino/BangleApps#509]
In attempt to fix #506 I am trying to upgrade from 2.05 to 2.06. I downloaded espruino_2v06_banglejs.zip.
On watch: **DFU Start**
On Nordic app: after pressing Upload I get Uploading...
After long while on the tablet: **GATT Failed**

**Comment by pasniak** [comment]
nevermind, I was not selecting DfuTarg. You could add this: `If you see **GATT Failed** message make sure you selected DfuTarg NOY banglle.js as device`

**Comment by gfwilliams** [comment]
Thanks. Actually I just had another report about this as well. You followed the instructions here?

https://www.espruino.com/Bangle.js#firmware-updates

I think realistically some photos/videos would help.

**Comment by pasniak** [comment]
Too late it worked for me - maybe next time.

**Comment by pasniak** [comment]
2.06 seems less stable as far as GPS (I get "Searching for GPS time" followed by black screen + no button response).  Are there any release notes?

**Comment by gfwilliams** [comment]
http://www.espruino.com/ChangeLog and http://forum.espruino.com/conversations/349172/newest/ ?

Worth making sure all your JS firmware is up to date first...

**Comment by pasniak** [comment]
![IMG_20200623_091138_2](https://user-images.githubusercontent.com/19778666/85408169-b2820580-b553-11ea-8683-470bd01b616f.jpg) is that the symptom? Could you please point me to the doc? (and maybe add link under firmware install?)

**Comment by pasniak** [comment]
All apps were reinstalled yesterday as I flashed Espruino v2.06. In About:
Version 2v06
Commit 21168a2b
Bootloader v0.19
Launcher v0.03
Settings v0.20

**Comment by gfwilliams** [comment]
Looks like you have the numerals clock installed? If you just install another clock it'll be fine.

Try installing default apps and work from there.

Honestly, looking at the code of numerals clock with the error, it's not nice at all. While it seems it should work, it just feels like it'd break at some point. I'll change it and it should update.

**Comment by pasniak** [comment]
That worked. You could include version on which apps were tested, like Android does.

**Comment by gfwilliams** [comment]
> You could include version on which apps were tested, like Android does.

Not sure I understand... 'Install default apps' should be the set of apps that are tested for each release?

Unfortunately it's not really feasible to test every app for each release unless I can come up with some magic Bangle.js + webcam thing.

**Comment by pasniak** [comment]
Couldn't apps be automatically tested on the emulator? The clocks at least.
