### ISSUE TITLE
[speedo] miles instead of km ?

### ISSUE THREAD

**Issue by chrisvel** [espruino/BangleApps#51]
I opened speedo in my car and saw **66** while I was almost going with ~**110**km/h. 

I took a look and couldn't find something related in the code except that there is no "special" calculations in `speedo.js` but I can quickly multiply with `1.60934` (is 1km)  If that's the case.

**Comment by gfwilliams** [comment]
Argh - thanks! I just looked into this and I was wrong about the data coming from the GPS receiver - it's in knots, not km/h. I've just fixed this on the firmware side so new firmware builds from http://www.espruino.com/binaries/travis/master/ should have it fixed!

**Comment by chrisvel** [comment]
@gfwilliams After flashing firmware http://www.espruino.com/binaries/travis/master/espruino_2v04_banglejs.zip I can't get GPS to work, it just stays in `0 satellites` forever. 
Any ideas? Might be unrelated? 
I also tried pressing BTN1 + BTN2 to reset it but there was no change.

**Comment by gfwilliams** [comment]
Can you just try leaving it outside for a bit with a GPS app running? Sometimes it can take a few minutes to get a lock if it hasn't been used for a while (or the battery ran down between times) - Smartphones can be a lot faster at getting a lock because they can ask the cell towers for time & position info to get them started.

**Comment by chrisvel** [comment]
You are right but it took 5 minutes. At first dates it was taking no more than 1-2 minutes. I know cloudy weather can slow down the lock but can something else be happening or it's just my idea?

**Comment by gfwilliams** [comment]
I bet if you try again now it'll be substantially faster?

Was the last time you tried it in Ireland? If so the GPS may have been working from the assumption you were somewhere else, which would have really slowed down the process of getting a lock.

**Comment by chrisvel** [comment]
Indeed, in Ireland the lock succeeded sometimes in 1'. I have no idea why, but this is a question for some other place. Thanks.
