### ISSUE TITLE
New app: GPS settings

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#515]
The UBlox GPS is actually pretty configurable. There is an example of sending commands to it in the 'testing' folder but we should expand this and make it into an app - allow:

* Low power mode
* Set GPS time from clock
* Choose GPS/GLONASS/Beidu
* AGPS
* what GPS data gets reported
* GPS report speed
* Anything else from the datasheet?

**Comment by jl-cs** [comment]
What about [Galileo](https://en.wikipedia.org/wiki/Galileo_(satellite_navigation))?

**Comment by gfwilliams** [comment]
If the GPS receiver does it (which looks promising), it could be enabled: https://www.u-blox.com/sites/default/files/products/documents/u-blox8-M8_ReceiverDescrProtSpec_%28UBX-13003221%29_Public.pdf 

However it might be on by default

**Comment by gfwilliams** [comment]
Fixed with @hughbarney's great work
