### ISSUE TITLE
verticalface shows hour 61 

### ISSUE THREAD

**Issue by pasniak** [espruino/BangleApps#516]
verticalface should have space if 1 digit hour is displayed, otherwise previous 2-digit hours digit is displayed (I saw 61) 

For example in https://github.com/espruino/BangleApps/blob/76b51f50747541ca0f12896cc5368adf8c3989ac/apps/verticalface/app.js#L11 could be (untested!)

```
var hours = (" "+h).substr(-2);
```

**Comment by gfwilliams** [comment]
Thanks! Just fixed
