### ISSUE TITLE
Timer app locks vibration on if BTN1 is pressed while vibrating

### ISSUE THREAD

**Issue by NateEag** [espruino/BangleApps#521]
With version 0.04 of the [simpletimer](https://github.com/espruino/BangleApps/tree/master/apps/simpletimer) app, start the app.

Create a one-second timer.

Once it goes off, while the watch is vibrating, press BTN1 (labeled `(re)start`).

The vibration will now continue until you long-press BTN3 to return to the home screen.

**Comment by NateEag** [comment]
Working flawlessly now.

Thanks for the fix!

**Comment by gfwilliams** [comment]
No problem - glad it's sorted :)
