### ISSUE TITLE
BangleRun distance doesn't go above 9.99km

### ISSUE THREAD

**Issue by pruperting** [espruino/BangleApps#529]
Hi - just used my Bangle.js for the first time and the BangleRun app. It worked great, but I noticed that once I had run more than 10km, the distance field reverted back to showing 0.XX. I ended up running 10.37km, but the distance display showed 0.37.

I guess its the BangleRun's equivalent of the y2k bug, but we could call it the d10k bug.

**Comment by gfwilliams** [comment]
Thanks! That'll be fixed in the next update
