### ISSUE TITLE
espruinoctrl errors

### ISSUE THREAD

**Issue by pasniak** [espruino/BangleApps#545]
With Bangle next to Puck (and address : Sometimes I get the LED blink, sometimes I get Error: Disconnected just after; waiting a bit clears the problem. Could it be low timeout value?

Kind of works intermittently up to 2m.

**Comment by gfwilliams** [comment]
Honestly, I think this is just a signal strength issue.

On Puck.js you can do `NRF.setTxPower(4)` to boost the signal strength (by default it's not full to help save on battery usage)
