### ISSUE TITLE
What is red "CALLBACK" message above lower edge?

### ISSUE THREAD

**Issue by phiL0co** [espruino/BangleApps#547]
Can anybody tell me what a red message saying CALLBACK means?
It appears under the watchface. 
I noticed that for instance the chrono widget timer stops if this message appears.
The message disappears after refreshing the screen.

**Comment by gfwilliams** [comment]
It's a warning from the watch itself to say that the JavaScript app/widget code caused an error that wasn't handled.

If you could find a way to reliably reproduce this (and what widgets are installed/app running at the time) then we could probably track down what the problem is - but it's basically impossible to track down without that.

**Comment by phiL0co** [comment]
OK, Thx Gordon!
I think it has to do with gadgetbridge disconnects.
I'll try to narrow it down!

**Comment by Didgeridoohan** [comment]
I see this message one in a while as well... Will try to get some troubleshooting in to narrow it down.

**Comment by kuleszdl** [comment]
I have seen this message as well. I am running with firmware 2v08 and the following apps:

- About
- Active Pedometer
- Alarms
- App Manager
- BangleRun
- BatteryWidget
- Bootloader
- Gadgetbridge
- Launcher
- Morph Clock+
- Notifications
- Welcome

@phiL0co @Didgeridoohan Maybe you could compare this list of apps to yours so we could narrow down the list of apps that might be causing this?

**Comment by gfwilliams** [comment]
Thanks - if the error happens over a wide variety of apps it might be worth checking Widgets first - since they will run in the background for a bunch of apps, so one widget might cause the message to appear in many different apps.
