### ISSUE TITLE
[Bug] /x10 is missing from gadgetbridge string lookup in .boot0

### ISSUE THREAD

**Issue by enaon** [espruino/BangleApps#558]
I am not sure it this is a mistake or there is something I am doing wrong, I was playing with your code on my p8, and it seems that this code from here:
https://github.com/espruino/BangleApps/blob/master/apps/boot/boot0.js
is not working.
```
  Bluetooth.on('line',function(l) {
    if (l.startsWith('GB({') && l.endsWith('})') && global.GB)
      try { global.GB(JSON.parse(l.slice(3,-1))); } catch(e) {}
  });
```
this line:
 if (l.startsWith('GB({') 
needs a leading /x10 to work in the p8, just wanted to report it in case I am not mistaken.

**Comment by gfwilliams** [comment]
Thanks! Yes, you're correct - that needs changing.
