### ISSUE TITLE
findphone

### ISSUE THREAD

**Issue by dapgo** [espruino/BangleApps#565]
Find Phone 0.01
GadgetBridge 0.47.1
"Firmware" v2.05

GB/Phone doesn't ring or do anything 

Steps to reproduce:
    Install "Findphone"
    Enable HID:  kbrd&media
    Connect GadgetBridge
    Open "Findphone" on Bangle.js
    ( Bangle.js get unresponsive)

By the way the opposite direction function (GB: Find lost device) works fine.

**Comment by gfwilliams** [comment]
Thanks.

Looking at it the app said you needed HID when there was no reason for it whatsoever. There was also no way to cancel the find phone message either and the screen never updated. Should have fixed it now.

Also worth noting you don't need the app. You can do Settings -> App Settings -> GadgetBridge -> find phone
