### ISSUE TITLE
verticalface - Vertical watch face and GB notifications

### ISSUE THREAD

**Issue by dapgo** [espruino/BangleApps#567]
App: Vertical watch face v0.05
FW: 2v07 (also in 2v05)
When I am on my prefer watchface/clock, GB notifications are not received on the bangle.js
However, using round clock or analog clock i receive them.
Is this watchface incompatible?

Another way to test is with the Gadgetbridge "Find Lost device"

**Comment by detached** [comment]
I think the problem is that verticalface doesn't call `Bangle.loadWidgets();`.

**Comment by gfwilliams** [comment]
Yes - unfortunately there's not enough space left in the vertical clock watch face for the widgets. It seems like a conscious decision of the clock designer.

I guess it could be moved around a little to make room though?

**Comment by gfwilliams** [comment]
Just added widgets to the face - it'll be in the dev version of the app loader now
