### ISSUE TITLE
bangleRun - store session and logo

### ISSUE THREAD

**Issue by dapgo** [espruino/BangleApps#572]
An historic of sessions would be an amazing feature. But if it is too much demanding, at least banglerun should store the last session data until you overwrite with anew session.

Other "issue/feature" is logo color, as it is black as the screen background. 
In the Launcher (Default) the logo will be displayed only when you select it. 
However, using Touch Launcher the logo will never be displayed 

[Example of a converted and color img file, remove .txt and upload](url
[banglerun.img.txt](https://github.com/espruino/BangleApps/files/5311371/banglerun.img.txt)
)

**Comment by gfwilliams** [comment]
Thanks! This is fixed now - logo is fixed, and there's an 'interface' in the App Loader where you can view/delete past exercises and download them to Strava-compatible files
