### ISSUE TITLE
Gesture demo app problem

### ISSUE THREAD

**Issue by Sblash** [espruino/BangleApps#573]
Hi all
I'm trying the code of this app, and i get some errors in the console when i try to do some gestures..

this when the watch notice a gesture but don't recognise
`Uncaught Error: Didn't find op for builtin opcode 'QUANTIZE' version '1'`

and after some attempts, i get this error
`Uncaught Error: Unable to allocate enough RAM for TensorFlow`

the code i'm using is the same of the app:
```
Bangle.on('aiGesture',(gesture)=>{
  E.showMessage(gesture?gesture:"Unknown");
  setTimeout(()=>g.clear(), 2000);
});
E.showMessage("Wave your hands\nto detect\na gesture","Gesture Test");
```

**Comment by gfwilliams** [comment]
Hi,

what firmware are you using? 2v07 had an issue but the latest builds actually have this fixed: https://github.com/espruino/Espruino/issues/1936

I'll likely release a 2v08 build some time this week
