### ISSUE TITLE
Line break is broken when erasing apps

### ISSUE THREAD

**Issue by Fscked-In-The-Head** [espruino/BangleApps#593]
When erasing apps through the app loader, \n is displayed as text instead of being rendered as a line break. Installing doesn't have the same issue.
I assume this is a quick fix, but couldn't find the relevant section to modify. I'm still learning my way around the codebase here. Example pictures below.
![image](https://user-images.githubusercontent.com/13549095/99158762-349dd280-268b-11eb-81b2-0098140bba92.png)
![image](https://user-images.githubusercontent.com/13549095/99158806-c4dc1780-268b-11eb-811f-342bca87307c.png)

**Comment by gfwilliams** [comment]
Wow, thanks! I'd noticed the issue in the upload and fixed it - didn't see it for erase :)

Just fixed.
