### ISSUE TITLE
Battery threshold setting in widbatwarn does not update correctly

### ISSUE THREAD

**Issue by Fscked-In-The-Head** [espruino/BangleApps#597]
When changing the low battery threshold setting for widbatwarn, the battery percentage does not update when BTN1 or BTN3 are pressed. The value does change as intended, but the screen does not update to reflect that until BTN2 is pressed to confirm the setting.

**Comment by rigrig** [comment]
This widget doesn't draw anything to the screen, what do you expect to happen?
