### ISSUE TITLE
Idea: "Return to Default App" function

### ISSUE THREAD

**Issue by OhMeadhbh** [espruino/BangleApps#617]
I realize there are only a few buttons available, and I like that watch seems to retain state after turning the screen on after it blanks. But in order to get back to the Vertical Face app when the device resets, I have to scroll to the bottom of the list of apps. Maybe if pressing buttons 2 & 3 simultaneously brought up a "Default App" you could quickly return to your favourite clock.

Also. It would be cool if there was a way to store the preferences between reboots so it wouldn't keep resetting my "select clock" preference.

**Comment by gfwilliams** [comment]
Hi - I'm pretty sure this exists.

If you go to `Settings`, then `Select Clock`, you can choose the default clock you want to appear when you long-press BTN3 or when the Bangle starts up from a cold boot.
