### ISSUE TITLE
Can't connect to Bangle.js when feature HID is set to ON

### ISSUE THREAD

**Issue by sebi5361** [espruino/BangleApps#62]
On my watch I have noticed that if I set `HID` to `ON` under _settings_, I am unable to connect to the watch (after a reboot) using Web Bluetooth: I get the **Connection Failed** error message in the Web IDE (whereas I can connect to it in all other situations).

**Comment by gfwilliams** [comment]
Which OS? Did you try on any that work? I think Android is ok?

Chances are you hit https://github.com/espruino/Espruino/issues/1701

**Comment by sebi5361** [comment]
Indeed same issue with same OS (Windows 10).
