### ISSUE TITLE
How to ease development/preview in emulator

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#63]
The bootloader currently defines 'drawWidgets' and this means that if you just do a direct upload to the watch (or run something in the emulator) it's not there and causes an error. There may be more things in the future where this is an issue.

Maybe Bangle.js should just define those variables internally at boot time? That does obviously make stuff a bit less flexible though

**Comment by sebi5361** [comment]
> Maybe Bangle.js should just define those variables internally at boot time?

This might be a good option to avoid having to encapsulate the `drawWidgets` function into a try block `try { drawWidgets(); } catch(err) {}`

**Comment by gfwilliams** [comment]
Done now
