### ISSUE TITLE
BangleRun shows I ran NaN KM

### ISSUE THREAD

**Issue by Shashank-Prasanna** [espruino/BangleApps#637]
So, I went running today, and BangleRun(with a GPS fix) showed I ran an incredible...unbelievable...NaN kilometers! But seriously, that's an issue. Also, there was no pace showing up.

**Comment by gfwilliams** [comment]
Ouch - thanks! @singintime ?

**Comment by Shashank-Prasanna** [comment]
So this can be closed with the new version, I guess
