### ISSUE TITLE
Allow non-integer timezones

### ISSUE THREAD

**Issue by ryzokuken** [espruino/BangleApps#68]
Hello! 👋 

I just got my Bangle.js from NodeConf EU this morning and started playing around with it. Apparently, it's not possible to set non-integer time-zones on the thing (I'm currently in UTC+5:30 and it became quite evident that this hasn't been addressed yet).

I thought changing the step size from 1 to 0.5 here (https://github.com/espruino/BangleApps/blob/master/apps/setting/settings.js#L101) will work, but maybe there's more nuance to it than that.

**Comment by gfwilliams** [comment]
Thanks! Yes, changing the step should fix it. I'm away at the moment but if you add a pr I'm happy to merge it

**Comment by MaBecker** [comment]
@ryzokuken, check this line too

https://github.com/espruino/BangleApps/blob/d306209da77cfc7c706f26054d59baaa422aff77/apps/setting/settings.js#L103

**Comment by ryzokuken** [comment]
@MaBecker Yeah, I guess I'll just remove it.
