### ISSUE TITLE
Geiss Clock not finishing precomputing

### ISSUE THREAD

**Issue by v1nc** [espruino/BangleApps#692]
Precomputing does not finish for me. I restarted it a few times, even after 10 minutes there were zero palettes calculated.

Does the app need a cutting edge build? I am using release 2v08.

I also noticed that if I reboot the device in this state, the clock does not start precomputing anymore, and instead shows an `uncaught reference error: "pal" is not defined`. The buttons do not start the app launcher anymore in this state.

**Comment by gfwilliams** [comment]
Could you start the Web IDE and connect it, then start the clock so it does its precomputing and see if anything is written to the console? Hopefully it'll show you some kind of error.

I've got a 2v08 watch running it fine here, so I wonder if maybe it's that you don't have enough free storage or something like that?

**Comment by v1nc** [comment]
I reset the device, now it works.
Sorry that I didnt check it with the console :s
