### ISSUE TITLE
GPS Widget and HRM Widget stopped the clock loading correcly

### ISSUE THREAD

**Issue by PHDPeter** [espruino/BangleApps#693]
Just a quick bug I found where my bangles clock would not load correctly with either of the apps loaded.
Some times it would load (but the bt 2 push would then not work for the launcher) but most of the time is just loaded a black screen where the clock should be. Widgets were still there but the launcher for apps would not load from the push of bt 2.
Have not looked at the code but thinking that it might just be messing with the running of the clocks as that would explain the bt 2 not working?

**Comment by PHDPeter** [comment]
I was using on the 2v08 of the firmware, did not test with any other firmware,

**Comment by gfwilliams** [comment]
Ahh - yeah, the widgets both say `Requires firmware v2.08.167 or later`

Obviously it'd be nice if they didn't totally break everything on older firmwares though! I've just pushed a fix and will get this into the official BangleApps soon

**Comment by PHDPeter** [comment]
Aww that's ok then :-) thanks
