### ISSUE TITLE
a centralized widget configuration

### ISSUE THREAD

**Issue by dapgo** [espruino/BangleApps#700]
I think that it would be great to have a function to administer every widget installed.

Functions can be: widget area (top, down), sort order, hide/show, enable/disable..

I suppose it can  be also a fork of "App Manager" but focused in widgets

On the other hand, on [README.md#graphic-areas](https://github.com/espruino/BangleApps/blob/4c78076603b36bcccff102ca2989c5ad82b8924b/README.md#graphic-areas) there is no reference to bottom widget area

**Comment by gfwilliams** [comment]
I'll update the graphic areas bit - but yes, an app manager would be pretty neat.

I think there was a discussion on the forum about it, but it should be pretty easy to do something. The app could add a `widgetconf.boot.js` file that overwrite `Bangle.loadWidgets` with a file that loaded widgets but then overwrite the `area` element and also re-ordered them as required.

**Comment by gfwilliams** [comment]
Fixed with https://banglejs.com/apps/#wid_edit
