### ISSUE TITLE
Accessing Alarms from a other Apps 

### ISSUE THREAD

**Issue by PHDPeter** [espruino/BangleApps#703]
Hi
working on a clock face that shows the time till the next alarm.
I looked at the default alarm app and think that the alarms are stored in the "alarm.json" file so I should be able to use thou alarms in a different app correct?
I.e.
`var alarms = require("Storage").readJSON("alarm.json",1)||[];`
should give me the alarms to work with right?

**Comment by gfwilliams** [comment]
Yes - that should be absolutely fine!

**Comment by PHDPeter** [comment]
Thanks
