### ISSUE TITLE
Route viewer colors

### ISSUE THREAD

**Issue by pglez82** [espruino/BangleApps#710]
Hi. I was checking the route viewer app. I uploaded a kml and the app works well. The only thing is that I think it is quite impossible to read it in the outdoors when there is some sun light. This is due to the red colour used. I think changing it to green or some other more visible colour will help`a lot. Does this happen to anyone else?

Pablo

**Comment by gfwilliams** [comment]
This sounds like a good plan - what do you think is best? Green, or maybe yellow (this should be even brighter since it's red+green)
