### ISSUE TITLE
12/24 hour setting

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#76]
As mentioned at https://github.com/espruino/BangleApps/pull/70

Should we add a global setting for the time format used in clock faces, and ask that all clock faces read the setting and change accordingly?

Or does it just make sense to have a different clock app for each time format?

**Comment by MaBecker** [comment]
> Or does it just make sense to have a different clock app for each time format?

What about a clock app with html config page to set time and date format to use.

**Comment by avanc** [comment]
I would prefer a global setting. If a watch face can handle both, 12/24, it can read the variable. If not, it just ignores it.
