### ISSUE TITLE
Bangle2 (SMA Q3) issue: Uncaught Error: ERR 0x12 (CONN_COUNT)

### ISSUE THREAD

**Issue by yngv27** [espruino/BangleApps#785]
I get this when I just send anything from the IDE right side to B2. Doesn't seem to have an ill effect, code seems fine.

**Comment by gfwilliams** [comment]
I hit this once or twice too - but I haven't had it recently.

Any clues how to reproduce?

**Comment by yngv27** [comment]
It's not happening today... happened every time yesterday. I'll close and re-open if I can regularly reproduce it.

**Comment by gfwilliams** [comment]
Thanks! I wonder whether if it's been running for some time... I'll see about making the error message give a line number, so at least if it does happen again we can figure out where it is
