### ISSUE TITLE
The .info files should contain the tags from apps.json

### ISSUE THREAD

**Issue by TheGLander** [espruino/BangleApps#788]
This could mean that launchers could sort apps by category, which could be a nice QoL thing, but I also think it can be useful due to the `b2` tag, since there are cases where it's very useful to know if an app is made for Bangle.js 2 or not, for example, I am writing a utility app of sorts, which automatically rescales `Graphics` calls to port Bangle.js 1 apps to 2 apps automatically, but since there's no way to identify B2 apps, there's no way to know if an app should be rescaled or not.

**Comment by gfwilliams** [comment]
Hi - yes, that seems like it could be quite handy - I've just added it...

For the app rescaling thing, I did already try this in the firmware, as well as 'faking' buttons 1/2/3 using the right-hand edge of the screen:

https://github.com/espruino/Espruino/commit/636c4ec0c053b636ec657ea0c662b775ac2cb0c0

I actually ended up pulling the changes back out again though, as it just felt like even with that, the vast majority of apps weren't usable, and it was better not even to pretend :(
