### ISSUE TITLE
Installing Gadgetbridge first time fails

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#792]
It installs notifications (which Gadgetbridge needs) but then fails to automatically install Gadgetbridge afterwards

**Comment by dapgo** [comment]
Few days ago I updated to last version the 2 notifications apps, gadgetbridge widget 0.23,  and also I did a clean install of fdroid Gadgetbridge (v0.59.1)

From Android gadgetbridge I can't find the bangle.js watch but GB must be working fine as it can find another espruino device  with the name "Espruino-devmode"

FW BANGLEJS, 2v09
