### ISSUE TITLE
Recipe app?

### ISSUE THREAD

**Issue by gfwilliams** [espruino/BangleApps#795]
Looks like there's a free recipe database at: https://www.themealdb.com/api.php

It'd be great to be able to store recipes on Bangle.js such that you could just step through each step one by one. Ideally with the quantities included for each step, but this doesn't seem to be handled by the API

**Comment by bobrippling** [comment]
I reckon we can close this issue off - there's now a newly introduced recipe app (#795) with the potential to iterate further

**Comment by gfwilliams** [comment]
Sounds great - thanks! Link to app at https://espruino.github.io/BangleApps/?id=followtherecipe
