### ISSUE TITLE
Heart rate monitor turns off with LCD

### ISSUE THREAD

**Issue by feldim2425** [espruino/BangleApps#799]
This "bug" occurs when "Simple Heart Rate widget" is installed. 
It turns off the heart rate monitor whenever the LCD turns off, however this is not practical when "Heart Rate Recorder" is running. 

I know this is not strictly a bug since the widget should turn off the sensor, however with the recorder this leads to bad readings. One option would be to give the "Heart Rate Recorder" application a option to show the heart rate similar to "Simple Heart Rate widget" so it can be fully replaced.

**Comment by gfwilliams** [comment]
Thanks! Actually yes, this is totally possible to change since in 2v09 (I think) I added the ability for apps to request the HRM to stay on just for them. I'll get some changes in to fix this in the next few minutes.
