### ISSUE TITLE
Layout: `pad` can cause text to get cut off

### ISSUE THREAD

**Issue by nebbishhacker** [espruino/BangleApps#819]
```
const Layout = require("Layout");
g.clear();
var layout = new Layout({type:"v", fillx: true, c: [
  {type: "txt", font: "10%", halign:1, pad: 20, label: "0123456789"},
]});
layout.render();
layout.debug();
```

Expected result:

![screenshot (17)](https://user-images.githubusercontent.com/2780794/134425340-604b75a1-b0f2-4597-9f11-b8787d06ecd4.png)

Actual result:

![screenshot (18)](https://user-images.githubusercontent.com/2780794/134425378-7ffb5e3e-616f-41a2-8655-2feb4f8e0ebd.png)

**Comment by gfwilliams** [comment]
Thanks! That's interesting. I thought pad got added to the required width, but maybe not... I'm starting to wonder if it's worth implementing a test harness now (JS + expected output). It might also serve as a useful reference.

**Comment by nebbishhacker** [comment]
Here's another test case that still exhibits issues.

```
const Layout = require("Layout");

g.clear();
var layout = new Layout({type: "v", c: [
  {type: "h", pad: 20, c: [
    {type: "txt", font: "10%", label: "abcd"},
    {fillx: 1},
    {type: "txt", font: "10%", label: "1234"},
  ]},
]});
layout.render();
layout.debug();
```

Expected:

![screenshot (22)](https://user-images.githubusercontent.com/2780794/134552241-37125beb-0f0d-45b8-837e-756ad1c1e0fc.png)

Actual:

![screenshot (21)](https://user-images.githubusercontent.com/2780794/134551911-8ffcc35b-4022-42d9-a118-79e371d3c8d4.png)
