### ISSUE TITLE
cliock: Not registering BTN1 presses reliably

### ISSUE THREAD

**Issue by hasmar04** [espruino/BangleApps#853]
Button functionality has been added to select settings and navigate menus, but neither on the physical watch (Bangle.js 1), with multiple other apps installed, or in the emulator (bangle.js 1) with no other apps does BTN1 register presses. 
Through the debugging output in the emulator, it can be seen the buttons are processing as pressed but not creating the expected response. 

Although weirdly it does work with the Bangle.js 2 emulator, if that helps at all, with all the correct button presses being processed as expected. 

If it helps, I am using Firefox on Manjaro Linux.

**Comment by gfwilliams** [comment]
Thanks - just fixed I hope!

**Comment by hasmar04** [comment]
So just confirming for future reference, the buttons are in the range -1, 0, and 1? And does this still work on B.js 2?

**Comment by hasmar04** [comment]
Just checked in the emulator, and B.js 1 works is fixed, while B.js 2 seems to be broken now, with only the virtual BTN3 working, and BTN2 (the top virtual button) being registered, but not working as intended. 
As I don't have the actual hardware yet, I cannot test if it is an emulator or app issue or both.
