### ISSUE TITLE
[BangleJS 2] Q Alarm and Timer does not have a logo when used with touch launcher

### ISSUE THREAD

**Issue by Aracnoss** [espruino/BangleApps#897]
When using the touch launcher, the bell icon used in the BangleJSApps page (for the Q alarm and timer) does not appear in the launcher. Instead replaced with Random symbols usually 2 X's with an underlined cube in between.

**Comment by gfwilliams** [comment]
@qucchia any ideas?

**Comment by gfwilliams** [comment]
Fixed this one now - looks like the icon was broken
