### ISSUE TITLE
[BangleJS 2] Notifications don't appear to be cleared.

### ISSUE THREAD

**Issue by Aracnoss** [espruino/BangleApps#898]
Not sure if this is an issue with Gadgetbridge or BangleJS 2, but notifications on watch don't appear to ever be cleared.

And given they seem to be ordered from top oldest to bottom newest in the menu, that's going to become more of an issue the more notifications that don't get removed.

**Comment by gfwilliams** [comment]
This is using the `Gadgetbridge` app on Bangle.js 2, or the `Android` one I guess?

Maybe the `notify-` event isn't being handled properly? I think there's also an argument that all notifications should be cleared when Gadgetbridge/iOS disconnects. iOS definitely re-sends them at startup.

Also, feel free to report issues, but this is the 3rd one in 30 minutes - given the load I'm currently under with shipping I can't respond to everything so unless someone else wants to jump on these, most will have to wait until the remaining Bangles are out the door.

**Comment by Aracnoss** [comment]
@gfwilliams The setup is Gadgetbridge on phone, gadgetbridge and message (with or without the android app) on the BangleJS 2.

No worries, I just like to report them before I forget myself, no rush at all. I might even take a look myself if I get some free time this weekend since I know C/JS, but not sure how likely that'll be.

**Comment by gfwilliams** [comment]
Ok, thanks! I believe the 'messages' app won't actually do anything useful without the Android/iOS apps installed - so that could be causing some issues I guess? But I'll look into it here when I get a moment.

**Comment by gfwilliams** [comment]
Notifications now get cleared on disconnect, so I think that's ok - but good point about message ordering - I'll tweak that
