### ISSUE TITLE
[Feature request] messages app

### ISSUE THREAD

**Issue by Didgeridoohan** [espruino/BangleApps#909]
On my Bangle.js 2 (haven't tested on the v1) I've been experiencing that notifications aren't always cleared from the Messages app when they're cleared from the phone (this might be related to #898, although on my device most notifications clear as expected in the Messages app). Can't currently pinpoint why this happens, but it would be nice to be able manually remove notifications from the Messages app.

Edit: Another thing I've noticed is that if you clear a notification on the phone, the notification is removed on the watch but the Messages app is displayed. It would be nice if it went directly to the clock instead.

Edit 2: I'd love to be able to change notification settings to change the duration of the buzz and the number of buzzes. The vibration motor is rather weak, so I find it easy to miss. Longer and/or more buzzes in a row might make it easier to detect.

Using Bangle.js 2, 2v10.224, Android integration v0.01 and the Messages app v0.03.

**Comment by Didgeridoohan** [comment]
Apart from this being a feature request, it might be related to #898, although on my device most notifications do clear in the Messages app.

**Comment by johan-m-o** [comment]
@gfwilliams Updating to Android integration v0.0.2 and Messages v0.04 removed all those old notifications I had laying around. Nice!

Can also confirm that music controls now work too.

**Comment by gfwilliams** [comment]
Great! Hopefully I'll get a few more tweaks in soon too.
