### ISSUE TITLE
distance should use SI based units

### ISSUE THREAD

**Issue by MaBecker** [espruino/BangleApps#93]
Using kilometer cause unreadable menu entry because of too much chars.

kilometer: km
miles: mi

**Comment by gfwilliams** [comment]
thanks - that's a pain, I thought I'd fixed that.

I reckon 'mile' will be ok though? Probably less confusing than 'mi'

**Comment by MaBecker** [comment]
Just tested, should distance unit match with distance?

```
>console.log(require('Storage').read("@setting").split(','))
[
  "{\"ble\":true",
  "\"dev\":true",
  "\"timeout\":10",
  "\"vibrate\":true",
  "\"beep\":true",
  "\"timezone\":0",
  "\"HID\":false",
  "\"clock\":null",
  "\"12hour\":false",
  "\"distance\":\"kilometer\"",
  "\"distanceunit\":\"mile\"}"
 ]
=undefined
> 
```

**Comment by gfwilliams** [comment]
Wow, I must have been having a bad day - it shouldn't be creating `distanceunit` at all, just `distance`.

**Comment by MaBecker** [comment]
Just updated, can you please switch kilometer to km.

![IMG_9797](https://user-images.githubusercontent.com/15932646/74167778-06d1bc00-4c29-11ea-825d-aebc238f2c53.jpg)

**Comment by gfwilliams** [comment]
It's already done (https://github.com/espruino/BangleApps/commit/3eb5d152672ebbcdab77a30a785edfb6907587bd), it's just that banglejs.com/apps wasn't up to date with GitHub yet.

Just updated banglejs.com/apps so if you try now it's fine
