### ISSUE TITLE
[BangleJS 2] Heartrate sensor turns on even though it should be disabled

### ISSUE THREAD

**Issue by Izaic** [espruino/BangleApps#940]
On version 2v10.226 I encounter an issue on my BangleJS 2 where the heartrate sensor turns on despite being set to Off in the health settings app.

**Comment by Izaic** [comment]
It seems that the Gadgetbridge app turns it on even if the system settings has it turned off.

**Comment by gfwilliams** [comment]
Hi - yes, however it looks like the HRM isn't on by default - so I think it must be Gadgetbridge requesting it...
