### ISSUE TITLE
Touch Launcher does not show some icons right on low resolution and high resolution it flickers when animating.[Bangle 1]

### ISSUE THREAD

**Issue by Ronin0000** [espruino/BangleApps#944]
The touch launcher app does not show some icons right on low resolution. For example the settings icon looks like a circle with a weird outline and the school calendar icon is messed up. Also, when you turn on high resolution the icons are fine, but the animation of moving between app icons flashes. I put images below. Sorry for the bad quality images.
![image](https://user-images.githubusercontent.com/89286474/143265527-0af2a392-bad2-4d8c-bfd0-607400352d15.png)
![image](https://user-images.githubusercontent.com/89286474/143265678-b3c1460a-092a-40f8-9289-7030097687f2.png)

**Comment by gfwilliams** [comment]
This is https://github.com/espruino/Espruino/issues/2049 - if you update your Bangle.js firmware to cutting edge (or 2v11 when it's released soon) it'll be fixed

**Comment by Ronin0000** [comment]
ok! Thanks!
