### ISSUE TITLE
Lock Widget with open lock icon

### ISSUE THREAD

**Issue by profriemke** [espruino/BangleApps#953]
It would be good to have an open lock icon instead of disappearing, which makes the other widgets jump.

**Comment by gfwilliams** [comment]
I wonder whether at a glance it would be harder to tell the difference between an open and closed lock? I guess it could keep the width the same and just keep itself blank so nothing moved around though, but personally that's never really upset me

**Comment by profriemke** [comment]
I tried another icon. You are right, it's only visible when red and green. A fixed width would be a good idea. I tried this with your code and it looks smooth now. Would be a small, but nice improvement.

**Comment by mabuchner** [comment]
> A fixed width would be a good idea. 

With a hidden lock widget, which still takes up space, I would be wondering why my widgets aren't aligned correctly to the left side.

How about just moving the lock widget to the bottom where it is less crowded?

![lock-bl](https://user-images.githubusercontent.com/6006874/144029541-4af9fe50-c391-4c70-a86b-4fdb51bc0270.png)

![lock-br](https://user-images.githubusercontent.com/6006874/144029561-9b4c5f3f-a8f0-40b0-80e9-8810e60b7927.png)

Or make it possible to horizontally center widgets and place the lock widget there?

**Comment by profriemke** [comment]
This could interfere with other apps:

![watch](https://user-images.githubusercontent.com/2960904/144032453-60fb8dc5-9bc3-4109-bc13-cceba2d5436a.png)

btw: the adapted fixed width lock is in the upper left (unlocked).

**Comment by thyttan** [comment]
Candidate for being closed - leave a comment if you object!

Rationale:
Light Switch Widget implements the feature request to a large degree if not completely.

**Comment by gfwilliams** [comment]
If someone cared enough then they could copy the existing lock widget and change it in under 5 minutes.

But just to avoid complaints, I just added `widlockunlock` widget that does exactly this
