### ISSUE TITLE
Timezone ignored when setting time in IDE or App Loader

### ISSUE THREAD

**Issue by profriemke** [espruino/BangleApps#954]
Timezone is ignored in Bangle.js v2 when setting time in IDE or app loader. Within +1 timezone the clock is always set to +0 time.

**Comment by gfwilliams** [comment]
That's an odd one. What does `(new Date()).getTimezoneOffset()` report if you run it in your browser?

The App Loader does definitely set the timezone according to the browser: https://github.com/espruino/EspruinoAppLoaderCore/blob/50aa45f13f06cc2f40684971d4c0a68d061b1f3c/js/comms.js#L292

Although I don't believe the IDE does, so maybe that's what is causing problems?

**Comment by profriemke** [comment]
It returns the correct -60.

**Comment by profriemke** [comment]
It looks ok. Yes, it could also be the IDE since I switch often between them these days.
At the moment I cannot reproduce it, so I think it's good to close.

**Comment by gfwilliams** [comment]
Ok, thanks! If you can reproduce it please let me know though
