### ISSUE TITLE
TimeCal wrong weekday

### ISSUE THREAD

**Issue by Philsan69** [espruino/BangleApps#958]
Today, Sunday 28th November 2021 17:00, appears under the first column (Monday).
Bangle 2, Locale settings Time Zone=1 and Clock style 24hr.
BTW, the app has no icon in the menu.
Thanks to the coder!

**Comment by gfwilliams** [comment]
@madman2021  any ideas?

**Comment by Philsan69** [comment]
Perhaps the fact Bangle2 isn't connected?
Today I found Anton Clock stuck with 0.00 time.
When I connected time has been updated.
Btw, that's no good because watchfaces should work without connection.

**Comment by gfwilliams** [comment]
> Btw, that's no good because watchfaces should work without connection.

They do. I'm not quite sure what's happened in your case - but I imagine you're not using the default apps? Maybe start a post for this in the forum and let us know exactly what apps you have installed http://forum.espruino.com/microcosms/1424/

**Comment by gfwilliams** [comment]
I believe this is now fixed with an updated timecal
