### ISSUE TITLE
messages app should not pop up with old messages

### ISSUE THREAD

**Issue by mabuchner** [espruino/BangleApps#968]
I've installed the messages app and the iOS integration on my Bangle.js 2.

Whenever I'm walking around in the house without my phone in the pocket, the messages app keeps popping up with old messages.

I guess, this is happening, because all notifications on my phone are treated as new notifications whenever the bluetooth connection gets re-established.

I don't mind having old messages appear in the messages app, but the messages app should not pop up, if there are no new messages.

**Comment by stephenPspackman** [comment]
FYI I've seen old messages show up in Android, too—though my device is known to have had more profound mental issues.
