### ISSUE TITLE
messages app should have better overflow behaviour

### ISSUE THREAD

**Issue by mabuchner** [espruino/BangleApps#969]
The text in the messages app overflows really easy

![messages-overflow](https://user-images.githubusercontent.com/6006874/144020429-80230a92-ad35-4354-8632-141be3bd30e8.png)

This  shouldn't happen. Longer messages should get truncated with an option to scroll up and down.

The UI should probably get changed a bit. Otherwise, the available space for the text is just too small.

**Comment by gfwilliams** [comment]
Thanks - yes, good point. This definitely wasn't intended to be final - I just wanted to get something there for when we shipped.

Actually restricting the amount of lines drawn should be just a few lines of code.
