### ISSUE TITLE
Closing app launcher with short button press

### ISSUE THREAD

**Issue by mabuchner** [espruino/BangleApps#971]
Right now it feels a bit unnatural for me to close the app launcher on my Bangle.js 2 via a button press.

I would expect, that a short button press is sufficient to go back, but one has to deliberately hold down until the loading message appears.

It would be nice, if a short button press would be sufficient.

**Comment by gfwilliams** [comment]
Yes - it's been suggested that on other devices with a single button, the button is generally used to go Back and the touchscreen used to go forward - so I think we might move in that direction

**Comment by mabuchner** [comment]
Wouldn't adding the following code (which I found int he About app) in the [launcher](https://github.com/espruino/BangleApps/tree/master/apps/launch) already be sufficient?

```js
setWatch(_=>load(), BTN1);
```

**Comment by gfwilliams** [comment]
Yes, that should work just fine
