### ISSUE TITLE
Some issues with the GPS Recorder App

### ISSUE THREAD

**Issue by sebi5361** [espruino/BangleApps#98]
### 1.
The GPS Recorder App (its corresponding widget) modifies the color of the Watch Face.
Should the Watch Face App be corrected or should it be the GPS Recorder App?
![IMG_3369](https://user-images.githubusercontent.com/18078043/74375124-121b1800-4de0-11ea-839a-b1fec645045a.jpg)

### 2.
Despite the Watch Face showing the proper time, the date and time of the recorded track are wrong.
![Image](https://user-images.githubusercontent.com/18078043/74375294-5a3a3a80-4de0-11ea-9fdf-02529cc138a2.png)

### 3.
The last character of the .gpsrc0 files is not displayed correctly in the App Loader (Windows 10).
![Image  2](https://user-images.githubusercontent.com/18078043/74375384-805fda80-4de0-11ea-8c96-f5ce8ef44946.png)

### 4.
There are some minor tabulation issues in the .kml file.
![Image](https://user-images.githubusercontent.com/18078043/74381035-0719b500-4deb-11ea-8650-d728d31de361.png)

**Comment by gfwilliams** [comment]
1. Watch Face App - this should be changed in the watch app. `g.reset()` would be good to put before the draw call in each one.

2. Just fixed this - my quick attempt at rounding cropped it down to a 32 bit int :)

3. Just filed an issue for this - it's not to do with GPS: https://github.com/espruino/BangleApps/issues/99

4. Fixed now. The file still works fine though?

**Comment by sebi5361** [comment]
Still a small bug with the track date displayed by the watch:
![IMG_3370](https://user-images.githubusercontent.com/18078043/74545086-9092c980-4f48-11ea-8600-2699326506f4.JPG)

**Comment by gfwilliams** [comment]
And that's for a new track? Not one of the old ones recorded before the fix?

**Comment by sebi5361** [comment]
Indeed it is.
The date displays fine here since the fix:
![Image](https://user-images.githubusercontent.com/18078043/74375294-5a3a3a80-4de0-11ea-9fdf-02529cc138a2.png)
...but not there:
![IMG_3370](https://user-images.githubusercontent.com/18078043/74545086-9092c980-4f48-11ea-8600-2699326506f4.JPG)

**Comment by sebi5361** [comment]
I think this issue just has to do with `Date().getTime()` being in ms while `getTime()` is in seconds.
Thus `Date(getTime()*1000)` is the proper formula.

**Comment by gfwilliams** [comment]
I think in this case it might just be the `0|` - same fix I made for the widget, but just in the app.js: https://github.com/espruino/BangleApps/commit/619786cae00d8d536324afacc9ac79c943ebc31d#diff-80e5d79fdecd6bca9027b76a523689acL46

**Comment by sebi5361** [comment]
Hi Gordon, I have checked your fix and am still getting the wrong date and time on the watch~~

**Comment by gfwilliams** [comment]
Ok, thanks. Fixed (and tested) for reals this time - I should have wrapped it in a `parseInt`

**Comment by sebi5361** [comment]
Indeed it works fine. However there is a Time-Zone hour difference between the time read on the watch and the one when downloading the file. It might be due to using `toISOString()`.

**Comment by gfwilliams** [comment]
Hmm, that's an interesting one. The time itself is just sent over as a raw value of milliseconds since 1970 (standard unix timestamp) - on the watch it's interpreted using the current timezone that's specified in settings, and I'd assumed the same would happen on the PC!
