### ISSUE TITLE
Astronomical step counts on GadgetBridge

### ISSUE THREAD

**Issue by aivopaas** [espruino/BangleApps#985]
For unknown reasons I'm getting quite comical activity reports on GadgetBridge from Bangle 2.
Everything should be on the latest versions.
Haven't tried debugging it yet in any way so I have no idea which component exactly might be causing it (I'm pretty sure it's not my feet though).

That's yesterdays data, today I'm going to pass the 2000 km mark easily.

![SmartSelect_20211201-181316_Gadgetbridge](https://user-images.githubusercontent.com/191152/144469577-5ba016d5-c84b-42a5-a1a3-d26973860696.jpg)

**Comment by gfwilliams** [comment]
Wow! Which app are you running on the Bangle? Gadgetbridge or Android?

The step reporting stuff will be in whichever ones of those are used - maybe it's not resetting the counter so is accumulating each time an update is posted

**Comment by myxor** [comment]
Glad to see i am not the only one having similar step counts :)
I am using the Active Pedometer and the Android apps on the Bangle.js 1.

**Comment by CountMurphy** [comment]
Same here. GadgetBridge and Active Pedometer installed here, though mine only did it once.

**Comment by CountMurphy** [comment]
After installing the Android app, my counts are normal/correct

**Comment by gfwilliams** [comment]
Fixed with #1058 now!
