### ISSUE TITLE
Messages app: Notifications won't vibrate?

### ISSUE THREAD

**Issue by holycow234234** [espruino/BangleApps#999]
Messages show up correctly, they just do not vibrate.
Not sure if this is a setting I have to turn on or what?
Quiet Mode is off.
Vibration is on.
Vibrate in messages settings is set to --- and 4s.
The motor works as it vibrates when going though menus, etc.
I'm using messages 0.07

Edit: Android integration 0.04.
I uninstalled notifyfs, and the gadgetbridge integration

**Comment by elrod16** [comment]
I got it working by uninstalling gadgetbridge watch app but keeping notifyfs

**Comment by holycow234234** [comment]
That didn't work for me. 
Something else of potential interest is after uninstalling Android+Messages, and reinstalling GadgetBridge, vibration wouldn't work for notifications until I rebooted the watch

**Comment by CountMurphy** [comment]
Same issue here. Moving back to gadgetbridge app until fixed.

**Comment by gfwilliams** [comment]
Are we saying that this is likely some issue caused by having *both* Gadgetbridge and Android installed at the same time?

**Comment by holycow234234** [comment]
For me at least, it was one or the other.
Anyway, your fix worked for me. Thanks!

**Comment by CountMurphy** [comment]
The fix worked for a little bit, but now it no longer buzzes. Buzzer is working for other apps. I've completely uninstalled android and messages and then reinstalled them. No buzz on email (gmail) or duo pushes.

**Comment by gfwilliams** [comment]
Are you using the development app loader, because the fix I did this morning isn't yet live on banglejs.com/apps?.
